SELECT
    [ID],
    [PARENT_CATEGORY_ID],
    [NAME],
    [SLUG],
    [IS_ACTIVE]
FROM [dbo].[CATEGORIES]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;