UPDATE [dbo].[CATEGORIES]
SET
    [PARENT_CATEGORY_ID] = @PRM_CATEGORY_PARENT_CATEGORY_ID,
    [NAME] = @PRM_CATEGORY_NAME,
    [SLUG] = @PRM_CATEGORY_SLUG,
    [IS_ACTIVE] = @PRM_CATEGORY_IS_ACTIVE
WHERE
    [ID] = @PRM_CATEGORY_ID
    AND [IsDeleted] = 0;