INSERT INTO [dbo].[CATEGORIES] (
    [PARENT_CATEGORY_ID],
    [NAME],
    [SLUG],
    [IS_ACTIVE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_CATEGORY_PARENT_CATEGORY_ID,
    @PRM_CATEGORY_NAME,
    @PRM_CATEGORY_SLUG,
    @PRM_CATEGORY_IS_ACTIVE
    );