SELECT PR.[ID] AS PRODUCT_REVIEW_ID,
	PR.[RATING] AS PRODUCT_REVIEW_RATING,
	PR.[COMMENT] AS PRODUCT_REVIEW_COMMENT,
	P.[TITLE] AS PRODUCT_TITLE 
FROM [PRODUCT_REVIEWS] PR 
	INNER JOIN [PRODUCTS] P 
			ON PR.[PRODUCT_ID] = P.[ID] 
WHERE PR.[IsDeleted] = 0 
	AND P.[IsDeleted] = 0 
	AND PR.[PRODUCT_ID] = @PRM_PRODUCT_REVIEWS_PRODUCT_ID 
	AND PR.[CREATED_AT] > DATEADD(DAY, -30,
	GETDATE()) 
ORDER BY PR.[ID] 