-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 A.[ID], A.[NAME] 
FROM [ATTRIBUTES] A 
WHERE A.[IsDeleted] = 0 
	AND A.[CODE] = @PRM_ATTRIBUTE_CODE 
ORDER BY A.[ID] 