SELECT [USER_ID], [ACCESS_TYPE], [FLAT_ID] 
FROM [USER_SITE_ACCESSES] 
WHERE [IsDeleted] = 0 
	AND [SITE_ID] = @PRM_USER_SITE_ACCESSES_SITE_ID 
	AND [IS_ACTIVE] = @PRM_USER_SITE_ACCESSES_IS_ACTIVE 
ORDER BY  