SELECT TOP 1 [ID], [NAME], [DESCRIPTION], [START_DATE], [END_DATE], [IS_ACTIVE], [PRIORITY], [TEMPLATE_NAME] 
FROM [CAMPAIGNS] 
WHERE [IsDeleted] = 0 
	AND [NAME] = @PRM_CAMPAIGNS_NAME 
ORDER BY [ID] 