SELECT MQ.[ID], MQ.[MESSAGE_ID], MQ.[CAMPAIGN_ID], MQ.[SENDER_ID], MQ.[RECIPIENT], MQ.[SUBJECT], MQ.[BODY], MQ.[PRIORITY], MQ.[STATUS], MQ.[PROCESS_DATE] 
FROM [MESSAGE_QUEUES] MQ 
	INNER JOIN [CAMPAIGNS] C 
			ON MQ.[CAMPAIGN_ID] = C.[ID] 
WHERE MQ.[IsDeleted] = 0 
	AND C.[IsDeleted] = 0 
	AND MQ.[ID] = @PRM_MESSAGE_QUEUES_ID 
	AND C.[ID] = @PRM_CAMPAIGNS_ID 
ORDER BY MQ.[ID] 