//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.SmsManagerModule.Domain.Entities;
using QuickCode.Demo.SmsManagerModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Common.Extensions;
using QuickCode.Demo.SmsManagerModule.Persistence.Contexts;
using QuickCode.Demo.SmsManagerModule.Application.Dtos;

namespace QuickCode.Demo.SmsManagerModule.Persistence.Repositories
{
    public partial class OtpTypesRepository : IOtpTypesRepository
    {
        private readonly WriteDbContext _writeContext;
        private readonly ReadDbContext _readContext;
        private readonly ILogger<OtpTypesRepository> _logger;
        public OtpTypesRepository(ILogger<OtpTypesRepository> logger, WriteDbContext writeContext, ReadDbContext readContext)
        {
            _writeContext = writeContext;
            _readContext = readContext;
            _logger = logger;
        }

        public async Task<RepoResponse<OtpTypes>> InsertAsync(OtpTypes value)
        {
            try
            {
                await _writeContext.OtpTypes.AddAsync(value);
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<OtpTypes>(value, "Not Defined");
            }
            catch (Exception ex)
            {
                return _logger.LogExceptionAndCreateResponse<OtpTypes>(ex, "OtpTypes", "Insert");
            }
        }

        public async Task<RepoResponse<bool>> UpdateAsync(OtpTypes value)
        {
            try
            {
                _writeContext.Set<OtpTypes>().Update(value);
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<bool>(true, "Success");
            }
            catch (Exception ex)
            {
                return _logger.LogExceptionAndCreateResponse<bool>(ex, "OtpTypes", "Update");
            }
        }

        public async Task<RepoResponse<bool>> DeleteAsync(OtpTypes value)
        {
            try
            {
                _writeContext.OtpTypes.Remove(value);
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<bool>(true, "Success");
            }
            catch (Exception ex)
            {
                return _logger.LogExceptionAndCreateResponse<bool>(ex, "OtpTypes", "Delete");
            }
        }

        public async Task<RepoResponse<OtpTypes>> GetByPkAsync(int id)
        {
            try
            {
                var result =
                    from otp_types in _readContext.OtpTypes
                    where otp_types.Id.Equals(id)select otp_types;
                var response = await result.FirstOrDefaultAsync();
                return response == null ? new RepoResponse<OtpTypes>
                {
                    Code = 404,
                    Message = "Not found in OtpTypes"
                }

                : new RepoResponse<OtpTypes>(response, "Success");
            }
            catch (Exception ex)
            {
                return _logger.LogExceptionAndCreateResponse<OtpTypes>(ex, "OtpTypes", "GetByPk");
            }
        }

        public async Task<RepoResponse<List<OtpTypes>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            try
            {
                if (pageNumber.HasValue && pageNumber < 1)
                {
                    return new RepoResponse<List<OtpTypes>>
                    {
                        Code = 404,
                        Message = "Page Number must be greater than 1"
                    };
                }

                var query = _readContext.OtpTypes.AsQueryable();
                if (pageNumber.HasValue && pageSize.HasValue)
                {
                    query = query.Skip((pageNumber.Value - 1) * pageSize.Value).Take(pageSize.Value);
                }

                return new RepoResponse<List<OtpTypes>>(await query.ToListAsync(), "Success");
            }
            catch (Exception ex)
            {
                return _logger.LogExceptionAndCreateResponse<List<OtpTypes>>(ex, "OtpTypes", "List");
            }
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            try
            {
                return new RepoResponse<int>(await _readContext.OtpTypes.CountAsync(), "Success");
            }
            catch (Exception ex)
            {
                return _logger.LogExceptionAndCreateResponse<int>(ex, "OtpTypes", "Count");
            }
        }

        public async Task<RepoResponse<List<OtpTypesOtpMessagesRestResponseDto>>> OtpTypesOtpMessagesRestAsync(int otpTypesId)
        {
            try
            {
                var queryableResult =
                    from otp_messages in _readContext.OtpMessages
                    join otp_types in _readContext.OtpTypes on otp_messages.OtpTypeId equals otp_types.Id
                    where otp_types.Id.Equals(otpTypesId)select new OtpTypesOtpMessagesRestResponseDto()
                    {
                        Id = otp_messages.Id,
                        SmsSenderId = otp_messages.SmsSenderId,
                        OtpTypeId = otp_messages.OtpTypeId,
                        GsmNumber = otp_messages.GsmNumber,
                        OtpCode = otp_messages.OtpCode,
                        Message = otp_messages.Message,
                        ExpireSeconds = otp_messages.ExpireSeconds,
                        MessageDate = otp_messages.MessageDate,
                        MessageSid = otp_messages.MessageSid,
                        DailyCounter = otp_messages.DailyCounter
                    };
                var result = await queryableResult.ToListAsync();
                return new RepoResponse<List<OtpTypesOtpMessagesRestResponseDto>>(result, "Success");
            }
            catch (Exception ex)
            {
                return _logger.LogExceptionAndCreateResponse<List<OtpTypesOtpMessagesRestResponseDto>>(ex, "OtpTypes", "OtpTypesOtpMessagesRest");
            }
        }

        public async Task<RepoResponse<OtpTypesOtpMessagesKeyRestResponseDto>> OtpTypesOtpMessagesKeyRestAsync(int otpTypesId, int otpMessagesId)
        {
            try
            {
                var returnValue = new RepoResponse<OtpTypesOtpMessagesKeyRestResponseDto>();
                var queryableResult =
                    from otp_messages in _readContext.OtpMessages
                    join otp_types in _readContext.OtpTypes on otp_messages.OtpTypeId equals otp_types.Id
                    where otp_types.Id.Equals(otpTypesId) && otp_messages.Id.Equals(otpMessagesId)select new OtpTypesOtpMessagesKeyRestResponseDto()
                    {
                        Id = otp_messages.Id,
                        SmsSenderId = otp_messages.SmsSenderId,
                        OtpTypeId = otp_messages.OtpTypeId,
                        GsmNumber = otp_messages.GsmNumber,
                        OtpCode = otp_messages.OtpCode,
                        Message = otp_messages.Message,
                        ExpireSeconds = otp_messages.ExpireSeconds,
                        MessageDate = otp_messages.MessageDate,
                        MessageSid = otp_messages.MessageSid,
                        DailyCounter = otp_messages.DailyCounter
                    };
                var result = await queryableResult.FirstOrDefaultAsync();
                if (result == null)
                {
                    returnValue.Code = 404;
                    returnValue.Message = $"Not found in OtpTypes";
                }
                else
                {
                    returnValue.Value = result;
                }

                return returnValue;
            }
            catch (Exception ex)
            {
                return _logger.LogExceptionAndCreateResponse<OtpTypesOtpMessagesKeyRestResponseDto>(ex, "OtpTypes", "OtpTypesOtpMessagesKeyRest");
            }
        }
    }
}