SELECT P.[ID], P.[PRODUCT_GROUP_ID], P.[MODEL], P.[TITLE], P.[DETAILS], P.[DESCRIPTION], P.[OPTIONS], P.[PRICE], P.[CURRENCY], P.[STOCK_QUANTITY] 
FROM [CART_ITEMS] CI 
	INNER JOIN [PRODUCTS] P 
			ON CI.[PRODUCT_ID] = P.[ID] 
WHERE CI.[IsDeleted] = 0 
	AND P.[IsDeleted] = 0 
	AND P.[ID] = @PRM_PRODUCTS_ID 
ORDER BY P.[ID] 