SELECT CI.[ID], CI.[CART_ID], CI.[PRODUCT_ID], CI.[QUANTITY], CI.[UNIT_PRICE] 
FROM [CART_ITEMS] CI 
	INNER JOIN [PRODUCTS] P 
			ON CI.[PRODUCT_ID] = P.[ID] 
WHERE CI.[IsDeleted] = 0 
	AND P.[IsDeleted] = 0 
	AND CI.[ID] = @PRM_CART_ITEMS_ID 
	AND P.[ID] = @PRM_PRODUCTS_ID 
ORDER BY CI.[ID] 