SELECT OI.[ID], OI.[ORDER_ID], OI.[PRODUCT_ID], OI.[QUANTITY], OI.[UNIT_PRICE] 
FROM [ORDER_ITEMS] OI 
	INNER JOIN [PRODUCTS] P 
			ON OI.[PRODUCT_ID] = P.[ID] 
WHERE OI.[IsDeleted] = 0 
	AND P.[IsDeleted] = 0 
	AND OI.[ID] = @PRM_ORDER_ITEMS_ID 
	AND P.[ID] = @PRM_PRODUCTS_ID 
ORDER BY OI.[ID] 