SELECT [ID], [TITLE], [PRICE], [CURRENCY] 
FROM [PRODUCTS] 
WHERE [IsDeleted] = 0 
	AND [TITLE] = @PRM_PRODUCTS_TITLE 
	AND [PRICE] = @PRM_PRODUCTS_PRICE 
	AND [PRODUCT_GROUP_ID] = @PRM_PRODUCTS_PRODUCT_GROUP_ID 
ORDER BY [ID] 