SELECT TOP 1 [ID], [NAME], [PHONE_NUMBER], [API_URL], [USERNAME], [PASSWORD], [IS_ACTIVE], [PRIORITY], [DAILY_LIMIT] 
FROM [SENDERS] 
WHERE [IsDeleted] = 0 
	AND [ID] = @PRM_SENDERS_ID 
ORDER BY [ID] 