SELECT MQ.[ID], MQ.[MESSAGE_ID], MQ.[CAMPAIGN_ID], MQ.[SENDER_ID], MQ.[RECIPIENT], MQ.[SUBJECT], MQ.[BODY], MQ.[PRIORITY], MQ.[STATUS], MQ.[PROCESS_DATE] 
FROM [MESSAGE_QUEUES] MQ 
	INNER JOIN [SENDERS] S 
			ON MQ.[SENDER_ID] = S.[ID] 
WHERE MQ.[IsDeleted] = 0 
	AND S.[IsDeleted] = 0 
	AND MQ.[ID] = @PRM_MESSAGE_QUEUES_ID 
	AND S.[ID] = @PRM_SENDERS_ID 
ORDER BY MQ.[ID] 