SELECT S.[ID], S.[NAME], S.[PHONE_NUMBER], S.[API_URL], S.[USERNAME], S.[PASSWORD], S.[IS_ACTIVE], S.[PRIORITY], S.[DAILY_LIMIT] 
FROM [OTP_MESSAGE_LOGS] OML 
	INNER JOIN [SENDERS] S 
			ON OML.[SENDER_ID] = S.[ID] 
WHERE OML.[IsDeleted] = 0 
	AND S.[IsDeleted] = 0 
	AND S.[ID] = @PRM_SENDERS_ID 
ORDER BY S.[ID] 