SELECT OMQ.[ID], OMQ.[SENDER_ID], OMQ.[OTP_MESSAGE_ID], OMQ.[RECIPIENT], OMQ.[OTP_CODE], OMQ.[HASH_CODE], OMQ.[PRIORITY], OMQ.[STATUS], OMQ.[PROCESS_DATE] 
FROM [OTP_MESSAGE_QUEUES] OMQ 
	INNER JOIN [SENDERS] S 
			ON OMQ.[SENDER_ID] = S.[ID] 
WHERE OMQ.[IsDeleted] = 0 
	AND S.[IsDeleted] = 0 
	AND OMQ.[ID] = @PRM_OTP_MESSAGE_QUEUES_ID 
	AND S.[ID] = @PRM_SENDERS_ID 
ORDER BY OMQ.[ID] 