//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.EmailManagerModule.Domain.Entities;
using QuickCode.Demo.EmailManagerModule.Application.Dtos;
using System.Threading.Tasks;

namespace QuickCode.Demo.EmailManagerModule.Application.Interfaces.Repositories
{
    public partial interface IEmailSendersRepository : IBaseRepository<EmailSendersDto>
    {
        Task<RepoResponse<EmailSendersDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<EmailSendersInfoMessagesRestResponseDto>>> EmailSendersInfoMessagesRestAsync(int emailSendersId);
        Task<RepoResponse<EmailSendersInfoMessagesKeyRestResponseDto>> EmailSendersInfoMessagesKeyRestAsync(int emailSendersId, int infoMessagesId);
        Task<RepoResponse<List<EmailSendersOtpMessagesRestResponseDto>>> EmailSendersOtpMessagesRestAsync(int emailSendersId);
        Task<RepoResponse<EmailSendersOtpMessagesKeyRestResponseDto>> EmailSendersOtpMessagesKeyRestAsync(int emailSendersId, int otpMessagesId);
        Task<RepoResponse<List<EmailSendersCampaignMessagesRestResponseDto>>> EmailSendersCampaignMessagesRestAsync(int emailSendersId);
        Task<RepoResponse<EmailSendersCampaignMessagesKeyRestResponseDto>> EmailSendersCampaignMessagesKeyRestAsync(int emailSendersId, int campaignMessagesId);
    }
}