//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.EmailManagerModule.Domain.Entities;
using QuickCode.Demo.EmailManagerModule.Application.Dtos.MessageLog;
using System.Threading.Tasks;
using QuickCode.Demo.EmailManagerModule.Domain.Enums;

namespace QuickCode.Demo.EmailManagerModule.Application.Interfaces.Repositories
{
    public partial interface IMessageLogRepository : IBaseRepository<MessageLogDto>
    {
        Task<RepoResponse<MessageLogDto>> GetByPkAsync(int id);
        Task<RepoResponse<GetByIdResponseDto>> GetByIdAsync(int messageLogsId);
        Task<RepoResponse<List<GetByMessageResponseDto>>> GetByMessageAsync(int messageLogsMessageId);
        Task<RepoResponse<List<GetByCampaignResponseDto>>> GetByCampaignAsync(int messageLogsCampaignId);
        Task<RepoResponse<List<GetBySenderResponseDto>>> GetBySenderAsync(int? messageLogsSenderId);
        Task<RepoResponse<long>> GetLogsCountAsync(int messageLogsCampaignId);
        Task<RepoResponse<List<GetLogsWithSenderResponseDto>>> GetLogsWithSenderAsync(bool sendersIsActive);
    }
}