SELECT [ID], [EXPENSE_ID], [INSTALLMENT_NUMBER], [INSTALLMENT_AMOUNT], [DUE_DATE] 
FROM [EXPENSE_INSTALLMENTS] 
WHERE [IsDeleted] = 0 
	AND [PAID] = @PRM_EXPENSE_INSTALLMENTS_PAID 
	AND [DUE_DATE] < GETDATE() 
ORDER BY [ID] 