SELECT [ID], [APARTMENT_ID], [EXPENSE_ID], [INSTALLMENT_NUMBER], [INSTALLMENT_AMOUNT], [DUE_DATE], [PAID] 
FROM [EXPENSE_INSTALLMENTS] 
WHERE [IsDeleted] = 0 
	AND [SITE_ID] = @PRM_EXPENSE_INSTALLMENTS_SITE_ID 
ORDER BY [ID] 