SELECT [ID], [INSTALLMENT_NUMBER], [INSTALLMENT_AMOUNT], [DUE_DATE] 
FROM [EXPENSE_INSTALLMENTS] 
WHERE [IsDeleted] = 0 
	AND [EXPENSE_ID] = @PRM_EXPENSE_INSTALLMENTS_EXPENSE_ID 
	AND [PAID] = @PRM_EXPENSE_INSTALLMENTS_PAID 
ORDER BY [ID] 