SELECT [ID], [FLAT_ID], [APARTMENT_ID], [YEAR_ID], [MONTH_ID], [PAYMENT_AMOUNT], [FEE_TYPE_ID], [DESCRIPTION] 
FROM [FLAT_PAYMENTS] 
WHERE [IsDeleted] = 0 
	AND [SITE_ID] = @PRM_FLAT_PAYMENTS_SITE_ID 
	AND [PAID] = @PRM_FLAT_PAYMENTS_PAID 
ORDER BY [ID] 