SELECT
    COUNT(*)
FROM [dbo].[SELLER_COMMISSION_ASSIGNMENTS]
WHERE EXISTS (
    SELECT 1
    FROM [dbo].[COMMISSION_MODELS] qc_sd_p
    WHERE qc_sd_p.[ID] = [dbo].[SELLER_COMMISSION_ASSIGNMENTS].[COMMISSION_MODEL_ID]
      AND qc_sd_p.[IsDeleted] = 0);