SELECT
    [SELLER_ID],
    [COMMISSION_MODEL_ID],
    [EFFECTIVE_DATE]
FROM [dbo].[SELLER_COMMISSION_ASSIGNMENTS]
WHERE
    [SELLER_ID] = @PRM_SELLER_COMMISSION_ASSIGNMENT_SELLER_ID
    AND EXISTS (
    SELECT 1
    FROM [dbo].[COMMISSION_MODELS] qc_sd_p
    WHERE qc_sd_p.[ID] = [dbo].[SELLER_COMMISSION_ASSIGNMENTS].[COMMISSION_MODEL_ID]
      AND qc_sd_p.[IsDeleted] = 0);