//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.UserManagerModule.Domain.Entities;
using QuickCode.Demo.UserManagerModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Common;
using QuickCode.Demo.Common.Extensions;
using QuickCode.Demo.Common.Helpers;
using QuickCode.Demo.UserManagerModule.Persistence.Contexts;
using QuickCode.Demo.UserManagerModule.Application.Dtos.ApiPermissionGroup;
using QuickCode.Demo.UserManagerModule.Application.Mappings;
using QuickCode.Demo.UserManagerModule.Application.Sql;
using QuickCode.Demo.UserManagerModule.Domain.Enums;

namespace QuickCode.Demo.UserManagerModule.Persistence.Repositories
{
    public partial class ApiPermissionGroupRepository : BaseRepository, IApiPermissionGroupRepository
    {
        public async Task<RepoResponse<List<GetApiPermissionGroupNamesResponseDto>>> GetApiPermissionGroupNamesAsync(string apiPermissionGroupsPermissionGroupName)
        {
            return await ExecuteWithExceptionHandling("GetApiPermissionGroupNames", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiPermissionGroup.Query.GetApiPermissionGroupNames);
                var parameters = new
                {
                    PRM_ApiPermissionGroups_PermissionGroupName = apiPermissionGroupsPermissionGroupName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetApiPermissionGroupNamesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ApiPermissionGroup");
            });
        }
    }
}