//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.OnlineShopModule.Domain.Entities;
using QuickCode.Demo.OnlineShopModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Common;
using QuickCode.Demo.Common.Extensions;
using QuickCode.Demo.Common.Helpers;
using QuickCode.Demo.OnlineShopModule.Persistence.Contexts;
using QuickCode.Demo.OnlineShopModule.Application.Dtos.UserCoupon;
using QuickCode.Demo.OnlineShopModule.Application.Mappings;
using QuickCode.Demo.OnlineShopModule.Persistence.Sql;
using QuickCode.Demo.OnlineShopModule.Domain.Enums;

namespace QuickCode.Demo.OnlineShopModule.Persistence.Repositories
{
    public partial class UserCouponRepository : BaseRepository, IUserCouponRepository
    {
        public async Task<RepoResponse<int>> UpdateUsedCouponsAsync(bool userCouponsIsUsed, UpdateUsedCouponsRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("UserCoupon", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.UserCoupon.Command.UpdateUsedCoupons);
                var parameters = new
                {
                    USER_COUPONS_IS_USED = updateRequest.UserCouponsIsUsed,
                    PRM_USER_COUPONS_IS_USED = userCouponsIsUsed
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }

        public async Task<RepoResponse<int>> UpdateAllUsedCouponsAsync(UpdateAllUsedCouponsRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("UserCoupon", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.UserCoupon.Command.UpdateAllUsedCoupons);
                var parameters = new
                {
                    USER_COUPONS_IS_USED = updateRequest.UserCouponsIsUsed
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }

        public async Task<RepoResponse<int>> UpdateAllTrueUsedCouponsAsync(UpdateAllTrueUsedCouponsRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("UserCoupon", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.UserCoupon.Command.UpdateAllTrueUsedCoupons);
                var parameters = new
                {
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}