UPDATE C 
	SET C.[ID] = @COUPONS_ID,
	C.[END_DATE] = DATEADD(DAY, -30,
	GETDATE()) 
FROM [COUPONS] C 
	INNER JOIN [USERS] U 
			ON C.[USER_ID] = U.[ID] 
WHERE C.[IsDeleted] = 0 
	AND U.[IsDeleted] = 0 
	AND C.[USER_ID] = @PRM_COUPONS_USER_ID 
	AND C.[START_DATE] <= GETDATE() 
	AND C.[END_DATE] >= GETDATE()