SELECT A.[ID], A.[SITE_ID], A.[NAME], A.[ADDRESS], A.[TOTAL_FLATS], A.[IS_ACTIVE], A.[CREATED_DATE] 
FROM [APARTMENTS] A 
	INNER JOIN [SITES] S 
			ON A.[SITE_ID] = S.[ID] 
WHERE A.[IsDeleted] = 0 
	AND S.[IsDeleted] = 0 
	AND S.[ID] = @PRM_SITES_ID 
ORDER BY A.[ID] 