SELECT EI.[ID], EI.[SITE_ID], EI.[APARTMENT_ID], EI.[EXPENSE_ID], EI.[INSTALLMENT_NUMBER], EI.[TOTAL_INSTALLMENTS], EI.[INSTALLMENT_AMOUNT], EI.[DUE_DATE], EI.[PAID], EI.[PAID_AT], EI.[PAYMENT_TYPE_ID], EI.[CREATED_DATE] 
FROM [EXPENSE_INSTALLMENTS] EI 
	INNER JOIN [SITES] S 
			ON EI.[SITE_ID] = S.[ID] 
WHERE EI.[IsDeleted] = 0 
	AND S.[IsDeleted] = 0 
	AND S.[ID] = @PRM_SITES_ID 
ORDER BY EI.[ID] 