SELECT F.[ID], F.[APARTMENT_ID], F.[SITE_ID], F.[FLAT_NUMBER], F.[FLOOR], F.[SQUARE_METERS], F.[ROOM_COUNT], F.[IS_ACTIVE], F.[CREATED_DATE] 
FROM [FLATS] F 
	INNER JOIN [SITES] S 
			ON F.[SITE_ID] = S.[ID] 
WHERE F.[IsDeleted] = 0 
	AND S.[IsDeleted] = 0 
	AND F.[ID] = @PRM_FLATS_ID 
	AND S.[ID] = @PRM_SITES_ID 
ORDER BY F.[ID] 