SELECT FEI.[ID], FEI.[SITE_ID], FEI.[APARTMENT_ID], FEI.[FLAT_ID], FEI.[EXPENSE_ID], FEI.[EXPENSE_INSTALLMENT_ID], FEI.[FLAT_INSTALLMENT_NUMBER], FEI.[TOTAL_FLAT_INSTALLMENTS], FEI.[FLAT_INSTALLMENT_AMOUNT], FEI.[DUE_DATE], FEI.[PAID], FEI.[PAID_AT], FEI.[PAYMENT_TYPE_ID], FEI.[CREATED_DATE] 
FROM [FLAT_EXPENSE_INSTALLMENTS] FEI 
	INNER JOIN [SITES] S 
			ON FEI.[SITE_ID] = S.[ID] 
WHERE FEI.[IsDeleted] = 0 
	AND S.[IsDeleted] = 0 
	AND S.[ID] = @PRM_SITES_ID 
ORDER BY FEI.[ID] 