SELECT COUNT(*) 
FROM [SITES] S 
	LEFT JOIN [FLAT_CONTACTS] FC 
			ON 1=1 
WHERE S.[IsDeleted] = 0 
	AND FC.[IsDeleted] = 0 
	AND S.[ID] = @PRM_SITES_ID 
	AND FC.[RELATIONSHIP_TYPE] = @PRM_FLAT_CONTACTS_RELATIONSHIP_TYPE 
	AND S.[IS_ACTIVE] = @PRM_SITES_IS_ACTIVE 
ORDER BY S.[ID] 