SELECT TOP 1 SUM(FP.[PAYMENT_AMOUNT]) AS TOTAL_PAYMENTS 
FROM [SITES] S 
	INNER JOIN [FLAT_PAYMENTS] FP 
			ON S.[SITE_ID] = FP.[ID] 
WHERE S.[IsDeleted] = 0 
	AND FP.[IsDeleted] = 0 
	AND S.[ID] = @PRM_SITES_ID 
	AND FP.[PAID] = @PRM_FLAT_PAYMENTS_PAID 