SELECT USA.[ID], USA.[USER_ID], USA.[SITE_ID], USA.[FLAT_ID], USA.[ACCESS_TYPE], USA.[IS_ACTIVE], USA.[GRANTED_DATE], USA.[GRANTED_BY] 
FROM [USER_SITE_ACCESSES] USA 
	INNER JOIN [SITES] S 
			ON USA.[SITE_ID] = S.[ID] 
WHERE USA.[IsDeleted] = 0 
	AND S.[IsDeleted] = 0 
	AND S.[ID] = @PRM_SITES_ID 
ORDER BY USA.[ID] 