//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.ProductCatalogModule.Domain.Entities;
using QuickCode.Demo.ProductCatalogModule.Application.Dtos.Brand;
using System.Threading.Tasks;
using QuickCode.Demo.ProductCatalogModule.Domain.Enums;

namespace QuickCode.Demo.ProductCatalogModule.Application.Interfaces.Repositories
{
    public partial interface IBrandRepository : IBaseRepository<BrandDto>
    {
        Task<RepoResponse<BrandDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<SearchByNameResponseDto>>> SearchByNameAsync(string brandName, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<int>> DeactivateAsync(int brandId, DeactivateRequestDto updateRequest);
    }
}