SELECT P.[ID], P.[SKU], P.[NAME] 
FROM [PRODUCTS] P 
WHERE P.[IsDeleted] = 0 
	AND P.[IS_FEATURED] = 1 
	AND P.[STATUS] = 'ACTIVE' 
ORDER BY P.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 