UPDATE [dbo].[PROMOTIONAL_CAMPAIGNS]
SET
    [NAME] = @PRM_PROMOTIONAL_CAMPAIGN_NAME,
    [START_DATE] = @PRM_PROMOTIONAL_CAMPAIGN_START_DATE,
    [END_DATE] = @PRM_PROMOTIONAL_CAMPAIGN_END_DATE,
    [DISCOUNT_PERCENTAGE] = @PRM_PROMOTIONAL_CAMPAIGN_DISCOUNT_PERCENTAGE,
    [IS_ACTIVE] = @PRM_PROMOTIONAL_CAMPAIGN_IS_ACTIVE
WHERE
    [ID] = @PRM_PROMOTIONAL_CAMPAIGN_ID
    AND [IsDeleted] = 0;