SELECT S.[ID], S.[COMPANY_NAME], S.[STATUS] 
FROM [SELLERS] S 
WHERE S.[IsDeleted] = 0 
	AND S.[COMPANY_NAME] LIKE '%' + @PRM_SELLER_COMPANY_NAME + '%' 
ORDER BY S.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 