SELECT S.[ID], S.[COMPANY_NAME], S.[CONTACT_EMAIL], S.[JOINED_DATE] 
FROM [SELLERS] S 
WHERE S.[IsDeleted] = 0 
	AND S.[STATUS] = @PRM_SELLER_STATUS 
ORDER BY S.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 