UPDATE [dbo].[SHIPPING_METHODS]
SET
    [NAME] = @PRM_SHIPPING_METHOD_NAME,
    [COST] = @PRM_SHIPPING_METHOD_COST,
    [IS_ACTIVE] = @PRM_SHIPPING_METHOD_IS_ACTIVE
WHERE
    [ID] = @PRM_SHIPPING_METHOD_ID
    AND [IsDeleted] = 0;