INSERT INTO [dbo].[SHIPPING_METHODS] (
    [NAME],
    [COST],
    [IS_ACTIVE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_SHIPPING_METHOD_NAME,
    @PRM_SHIPPING_METHOD_COST,
    @PRM_SHIPPING_METHOD_IS_ACTIVE
    );