SELECT PT.[ID] AS PRODUCT_TYPE_ID,
	PT.[NAME] AS PRODUCT_TYPE_NAME,
	PT.[TITLE] AS PRODUCT_TYPE_TITLE 
FROM [PRODUCT_TYPES] PT 
	INNER JOIN [PRODUCT_GROUPS] PG 
			ON PG.[PRODUCT_TYPE_ID] = PT.[ID] 
WHERE PT.[IsDeleted] = 0 
	AND PG.[IsDeleted] = 0 
	AND PG.[PRODUCT_TYPE_ID] = @PRM_PRODUCT_GROUPS_PRODUCT_TYPE_ID 
ORDER BY PT.[ID] 