SELECT PT.[ID], PT.[NAME], PT.[IMAGE_URL], PT.[TITLE] 
FROM [PRODUCT_GROUPS] PG 
	INNER JOIN [PRODUCT_TYPES] PT 
			ON PG.[PRODUCT_TYPE_ID] = PT.[ID] 
WHERE PG.[IsDeleted] = 0 
	AND PT.[IsDeleted] = 0 
	AND PT.[ID] = @PRM_PRODUCT_TYPES_ID 
ORDER BY PT.[ID] 