SELECT PG.[ID], PG.[NAME], PG.[TITLE], PG.[IMAGE_URL], PG.[DESCRIPTION], PG.[CODE], PG.[PRODUCT_TYPE_ID] 
FROM [PRODUCT_GROUPS] PG 
	INNER JOIN [PRODUCT_TYPES] PT 
			ON PG.[PRODUCT_TYPE_ID] = PT.[ID] 
WHERE PG.[IsDeleted] = 0 
	AND PT.[IsDeleted] = 0 
	AND PG.[ID] = @PRM_PRODUCT_GROUPS_ID 
	AND PT.[ID] = @PRM_PRODUCT_TYPES_ID 
ORDER BY PG.[ID] 