SELECT
    [CAMPAIGN_ID],
    [SCOPE],
    [SCOPE_ID]
FROM [dbo].[CAMPAIGN_APPLICABILITIES]
WHERE EXISTS (
    SELECT 1
    FROM [dbo].[PROMOTIONAL_CAMPAIGNS] qc_sd_p
    WHERE qc_sd_p.[ID] = [dbo].[CAMPAIGN_APPLICABILITIES].[CAMPAIGN_ID]
      AND qc_sd_p.[IsDeleted] = 0)
ORDER BY
    [CAMPAIGN_ID],
    [SCOPE],
    [SCOPE_ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;