INSERT INTO [dbo].[CAMPAIGN_APPLICABILITIES] (
    [CAMPAIGN_ID],
    [SCOPE],
    [SCOPE_ID]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_CAMPAIGN_APPLICABILITY_CAMPAIGN_ID,
    @PRM_CAMPAIGN_APPLICABILITY_SCOPE,
    @PRM_CAMPAIGN_APPLICABILITY_SCOPE_ID
    );