DELETE FROM [dbo].[CAMPAIGN_APPLICABILITIES]
WHERE
    [CAMPAIGN_ID] = @PRM_CAMPAIGN_APPLICABILITY_CAMPAIGN_ID AND
    [SCOPE] = @PRM_CAMPAIGN_APPLICABILITY_SCOPE AND
    [SCOPE_ID] = @PRM_CAMPAIGN_APPLICABILITY_SCOPE_ID
    AND EXISTS (
    SELECT 1
    FROM [dbo].[PROMOTIONAL_CAMPAIGNS] qc_sd_p
    WHERE qc_sd_p.[ID] = [dbo].[CAMPAIGN_APPLICABILITIES].[CAMPAIGN_ID]
      AND qc_sd_p.[IsDeleted] = 0);