SELECT [ID], [CARGO_COMPANY], [STATUS], [SHIPPED_DATE], [DELIVERED_DATE] 
FROM [SHIPMENTS] 
WHERE [IsDeleted] = 0 
	AND [TRACKING_CODE] = @PRM_SHIPMENTS_TRACKING_CODE 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 