SELECT
    [ID],
    [SELLER_ID],
    [NAME],
    [SLUG],
    [DESCRIPTION],
    [LOGO_URL],
    [IS_ACTIVE]
FROM [dbo].[STORES]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;