UPDATE [dbo].[STORES]
SET
    [SELLER_ID] = @PRM_STORE_SELLER_ID,
    [NAME] = @PRM_STORE_NAME,
    [SLUG] = @PRM_STORE_SLUG,
    [DESCRIPTION] = @PRM_STORE_DESCRIPTION,
    [LOGO_URL] = @PRM_STORE_LOGO_URL,
    [IS_ACTIVE] = @PRM_STORE_IS_ACTIVE
WHERE
    [ID] = @PRM_STORE_ID
    AND [IsDeleted] = 0;