INSERT INTO [dbo].[STORES] (
    [SELLER_ID],
    [NAME],
    [SLUG],
    [DESCRIPTION],
    [LOGO_URL],
    [IS_ACTIVE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_STORE_SELLER_ID,
    @PRM_STORE_NAME,
    @PRM_STORE_SLUG,
    @PRM_STORE_DESCRIPTION,
    @PRM_STORE_LOGO_URL,
    @PRM_STORE_IS_ACTIVE
    );