//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.OnlineShopModule.Application.Dtos.CompanyInfo;
using QuickCode.Demo.OnlineShopModule.Domain.Entities;
using QuickCode.Demo.OnlineShopModule.Domain.Enums;

namespace QuickCode.Demo.OnlineShopModule.Application.Mappings
{
    public static class CompanyInfoMappings
    {
        public static List<CompanyInfoDto> ToDto(this IEnumerable<CompanyInfo> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static CompanyInfoDto ToDto(this CompanyInfo model)
        {
            return new CompanyInfoDto
            {
                Id = model.Id,
                Name = model.Name,
                Address = model.Address,
                City = model.City,
                Country = model.Country,
                AboutUs = model.AboutUs,
                Email = model.Email,
                Phone = model.Phone,
                Longitude = model.Longitude,
                Latitude = model.Latitude,
                CompanyIconUrl = model.CompanyIconUrl,
                CompanyLogoUrl = model.CompanyLogoUrl
            };
        }

        public static CompanyInfo ToEntity(this CompanyInfoDto model)
        {
            return new CompanyInfo
            {
                Id = model.Id,
                Name = model.Name,
                Address = model.Address,
                City = model.City,
                Country = model.Country,
                AboutUs = model.AboutUs,
                Email = model.Email,
                Phone = model.Phone,
                Longitude = model.Longitude,
                Latitude = model.Latitude,
                CompanyIconUrl = model.CompanyIconUrl,
                CompanyLogoUrl = model.CompanyLogoUrl
            };
        }
    }
}