// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.PricingEngineModule.Domain.Entities;
using QuickCode.Demo.PricingEngineModule.Application.Interfaces.Repositories;
using QuickCode.Demo.PricingEngineModule.Application.Dtos.SellerCommissionAssignment;
using QuickCode.Demo.PricingEngineModule.Domain.Enums;

namespace QuickCode.Demo.PricingEngineModule.Application.Features.SellerCommissionAssignment
{
    public class ListSellerCommissionAssignmentQuery : IRequest<Response<List<SellerCommissionAssignmentDto>>>
    {
        public int? PageNumber { get; set; }
        public int? PageSize { get; set; }

        public ListSellerCommissionAssignmentQuery(int? pageNumber, int? pageSize)
        {
            this.PageNumber = pageNumber;
            this.PageSize = pageSize;
        }

        public class ListSellerCommissionAssignmentHandler : IRequestHandler<ListSellerCommissionAssignmentQuery, Response<List<SellerCommissionAssignmentDto>>>
        {
            private readonly ILogger<ListSellerCommissionAssignmentHandler> _logger;
            private readonly ISellerCommissionAssignmentRepository _repository;
            public ListSellerCommissionAssignmentHandler(ILogger<ListSellerCommissionAssignmentHandler> logger, ISellerCommissionAssignmentRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<SellerCommissionAssignmentDto>>> Handle(ListSellerCommissionAssignmentQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.ListAsync(request.PageNumber, request.PageSize);
                return returnValue.ToResponse();
            }
        }
    }
}