SELECT AV.[ID], AV.[VALUE] 
FROM [ATTRIBUTE_VALUES] AV 
WHERE AV.[IsDeleted] = 0 
	AND AV.[ATTRIBUTE_ID] = @PRM_ATTRIBUTE_VALUE_ATTRIBUTE_ID 
ORDER BY AV.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 