UPDATE [dbo].[FINANCIAL_ADJUSTMENTS]
SET
    [SELLER_ID] = @PRM_FINANCIAL_ADJUSTMENT_SELLER_ID,
    [AMOUNT] = @PRM_FINANCIAL_ADJUSTMENT_AMOUNT,
    [REASON] = @PRM_FINANCIAL_ADJUSTMENT_REASON,
    [NOTES] = @PRM_FINANCIAL_ADJUSTMENT_NOTES,
    [CREATED_BY_USER_ID] = @PRM_FINANCIAL_ADJUSTMENT_CREATED_BY_USER_ID,
    [CREATED_DATE] = @PRM_FINANCIAL_ADJUSTMENT_CREATED_DATE
WHERE
    [ID] = @PRM_FINANCIAL_ADJUSTMENT_ID
    AND [IsDeleted] = 0;