SELECT
    [ID],
    [SELLER_ID],
    [AMOUNT],
    [REASON],
    [NOTES],
    [CREATED_BY_USER_ID],
    [CREATED_DATE]
FROM [dbo].[FINANCIAL_ADJUSTMENTS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;