INSERT INTO [dbo].[FINANCIAL_ADJUSTMENTS] (
    [SELLER_ID],
    [AMOUNT],
    [REASON],
    [NOTES],
    [CREATED_BY_USER_ID],
    [CREATED_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_FINANCIAL_ADJUSTMENT_SELLER_ID,
    @PRM_FINANCIAL_ADJUSTMENT_AMOUNT,
    @PRM_FINANCIAL_ADJUSTMENT_REASON,
    @PRM_FINANCIAL_ADJUSTMENT_NOTES,
    @PRM_FINANCIAL_ADJUSTMENT_CREATED_BY_USER_ID,
    @PRM_FINANCIAL_ADJUSTMENT_CREATED_DATE
    );