//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.Demo.PricingEngineModule.Application.Dtos.SellerCommissionAssignment;

namespace QuickCode.Demo.PricingEngineModule.Persistence.Repositories;
internal static class SellerCommissionAssignmentCrudSqlBindings
{
    public const string StoreTableName = "SELLER_COMMISSION_ASSIGNMENTS";
    public const string ParameterNamePrefix = "SELLER_COMMISSION_ASSIGNMENT";
    public const string SellerIdParameterName = "PRM_SELLER_COMMISSION_ASSIGNMENT_SELLER_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByModelId = "GetByModelId";
        public const string GetByPk = "GetByPk";
        public const string GetBySellerId = "GetBySellerId";
        public const string Insert = "Insert";
        public const string RemoveAssignment = "RemoveAssignment";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("SELLER_ID", nameof(SellerCommissionAssignmentDto.SellerId)),
        ("COMMISSION_MODEL_ID", nameof(SellerCommissionAssignmentDto.CommissionModelId)),
        ("EFFECTIVE_DATE", nameof(SellerCommissionAssignmentDto.EffectiveDate))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("COMMISSION_MODEL_ID", nameof(SellerCommissionAssignmentDto.CommissionModelId)),
        ("EFFECTIVE_DATE", nameof(SellerCommissionAssignmentDto.EffectiveDate)),
        ("SELLER_ID", nameof(SellerCommissionAssignmentDto.SellerId))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("SELLER_ID", nameof(SellerCommissionAssignmentDto.SellerId))
    };
}