SELECT PT.[ID], PT.[NAME], PT.[DESCRIPTION], PT.[IS_ACTIVE] 
FROM [COMMON_EXPENSES] CE 
	INNER JOIN [PAYMENT_TYPES] PT 
			ON CE.[PAYMENT_TYPE_ID] = PT.[ID] 
WHERE CE.[IsDeleted] = 0 
	AND PT.[IsDeleted] = 0 
	AND PT.[ID] = @PRM_PAYMENT_TYPES_ID 
ORDER BY CE.[ID] 