SELECT PT.[ID], PT.[NAME], PT.[DESCRIPTION], PT.[IS_ACTIVE] 
FROM [EXPENSE_INSTALLMENTS] EI 
	INNER JOIN [PAYMENT_TYPES] PT 
			ON EI.[PAYMENT_TYPE_ID] = PT.[ID] 
WHERE EI.[IsDeleted] = 0 
	AND PT.[IsDeleted] = 0 
	AND PT.[ID] = @PRM_PAYMENT_TYPES_ID 
ORDER BY PT.[ID] 