SELECT PT.[ID], PT.[NAME], PT.[DESCRIPTION], PT.[IS_ACTIVE] 
FROM [FLAT_PAYMENTS] FP 
	INNER JOIN [PAYMENT_TYPES] PT 
			ON FP.[PAYMENT_TYPE_ID] = PT.[ID] 
WHERE FP.[IsDeleted] = 0 
	AND PT.[IsDeleted] = 0 
	AND PT.[ID] = @PRM_PAYMENT_TYPES_ID 
ORDER BY PT.[ID] 