SELECT PT.[ID], PT.[NAME], PT.[DESCRIPTION], PT.[IS_ACTIVE] 
FROM [FLAT_EXPENSE_INSTALLMENTS] FEI 
	INNER JOIN [PAYMENT_TYPES] PT 
			ON FEI.[PAYMENT_TYPE_ID] = PT.[ID] 
WHERE FEI.[IsDeleted] = 0 
	AND PT.[IsDeleted] = 0 
	AND PT.[ID] = @PRM_PAYMENT_TYPES_ID 
ORDER BY FEI.[ID] 