SELECT CE.[ID], CE.[SITE_ID], CE.[APARTMENT_ID], CE.[NAME], CE.[EXPENSE_TYPE_ID], CE.[YEAR_ID], CE.[MONTH_ID], CE.[EXPENSE_AMOUNT], CE.[DESCRIPTION], CE.[PAID], CE.[PAID_AT], CE.[PAYMENT_TYPE_ID], CE.[CREATED_DATE] 
FROM [COMMON_EXPENSES] CE 
	INNER JOIN [EXPENSE_TYPES] ET 
			ON CE.[EXPENSE_TYPE_ID] = ET.[ID] 
WHERE CE.[IsDeleted] = 0 
	AND ET.[IsDeleted] = 0 
	AND CE.[ID] = @PRM_COMMON_EXPENSES_ID 
	AND ET.[ID] = @PRM_EXPENSE_TYPES_ID 
ORDER BY CE.[ID] 