SELECT ET.[ID], ET.[NAME], ET.[DESCRIPTION], ET.[IS_ACTIVE] 
FROM [COMMON_EXPENSES] CE 
	INNER JOIN [EXPENSE_TYPES] ET 
			ON CE.[EXPENSE_TYPE_ID] = ET.[ID] 
WHERE CE.[IsDeleted] = 0 
	AND ET.[IsDeleted] = 0 
	AND ET.[ID] = @PRM_EXPENSE_TYPES_ID 
ORDER BY ET.[ID] 