//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.EmailManagerModule.Domain.Entities;
using QuickCode.Demo.EmailManagerModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Common;
using QuickCode.Demo.Common.Extensions;
using QuickCode.Demo.Common.Helpers;
using QuickCode.Demo.EmailManagerModule.Persistence.Contexts;
using QuickCode.Demo.EmailManagerModule.Application.Dtos.Sender;
using QuickCode.Demo.EmailManagerModule.Application.Mappings;
using QuickCode.Demo.EmailManagerModule.Persistence.Sql;
using QuickCode.Demo.EmailManagerModule.Domain.Enums;

namespace QuickCode.Demo.EmailManagerModule.Persistence.Repositories
{
    public partial class SenderRepository : BaseRepository, ISenderRepository
    {
        public async Task<RepoResponse<GetByIdResponseDto>> GetByIdAsync(int sendersId)
        {
            return await ExecuteWithExceptionHandling("GetById", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Sender.Query.GetById);
                var parameters = new
                {
                    PRM_SENDERS_ID = sendersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetByIdResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Sender");
            });
        }

        public async Task<RepoResponse<List<GetActiveSendersResponseDto>>> GetActiveSendersAsync(bool sendersIsActive)
        {
            return await ExecuteWithExceptionHandling("GetActiveSenders", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Sender.Query.GetActiveSenders);
                var parameters = new
                {
                    PRM_SENDERS_IS_ACTIVE = sendersIsActive
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetActiveSendersResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Sender");
            });
        }

        public async Task<RepoResponse<GetByNameResponseDto>> GetByNameAsync(string sendersName)
        {
            return await ExecuteWithExceptionHandling("GetByName", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Sender.Query.GetByName);
                var parameters = new
                {
                    PRM_SENDERS_NAME = sendersName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetByNameResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Sender");
            });
        }

        public async Task<RepoResponse<bool>> ExistsByEmailAsync(string sendersEmailAddress)
        {
            return await ExecuteWithExceptionHandling("ExistsByEmail", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Sender.Query.ExistsByEmail);
                var parameters = new
                {
                    PRM_SENDERS_EMAIL_ADDRESS = sendersEmailAddress
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var exists = await connection.ExecuteScalarAsync<bool>(sql, parameters);
                return BuildBoolResponse(exists, $"Not found in Sender");
            });
        }

        public async Task<RepoResponse<List<GetMessageLogsForSendersResponseDto>>> GetMessageLogsForSendersAsync(int sendersId)
        {
            return await ExecuteWithExceptionHandling("GetMessageLogsForSenders", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Sender.Query.GetMessageLogsForSenders);
                var parameters = new
                {
                    PRM_SENDERS_ID = sendersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetMessageLogsForSendersResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Sender");
            });
        }

        public async Task<RepoResponse<GetMessageLogsForSendersResponseDto>> GetMessageLogsForSendersDetailsAsync(int sendersId, int messageLogsId)
        {
            return await ExecuteWithExceptionHandling("GetMessageLogsForSendersDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Sender.Query.GetMessageLogsForSendersDetails);
                var parameters = new
                {
                    PRM_MESSAGE_LOGS_ID = messageLogsId,
                    PRM_SENDERS_ID = sendersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetMessageLogsForSendersResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Sender");
            });
        }

        public async Task<RepoResponse<List<GetOtpMessageLogsForSendersResponseDto>>> GetOtpMessageLogsForSendersAsync(int sendersId)
        {
            return await ExecuteWithExceptionHandling("GetOtpMessageLogsForSenders", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Sender.Query.GetOtpMessageLogsForSenders);
                var parameters = new
                {
                    PRM_SENDERS_ID = sendersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetOtpMessageLogsForSendersResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Sender");
            });
        }

        public async Task<RepoResponse<GetOtpMessageLogsForSendersResponseDto>> GetOtpMessageLogsForSendersDetailsAsync(int sendersId, int otpMessageLogsId)
        {
            return await ExecuteWithExceptionHandling("GetOtpMessageLogsForSendersDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Sender.Query.GetOtpMessageLogsForSendersDetails);
                var parameters = new
                {
                    PRM_OTP_MESSAGE_LOGS_ID = otpMessageLogsId,
                    PRM_SENDERS_ID = sendersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetOtpMessageLogsForSendersResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Sender");
            });
        }

        public async Task<RepoResponse<List<GetMessageQueuesForSendersResponseDto>>> GetMessageQueuesForSendersAsync(int sendersId)
        {
            return await ExecuteWithExceptionHandling("GetMessageQueuesForSenders", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Sender.Query.GetMessageQueuesForSenders);
                var parameters = new
                {
                    PRM_SENDERS_ID = sendersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetMessageQueuesForSendersResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Sender");
            });
        }

        public async Task<RepoResponse<GetMessageQueuesForSendersResponseDto>> GetMessageQueuesForSendersDetailsAsync(int sendersId, int messageQueuesId)
        {
            return await ExecuteWithExceptionHandling("GetMessageQueuesForSendersDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Sender.Query.GetMessageQueuesForSendersDetails);
                var parameters = new
                {
                    PRM_MESSAGE_QUEUES_ID = messageQueuesId,
                    PRM_SENDERS_ID = sendersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetMessageQueuesForSendersResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Sender");
            });
        }

        public async Task<RepoResponse<List<GetOtpMessageQueuesForSendersResponseDto>>> GetOtpMessageQueuesForSendersAsync(int sendersId)
        {
            return await ExecuteWithExceptionHandling("GetOtpMessageQueuesForSenders", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Sender.Query.GetOtpMessageQueuesForSenders);
                var parameters = new
                {
                    PRM_SENDERS_ID = sendersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetOtpMessageQueuesForSendersResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Sender");
            });
        }

        public async Task<RepoResponse<GetOtpMessageQueuesForSendersResponseDto>> GetOtpMessageQueuesForSendersDetailsAsync(int sendersId, int otpMessageQueuesId)
        {
            return await ExecuteWithExceptionHandling("GetOtpMessageQueuesForSendersDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Sender.Query.GetOtpMessageQueuesForSendersDetails);
                var parameters = new
                {
                    PRM_OTP_MESSAGE_QUEUES_ID = otpMessageQueuesId,
                    PRM_SENDERS_ID = sendersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetOtpMessageQueuesForSendersResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Sender");
            });
        }
    }
}