SELECT TC.[ID], TC.[TASK_ID], TC.[USER_ID], TC.[COMMENT], TC.[CREATED_AT] 
FROM [TASK_COMMENTS] TC 
	INNER JOIN [TASKS] T 
			ON TC.[TASK_ID] = T.[ID] 
WHERE TC.[IsDeleted] = 0 
	AND T.[IsDeleted] = 0 
	AND TC.[ID] = @PRM_TASK_COMMENTS_ID 
	AND T.[ID] = @PRM_TASKS_ID 
ORDER BY TC.[ID] 