SELECT T.[ID], T.[TITLE], T.[DESCRIPTION], T.[STATUS], T.[PRIORITY], T.[DUE_DATE], T.[CREATED_AT], T.[UPDATED_AT], T.[USER_ID] 
FROM [TASK_COMMENTS] TC 
	INNER JOIN [TASKS] T 
			ON TC.[TASK_ID] = T.[ID] 
WHERE TC.[IsDeleted] = 0 
	AND T.[IsDeleted] = 0 
	AND T.[ID] = @PRM_TASKS_ID 
ORDER BY T.[ID] 