// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.PricingEngineModule.Domain.Entities;
using QuickCode.Demo.PricingEngineModule.Application.Interfaces.Repositories;
using QuickCode.Demo.PricingEngineModule.Application.Dtos.CommissionRule;
using QuickCode.Demo.PricingEngineModule.Domain.Enums;

namespace QuickCode.Demo.PricingEngineModule.Application.Features.CommissionRule
{
    public class ListCommissionRuleQuery : IRequest<Response<List<CommissionRuleDto>>>
    {
        public int? PageNumber { get; set; }
        public int? PageSize { get; set; }

        public ListCommissionRuleQuery(int? pageNumber, int? pageSize)
        {
            this.PageNumber = pageNumber;
            this.PageSize = pageSize;
        }

        public class ListCommissionRuleHandler : IRequestHandler<ListCommissionRuleQuery, Response<List<CommissionRuleDto>>>
        {
            private readonly ILogger<ListCommissionRuleHandler> _logger;
            private readonly ICommissionRuleRepository _repository;
            public ListCommissionRuleHandler(ILogger<ListCommissionRuleHandler> logger, ICommissionRuleRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<CommissionRuleDto>>> Handle(ListCommissionRuleQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.ListAsync(request.PageNumber, request.PageSize);
                return returnValue.ToResponse();
            }
        }
    }
}