SELECT FP.[ID], FP.[SITE_ID], FP.[FLAT_ID], FP.[APARTMENT_ID], FP.[YEAR_ID], FP.[MONTH_ID], FP.[PAYMENT_AMOUNT], FP.[FEE_TYPE_ID], FP.[DESCRIPTION], FP.[FEE_PLAN_ID], FP.[EXPENSE_ID], FP.[PAID], FP.[PAID_AT], FP.[PAYMENT_TYPE_ID], FP.[CREATED_DATE] 
FROM [FLAT_PAYMENTS] FP 
	INNER JOIN [FEE_TYPES] FT 
			ON FP.[FEE_TYPE_ID] = FT.[ID] 
WHERE FP.[IsDeleted] = 0 
	AND FT.[IsDeleted] = 0 
	AND FP.[ID] = @PRM_FLAT_PAYMENTS_ID 
	AND FT.[ID] = @PRM_FEE_TYPES_ID 
ORDER BY FP.[ID] 