SELECT FT.[ID], FT.[NAME], FT.[DESCRIPTION], FT.[IS_ACTIVE] 
FROM [FLAT_PAYMENTS] FP 
	INNER JOIN [FEE_TYPES] FT 
			ON FP.[FEE_TYPE_ID] = FT.[ID] 
WHERE FP.[IsDeleted] = 0 
	AND FT.[IsDeleted] = 0 
	AND FT.[ID] = @PRM_FEE_TYPES_ID 
ORDER BY FP.[ID] 