SELECT [SITE_ID], [FLAT_ID], [ACCESS_TYPE] 
FROM [USER_SITE_ACCESSES] 
WHERE [IsDeleted] = 0 
	AND [USER_ID] = @PRM_USER_SITE_ACCESSES_USER_ID 
	AND [IS_ACTIVE] = @PRM_USER_SITE_ACCESSES_IS_ACTIVE 
ORDER BY [ID] 