SELECT TOP 1 SBA.[ID], SBA.[IBAN], SBA.[IS_VERIFIED] 
FROM [SELLER_BANK_ACCOUNTS] SBA 
WHERE SBA.[IsDeleted] = 0 
	AND SBA.[SELLER_ID] = @PRM_SELLER_BANK_ACCOUNT_SELLER_ID 
	AND SBA.[IS_DEFAULT] = @PRM_SELLER_BANK_ACCOUNT_IS_DEFAULT 
ORDER BY SBA.[ID] 