SELECT SBA.[ID], SBA.[BANK_NAME], SBA.[ACCOUNT_HOLDER_NAME], SBA.[IBAN], SBA.[IS_DEFAULT], SBA.[IS_VERIFIED] 
FROM [SELLER_BANK_ACCOUNTS] SBA 
WHERE SBA.[IsDeleted] = 0 
	AND SBA.[SELLER_ID] = @PRM_SELLER_BANK_ACCOUNT_SELLER_ID 
ORDER BY SBA.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 