SELECT SCA.[SELLER_ID], SCA.[EFFECTIVE_DATE] 
FROM [SELLER_COMMISSION_ASSIGNMENTS] SCA 
WHERE SCA.[COMMISSION_MODEL_ID] = @PRM_SELLER_COMMISSION_ASSIGNMENT_COMMISSION_MODEL_ID 
ORDER BY SCA.[SELLER_ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 