SELECT [ID], [SENDER_ID], [OTP_MESSAGE_ID], [RECIPIENT], [OTP_CODE], [HASH_CODE], [TEMPLATE_NAME], [STATUS], [EXPIRE_TIME_SECONDS] 
FROM [OTP_MESSAGE_LOGS] 
WHERE [IsDeleted] = 0 
	AND [STATUS] = @PRM_OTP_MESSAGE_LOGS_STATUS 
ORDER BY [ID] 