SELECT L.[ID], L.[RECIPIENT], M.[OTP_CODE] 
FROM [OTP_MESSAGE_LOGS] L 
	INNER JOIN [OTP_MESSAGES] M 
			ON L.[OTP_MESSAGE_ID] = M.[ID] 
WHERE L.[IsDeleted] = 0 
	AND M.[IsDeleted] = 0 
	AND L.[STATUS] = @PRM_OTP_MESSAGE_LOGS_STATUS 
ORDER BY L.[ID] 