SELECT
    [ID],
    [SELLER_ID],
    [TRANSACTION_TYPE],
    [AMOUNT],
    [REFERENCE_ID],
    [DESCRIPTION],
    [TRANSACTION_DATE]
FROM [dbo].[TRANSACTION_LEDGERS]
WHERE
    [ID] = @PRM_TRANSACTION_LEDGER_ID
    AND [IsDeleted] = 0;