UPDATE [dbo].[TRANSACTION_LEDGERS]
SET
    [SELLER_ID] = @PRM_TRANSACTION_LEDGER_SELLER_ID,
    [TRANSACTION_TYPE] = @PRM_TRANSACTION_LEDGER_TRANSACTION_TYPE,
    [AMOUNT] = @PRM_TRANSACTION_LEDGER_AMOUNT,
    [REFERENCE_ID] = @PRM_TRANSACTION_LEDGER_REFERENCE_ID,
    [DESCRIPTION] = @PRM_TRANSACTION_LEDGER_DESCRIPTION,
    [TRANSACTION_DATE] = @PRM_TRANSACTION_LEDGER_TRANSACTION_DATE
WHERE
    [ID] = @PRM_TRANSACTION_LEDGER_ID
    AND [IsDeleted] = 0;