SELECT
    [ID],
    [SELLER_ID],
    [TRANSACTION_TYPE],
    [AMOUNT],
    [REFERENCE_ID],
    [DESCRIPTION],
    [TRANSACTION_DATE]
FROM [dbo].[TRANSACTION_LEDGERS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;