INSERT INTO [dbo].[TRANSACTION_LEDGERS] (
    [SELLER_ID],
    [TRANSACTION_TYPE],
    [AMOUNT],
    [REFERENCE_ID],
    [DESCRIPTION],
    [TRANSACTION_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_TRANSACTION_LEDGER_SELLER_ID,
    @PRM_TRANSACTION_LEDGER_TRANSACTION_TYPE,
    @PRM_TRANSACTION_LEDGER_AMOUNT,
    @PRM_TRANSACTION_LEDGER_REFERENCE_ID,
    @PRM_TRANSACTION_LEDGER_DESCRIPTION,
    @PRM_TRANSACTION_LEDGER_TRANSACTION_DATE
    );