SELECT
    [ID],
    [SELLER_ID],
    [BANK_NAME],
    [ACCOUNT_HOLDER_NAME],
    [IBAN],
    [IS_DEFAULT],
    [IS_VERIFIED]
FROM [dbo].[SELLER_BANK_ACCOUNTS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;