//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.OnlineShopModule.Domain.Entities;
using QuickCode.Demo.OnlineShopModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Common;
using QuickCode.Demo.Common.Extensions;
using QuickCode.Demo.Common.Helpers;
using QuickCode.Demo.OnlineShopModule.Persistence.Contexts;
using QuickCode.Demo.OnlineShopModule.Application.Dtos.Payment;
using QuickCode.Demo.OnlineShopModule.Application.Mappings;
using QuickCode.Demo.OnlineShopModule.Persistence.Sql;
using QuickCode.Demo.OnlineShopModule.Domain.Enums;

namespace QuickCode.Demo.OnlineShopModule.Persistence.Repositories
{
    public partial class PaymentRepository : BaseRepository, IPaymentRepository
    {
        public async Task<RepoResponse<int>> MarkPaymentFailedAsync(PaymentStatus paymentsStatus, MarkPaymentFailedRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Payment", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Payment.Command.MarkPaymentFailed);
                var parameters = new
                {
                    PRM_PAYMENTS_STATUS = paymentsStatus
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}