//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.SmsManagerModule.Domain.Entities;
using QuickCode.Demo.SmsManagerModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Common;
using QuickCode.Demo.Common.Extensions;
using QuickCode.Demo.Common.Helpers;
using QuickCode.Demo.SmsManagerModule.Persistence.Contexts;
using QuickCode.Demo.SmsManagerModule.Application.Dtos.OtpMessage;
using QuickCode.Demo.SmsManagerModule.Application.Mappings;
using QuickCode.Demo.SmsManagerModule.Persistence.Sql;
using QuickCode.Demo.SmsManagerModule.Domain.Enums;

namespace QuickCode.Demo.SmsManagerModule.Persistence.Repositories
{
    public partial class OtpMessageRepository : BaseRepository, IOtpMessageRepository
    {
        public async Task<RepoResponse<GetByIdResponseDto>> GetByIdAsync(int otpMessagesId)
        {
            return await ExecuteWithExceptionHandling("GetById", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.OtpMessage.Query.GetById);
                var parameters = new
                {
                    PRM_OTP_MESSAGES_ID = otpMessagesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetByIdResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in OtpMessage");
            });
        }

        public async Task<RepoResponse<List<GetByRecipientResponseDto>>> GetByRecipientAsync(string otpMessagesRecipient)
        {
            return await ExecuteWithExceptionHandling("GetByRecipient", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.OtpMessage.Query.GetByRecipient);
                var parameters = new
                {
                    PRM_OTP_MESSAGES_RECIPIENT = otpMessagesRecipient
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetByRecipientResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in OtpMessage");
            });
        }

        public async Task<RepoResponse<bool>> ExistsByHashAsync(string otpMessagesHashCode)
        {
            return await ExecuteWithExceptionHandling("ExistsByHash", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.OtpMessage.Query.ExistsByHash);
                var parameters = new
                {
                    PRM_OTP_MESSAGES_HASH_CODE = otpMessagesHashCode
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var exists = await connection.ExecuteScalarAsync<bool>(sql, parameters);
                return BuildBoolResponse(exists, $"Not found in OtpMessage");
            });
        }

        public async Task<RepoResponse<List<GetOtpMessageQueuesForOtpMessagesResponseDto>>> GetOtpMessageQueuesForOtpMessagesAsync(int otpMessagesId)
        {
            return await ExecuteWithExceptionHandling("GetOtpMessageQueuesForOtpMessages", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.OtpMessage.Query.GetOtpMessageQueuesForOtpMessages);
                var parameters = new
                {
                    PRM_OTP_MESSAGES_ID = otpMessagesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetOtpMessageQueuesForOtpMessagesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in OtpMessage");
            });
        }

        public async Task<RepoResponse<GetOtpMessageQueuesForOtpMessagesResponseDto>> GetOtpMessageQueuesForOtpMessagesDetailsAsync(int otpMessagesId, int otpMessageQueuesId)
        {
            return await ExecuteWithExceptionHandling("GetOtpMessageQueuesForOtpMessagesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.OtpMessage.Query.GetOtpMessageQueuesForOtpMessagesDetails);
                var parameters = new
                {
                    PRM_OTP_MESSAGE_QUEUES_ID = otpMessageQueuesId,
                    PRM_OTP_MESSAGES_ID = otpMessagesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetOtpMessageQueuesForOtpMessagesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in OtpMessage");
            });
        }

        public async Task<RepoResponse<List<GetOtpMessageLogsForOtpMessagesResponseDto>>> GetOtpMessageLogsForOtpMessagesAsync(int otpMessagesId)
        {
            return await ExecuteWithExceptionHandling("GetOtpMessageLogsForOtpMessages", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.OtpMessage.Query.GetOtpMessageLogsForOtpMessages);
                var parameters = new
                {
                    PRM_OTP_MESSAGES_ID = otpMessagesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetOtpMessageLogsForOtpMessagesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in OtpMessage");
            });
        }

        public async Task<RepoResponse<GetOtpMessageLogsForOtpMessagesResponseDto>> GetOtpMessageLogsForOtpMessagesDetailsAsync(int otpMessagesId, int otpMessageLogsId)
        {
            return await ExecuteWithExceptionHandling("GetOtpMessageLogsForOtpMessagesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.OtpMessage.Query.GetOtpMessageLogsForOtpMessagesDetails);
                var parameters = new
                {
                    PRM_OTP_MESSAGE_LOGS_ID = otpMessageLogsId,
                    PRM_OTP_MESSAGES_ID = otpMessagesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetOtpMessageLogsForOtpMessagesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in OtpMessage");
            });
        }
    }
}