UPDATE [dbo].[SELLER_DOCUMENTS]
SET
    [SELLER_ID] = @PRM_SELLER_DOCUMENT_SELLER_ID,
    [DOCUMENT_TYPE] = @PRM_SELLER_DOCUMENT_DOCUMENT_TYPE,
    [FILE_URL] = @PRM_SELLER_DOCUMENT_FILE_URL,
    [STATUS] = @PRM_SELLER_DOCUMENT_STATUS,
    [UPLOADED_DATE] = @PRM_SELLER_DOCUMENT_UPLOADED_DATE,
    [REVIEWED_DATE] = @PRM_SELLER_DOCUMENT_REVIEWED_DATE,
    [REJECTION_REASON] = @PRM_SELLER_DOCUMENT_REJECTION_REASON
WHERE
    [ID] = @PRM_SELLER_DOCUMENT_ID
    AND [IsDeleted] = 0;