//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.ApartmentManageModule.Domain.Entities;
using QuickCode.Demo.ApartmentManageModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Common;
using QuickCode.Demo.Common.Extensions;
using QuickCode.Demo.Common.Helpers;
using QuickCode.Demo.ApartmentManageModule.Persistence.Contexts;
using QuickCode.Demo.ApartmentManageModule.Application.Dtos.FeeType;
using QuickCode.Demo.ApartmentManageModule.Application.Mappings;
using QuickCode.Demo.ApartmentManageModule.Application.Sql;
using QuickCode.Demo.ApartmentManageModule.Domain.Enums;

namespace QuickCode.Demo.ApartmentManageModule.Persistence.Repositories
{
    public partial class FeeTypeRepository : BaseRepository, IFeeTypeRepository
    {
        public async Task<RepoResponse<List<GetActiveFeeTypesResponseDto>>> GetActiveFeeTypesAsync(bool feeTypesIsActive)
        {
            return await ExecuteWithExceptionHandling("GetActiveFeeTypes", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.FeeType.Query.GetActiveFeeTypes);
                var parameters = new
                {
                    PRM_FEE_TYPES_IS_ACTIVE = feeTypesIsActive
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetActiveFeeTypesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in FeeType");
            });
        }

        public async Task<RepoResponse<List<GetFlatPaymentsForFeeTypesResponseDto>>> GetFlatPaymentsForFeeTypesAsync(int feeTypesId)
        {
            return await ExecuteWithExceptionHandling("GetFlatPaymentsForFeeTypes", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.FeeType.Query.GetFlatPaymentsForFeeTypes);
                var parameters = new
                {
                    PRM_FEE_TYPES_ID = feeTypesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetFlatPaymentsForFeeTypesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in FeeType");
            });
        }

        public async Task<RepoResponse<GetFlatPaymentsForFeeTypesResponseDto>> GetFlatPaymentsForFeeTypesDetailsAsync(int feeTypesId, int flatPaymentsId)
        {
            return await ExecuteWithExceptionHandling("GetFlatPaymentsForFeeTypesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.FeeType.Query.GetFlatPaymentsForFeeTypesDetails);
                var parameters = new
                {
                    PRM_FLAT_PAYMENTS_ID = flatPaymentsId,
                    PRM_FEE_TYPES_ID = feeTypesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetFlatPaymentsForFeeTypesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in FeeType");
            });
        }
    }
}