SELECT CM.[ID], CM.[NAME], CM.[DESCRIPTION] 
FROM [COMMISSION_MODELS] CM 
WHERE CM.[IsDeleted] = 0 
	AND CM.[IS_ACTIVE] = @PRM_COMMISSION_MODEL_IS_ACTIVE 
ORDER BY CM.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 