SELECT [ID], [NAME], [EMAIL_ADDRESS], [API_URL], [USERNAME], [PASSWORD], [IS_ACTIVE], [PRIORITY], [DAILY_LIMIT] 
FROM [SENDERS] 
WHERE [IsDeleted] = 0 
	AND [IS_ACTIVE] = @PRM_SENDERS_IS_ACTIVE 
ORDER BY [ID] 