SELECT TOP 1 [ID], [NAME], [EMAIL_ADDRESS], [API_URL], [USERNAME], [PASSWORD], [IS_ACTIVE], [PRIORITY], [DAILY_LIMIT] 
FROM [SENDERS] 
WHERE [IsDeleted] = 0 
	AND [NAME] = @PRM_SENDERS_NAME 
ORDER BY [ID] 