SELECT S.[ID], S.[NAME], S.[EMAIL_ADDRESS], S.[API_URL], S.[USERNAME], S.[PASSWORD], S.[IS_ACTIVE], S.[PRIORITY], S.[DAILY_LIMIT] 
FROM [MESSAGE_LOGS] ML 
	INNER JOIN [SENDERS] S 
			ON ML.[SENDER_ID] = S.[ID] 
WHERE ML.[IsDeleted] = 0 
	AND S.[IsDeleted] = 0 
	AND S.[ID] = @PRM_SENDERS_ID 
ORDER BY S.[ID] 