SELECT ML.[ID], ML.[MESSAGE_ID], ML.[CAMPAIGN_ID], ML.[SENDER_ID], ML.[ATTEMPT_DATE], ML.[RECIPIENT], ML.[SUBJECT], ML.[BODY], ML.[TEMPLATE_NAME], ML.[STATUS], ML.[ATTEMPT_COUNT], ML.[SENT_DATE] 
FROM [MESSAGE_LOGS] ML 
	INNER JOIN [SENDERS] S 
			ON ML.[SENDER_ID] = S.[ID] 
WHERE ML.[IsDeleted] = 0 
	AND S.[IsDeleted] = 0 
	AND ML.[ID] = @PRM_MESSAGE_LOGS_ID 
	AND S.[ID] = @PRM_SENDERS_ID 
ORDER BY ML.[ID] 