SELECT OML.[ID], OML.[SENDER_ID], OML.[OTP_MESSAGE_ID], OML.[RECIPIENT], OML.[OTP_CODE], OML.[HASH_CODE], OML.[TEMPLATE_NAME], OML.[STATUS], OML.[EXPIRE_TIME_SECONDS] 
FROM [OTP_MESSAGE_LOGS] OML 
	INNER JOIN [SENDERS] S 
			ON OML.[SENDER_ID] = S.[ID] 
WHERE OML.[IsDeleted] = 0 
	AND S.[IsDeleted] = 0 
	AND OML.[ID] = @PRM_OTP_MESSAGE_LOGS_ID 
	AND S.[ID] = @PRM_SENDERS_ID 
ORDER BY OML.[ID] 