SELECT S.[ID], S.[NAME], S.[EMAIL_ADDRESS], S.[API_URL], S.[USERNAME], S.[PASSWORD], S.[IS_ACTIVE], S.[PRIORITY], S.[DAILY_LIMIT] 
FROM [OTP_MESSAGE_QUEUES] OMQ 
	INNER JOIN [SENDERS] S 
			ON OMQ.[SENDER_ID] = S.[ID] 
WHERE OMQ.[IsDeleted] = 0 
	AND S.[IsDeleted] = 0 
	AND S.[ID] = @PRM_SENDERS_ID 
ORDER BY S.[ID] 