SELECT [ID], [CAMPAIGN_ID], [RECIPIENT], [SUBJECT], [BODY], [TEMPLATE_NAME], [STATUS], [ATTEMPT_COUNT], [LAST_ATTEMPT_DATE], [SENT_DATE] 
FROM [MESSAGES] 
WHERE [IsDeleted] = 0 
	AND [CAMPAIGN_ID] = @PRM_MESSAGES_CAMPAIGN_ID 
ORDER BY [ID] 