SELECT [FEE_AMOUNT] 
FROM [APARTMENT_FEE_PLANS] 
WHERE [IsDeleted] = 0 
	AND [SITE_ID] = @PRM_APARTMENT_FEE_PLANS_SITE_ID 
	AND [APARTMENT_ID] = @PRM_APARTMENT_FEE_PLANS_APARTMENT_ID 
	AND [YEAR_ID] = @PRM_APARTMENT_FEE_PLANS_YEAR_ID 
	AND [MONTH_ID] = @PRM_APARTMENT_FEE_PLANS_MONTH_ID 
	AND [IS_ACTIVE] = @PRM_APARTMENT_FEE_PLANS_IS_ACTIVE 
ORDER BY [ID] 