SELECT [APARTMENT_ID], [YEAR_ID], [MONTH_ID], [FEE_AMOUNT] 
FROM [APARTMENT_FEE_PLANS] 
WHERE [IsDeleted] = 0 
	AND [SITE_ID] = @PRM_APARTMENT_FEE_PLANS_SITE_ID 
	AND [IS_ACTIVE] = @PRM_APARTMENT_FEE_PLANS_IS_ACTIVE 
ORDER BY [ID] 