SELECT EI.[ID], EI.[SITE_ID], EI.[APARTMENT_ID], EI.[EXPENSE_ID], EI.[INSTALLMENT_NUMBER], EI.[TOTAL_INSTALLMENTS], EI.[INSTALLMENT_AMOUNT], EI.[DUE_DATE], EI.[PAID], EI.[PAID_AT], EI.[PAYMENT_TYPE_ID], EI.[CREATED_DATE] 
FROM [EXPENSE_INSTALLMENTS] EI 
	INNER JOIN [COMMON_EXPENSES] CE 
			ON EI.[EXPENSE_ID] = CE.[ID] 
WHERE EI.[IsDeleted] = 0 
	AND CE.[IsDeleted] = 0 
	AND EI.[ID] = @PRM_EXPENSE_INSTALLMENTS_ID 
	AND CE.[ID] = @PRM_COMMON_EXPENSES_ID 
ORDER BY EI.[ID] 