SELECT [ID], [NAME], [EXPENSE_TYPE_ID], [EXPENSE_AMOUNT], [DESCRIPTION], [PAID], [PAID_AT], [PAYMENT_TYPE_ID] 
FROM [COMMON_EXPENSES] 
WHERE [IsDeleted] = 0 
	AND [SITE_ID] = @PRM_COMMON_EXPENSES_SITE_ID 
	AND [APARTMENT_ID] = @PRM_COMMON_EXPENSES_APARTMENT_ID 
	AND [YEAR_ID] = @PRM_COMMON_EXPENSES_YEAR_ID 
	AND [MONTH_ID] = @PRM_COMMON_EXPENSES_MONTH_ID 
ORDER BY [ID] 