SELECT [EXPENSE_TYPE_ID], SUM([EXPENSE_AMOUNT]) AS TOTAL_AMOUNT 
FROM [COMMON_EXPENSES] 
WHERE [IsDeleted] = 0 
	AND [SITE_ID] = @PRM_COMMON_EXPENSES_SITE_ID 
	AND [APARTMENT_ID] = @PRM_COMMON_EXPENSES_APARTMENT_ID 
	AND [YEAR_ID] = @PRM_COMMON_EXPENSES_YEAR_ID 
GROUP BY [EXPENSE_TYPE_ID] 
ORDER BY [EXPENSE_TYPE_ID] 