SELECT [ID], [APARTMENT_ID], [NAME], [EXPENSE_TYPE_ID], [EXPENSE_AMOUNT], [DESCRIPTION], [PAID], [PAYMENT_TYPE_ID] 
FROM [COMMON_EXPENSES] 
WHERE [IsDeleted] = 0 
	AND [SITE_ID] = @PRM_COMMON_EXPENSES_SITE_ID 
ORDER BY [ID] 