SELECT FEI.[ID], FEI.[SITE_ID], FEI.[APARTMENT_ID], FEI.[FLAT_ID], FEI.[EXPENSE_ID], FEI.[EXPENSE_INSTALLMENT_ID], FEI.[FLAT_INSTALLMENT_NUMBER], FEI.[TOTAL_FLAT_INSTALLMENTS], FEI.[FLAT_INSTALLMENT_AMOUNT], FEI.[DUE_DATE], FEI.[PAID], FEI.[PAID_AT], FEI.[PAYMENT_TYPE_ID], FEI.[CREATED_DATE] 
FROM [FLAT_EXPENSE_INSTALLMENTS] FEI 
	INNER JOIN [COMMON_EXPENSES] CE 
			ON FEI.[EXPENSE_ID] = CE.[ID] 
WHERE FEI.[IsDeleted] = 0 
	AND CE.[IsDeleted] = 0 
	AND CE.[ID] = @PRM_COMMON_EXPENSES_ID 
ORDER BY FEI.[ID] 