SELECT
    [ID],
    [CUSTOMER_ID],
    [SELLER_ID],
    [ORDER_NUMBER],
    [TOTAL_AMOUNT],
    [SHIPPING_ADDRESS],
    [STATUS],
    [ORDER_DATE]
FROM [dbo].[ORDERS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;