SELECT C.[ID] AS COUPON_ID,
	C.[COUPON_CODE], C.[DISCOUNT_RATE] AS COUPON_DISCOUNT_RATE 
FROM [COUPONS] C 
	INNER JOIN [USERS] U 
			ON C.[USER_ID] = U.[ID] 
WHERE C.[IsDeleted] = 0 
	AND U.[IsDeleted] = 0 
	AND C.[USER_ID] = @PRM_COUPONS_USER_ID 
	AND C.[START_DATE] <= GETDATE() 
	AND C.[END_DATE] >= GETDATE() 
ORDER BY C.[ID] 