SELECT C.[ID], C.[COUPON_CODE], C.[CAMPAIGN_ID], C.[USER_ID], C.[DISCOUNT_RATE], C.[DISCOUNT_AMOUNT], C.[MAX_USAGE], C.[USED_COUNT], C.[START_DATE], C.[END_DATE], C.[IS_SINGLE_USE] 
FROM [USER_COUPONS] UC 
	INNER JOIN [COUPONS] C 
			ON UC.[COUPON_ID] = C.[ID] 
WHERE C.[IsDeleted] = 0 
	AND C.[ID] = @PRM_COUPONS_ID 
ORDER BY C.[ID] 