SELECT UC.[USER_ID], UC.[COUPON_ID], UC.[IS_USED], UC.[USED_AT] 
FROM [USER_COUPONS] UC 
	INNER JOIN [COUPONS] C 
			ON UC.[COUPON_ID] = C.[ID] 
WHERE C.[IsDeleted] = 0 
	AND UC.[USER_ID] = @PRM_USER_COUPONS_USER_ID 
	AND C.[ID] = @PRM_COUPONS_ID 
ORDER BY UC.[USER_ID], UC.[COUPON_ID] 