SELECT [ID], [COUPON_CODE], [DISCOUNT_RATE], [DISCOUNT_AMOUNT] 
FROM [COUPONS] 
WHERE [IsDeleted] = 0 
	AND [COUPON_CODE] = @PRM_COUPONS_COUPON_CODE 
	AND [START_DATE] <= GETDATE() 
	AND [END_DATE] >= GETDATE() 
ORDER BY [ID] 