SELECT CI.[ID] AS CART_ITEM_ID,
	CI.[QUANTITY] AS CART_ITEM_QUANTITY,
	CI.[UNIT_PRICE] AS CART_ITEM_UNIT_PRICE,
	P.[TITLE] AS PRODUCT_TITLE 
FROM [CART_ITEMS] CI 
	INNER JOIN [PRODUCTS] P 
			ON CI.[PRODUCT_ID] = P.[ID] 
WHERE CI.[IsDeleted] = 0 
	AND P.[IsDeleted] = 0 
	AND CI.[CART_ID] = @PRM_CART_ITEMS_CART_ID 
ORDER BY CI.[ID] 