SELECT O.[ID], O.[ORDER_NUMBER], O.[TOTAL_AMOUNT], O.[ORDER_DATE] 
FROM [ORDERS] O 
WHERE O.[IsDeleted] = 0 
	AND O.[SELLER_ID] = @PRM_ORDER_SELLER_ID 
	AND O.[STATUS] = 'COMPLETED' 
ORDER BY O.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 