SELECT O.[ID], O.[ORDER_NUMBER], O.[STATUS], O.[TOTAL_AMOUNT], O.[ORDER_DATE] 
FROM [ORDERS] O 
WHERE O.[IsDeleted] = 0 
	AND O.[SELLER_ID] = @PRM_ORDER_SELLER_ID 
ORDER BY O.[ORDER_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 