SELECT O.[ID], O.[ORDER_NUMBER], O.[STATUS], O.[TOTAL_AMOUNT], O.[ORDER_DATE] 
FROM [ORDERS] O 
WHERE O.[IsDeleted] = 0 
	AND O.[ORDER_DATE] BETWEEN @PRM_ORDER_ORDER_DATE_From 
	AND @PRM_ORDER_ORDER_DATE_To 
ORDER BY O.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 