SELECT [ID], [RECIPIENT], [OTP_CODE], [HASH_CODE], [TEMPLATE_NAME], [STATUS], [EXPIRE_TIME_SECONDS], [ATTEMPT_COUNT] 
FROM [OTP_MESSAGES] 
WHERE [IsDeleted] = 0 
	AND [RECIPIENT] = @PRM_OTP_MESSAGES_RECIPIENT 
ORDER BY [ID] 