SELECT C.[ID], C.[NAME], C.[SLUG], C.[PARENT_CATEGORY_ID] 
FROM [CATEGORIES] C 
WHERE C.[IsDeleted] = 0 
	AND C.[IS_ACTIVE] = 1 
ORDER BY C.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 