SELECT [ID], [NAME], [DESCRIPTION], [START_DATE], [END_DATE], [IS_ACTIVE], [PRIORITY], [TEMPLATE_NAME] 
FROM [CAMPAIGNS] 
WHERE [IsDeleted] = 0 
	AND [IS_ACTIVE] = @PRM_CAMPAIGNS_IS_ACTIVE 
ORDER BY [ID] 