//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.TaskManagerModule.Domain.Entities;
using QuickCode.Demo.TaskManagerModule.Application.Dtos.Project;
using System.Threading.Tasks;
using QuickCode.Demo.TaskManagerModule.Domain.Enums;

namespace QuickCode.Demo.TaskManagerModule.Application.Interfaces.Repositories
{
    public partial interface IProjectRepository : IBaseRepository<ProjectDto>
    {
        Task<RepoResponse<ProjectDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetProjectsByUserIdResponseDto>>> GetProjectsByUserIdAsync(int projectsUserId);
        Task<RepoResponse<List<GetProjectsDueSoonResponseDto>>> GetProjectsDueSoonAsync();
        Task<RepoResponse<List<SearchProjectsResponseDto>>> SearchProjectsAsync(string projectsName);
        Task<RepoResponse<int>> UpdateProjectEndDateAsync(int projectsId, UpdateProjectEndDateRequestDto updateRequest);
        Task<RepoResponse<int>> DeleteProjectAsync(int projectsId);
    }
}