//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.TaskManagerModule.Domain.Entities;
using QuickCode.Demo.TaskManagerModule.Application.Dtos.Task;
using System.Threading.Tasks;
using QuickCode.Demo.TaskManagerModule.Domain.Enums;

namespace QuickCode.Demo.TaskManagerModule.Application.Interfaces.Repositories
{
    public partial interface ITaskRepository : IBaseRepository<TaskDto>
    {
        Task<RepoResponse<TaskDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetTasksByUserIdResponseDto>>> GetTasksByUserIdAsync(int tasksUserId);
        Task<RepoResponse<List<GetTasksByStatusResponseDto>>> GetTasksByStatusAsync(TaskStatus tasksStatus);
        Task<RepoResponse<List<GetTasksByPriorityResponseDto>>> GetTasksByPriorityAsync(short tasksPriority);
        Task<RepoResponse<List<GetTasksDueTodayResponseDto>>> GetTasksDueTodayAsync(DateTime tasksDueDate);
        Task<RepoResponse<List<SearchTasksResponseDto>>> SearchTasksAsync(string tasksTitle);
        Task<RepoResponse<List<GetTaskCommentsForTasksResponseDto>>> GetTaskCommentsForTasksAsync(int tasksId);
        Task<RepoResponse<GetTaskCommentsForTasksResponseDto>> GetTaskCommentsForTasksDetailsAsync(int tasksId, int taskCommentsId);
        Task<RepoResponse<int>> UpdateTaskStatusAsync(int tasksId, UpdateTaskStatusRequestDto updateRequest);
        Task<RepoResponse<int>> UpdateTaskPriorityAsync(int tasksId, UpdateTaskPriorityRequestDto updateRequest);
        Task<RepoResponse<int>> DeleteTaskAsync(int tasksId);
    }
}