SELECT SD.[ID], SD.[DOCUMENT_TYPE], SD.[STATUS], SD.[UPLOADED_DATE] 
FROM [SELLER_DOCUMENTS] SD 
WHERE SD.[IsDeleted] = 0 
	AND SD.[SELLER_ID] = @PRM_SELLER_DOCUMENT_SELLER_ID 
ORDER BY SD.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 