SELECT SD.[ID], SD.[SELLER_ID], SD.[DOCUMENT_TYPE], SD.[UPLOADED_DATE] 
FROM [SELLER_DOCUMENTS] SD 
WHERE SD.[IsDeleted] = 0 
	AND SD.[STATUS] = @PRM_SELLER_DOCUMENT_STATUS 
ORDER BY SD.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 