// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.OrderManagementModule.Domain.Entities;
using QuickCode.Demo.OrderManagementModule.Application.Interfaces.Repositories;
using QuickCode.Demo.OrderManagementModule.Application.Dtos.OrderItem;
using QuickCode.Demo.OrderManagementModule.Domain.Enums;

namespace QuickCode.Demo.OrderManagementModule.Application.Features.OrderItem
{
    public class ListOrderItemQuery : IRequest<Response<List<OrderItemDto>>>
    {
        public int? PageNumber { get; set; }
        public int? PageSize { get; set; }

        public ListOrderItemQuery(int? pageNumber, int? pageSize)
        {
            this.PageNumber = pageNumber;
            this.PageSize = pageSize;
        }

        public class ListOrderItemHandler : IRequestHandler<ListOrderItemQuery, Response<List<OrderItemDto>>>
        {
            private readonly ILogger<ListOrderItemHandler> _logger;
            private readonly IOrderItemRepository _repository;
            public ListOrderItemHandler(ILogger<ListOrderItemHandler> logger, IOrderItemRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<OrderItemDto>>> Handle(ListOrderItemQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.ListAsync(request.PageNumber, request.PageSize);
                return returnValue.ToResponse();
            }
        }
    }
}