//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.ApartmentManageModule.Domain.Entities;
using QuickCode.Demo.ApartmentManageModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Common;
using QuickCode.Demo.Common.Extensions;
using QuickCode.Demo.Common.Helpers;
using QuickCode.Demo.ApartmentManageModule.Persistence.Contexts;
using QuickCode.Demo.ApartmentManageModule.Application.Dtos;
using QuickCode.Demo.ApartmentManageModule.Application.Mappings;
using QuickCode.Demo.ApartmentManageModule.Application.Sql;
using QuickCode.Demo.ApartmentManageModule.Domain.Enums;

namespace QuickCode.Demo.ApartmentManageModule.Persistence.Repositories
{
    public partial class FlatContactsRepository : BaseRepository, IFlatContactsRepository
    {
        public async Task<RepoResponse<List<FlatContactsGetFlatOwnersResponseDto>>> FlatContactsGetFlatOwnersAsync(int flatContactsFlatId, RelationshipType flatContactsRelationshipType, bool flatContactsIsActive)
        {
            return await ExecuteWithExceptionHandling("FlatContactsGetFlatOwners", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.FlatContacts.Query.GetFlatOwners);
                var parameters = new
                {
                    PRM_FLAT_CONTACTS_FLAT_ID = flatContactsFlatId,
                    PRM_FLAT_CONTACTS_RELATIONSHIP_TYPE = flatContactsRelationshipType,
                    PRM_FLAT_CONTACTS_IS_ACTIVE = flatContactsIsActive
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<FlatContactsGetFlatOwnersResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in FlatContacts");
            });
        }

        public async Task<RepoResponse<List<FlatContactsGetFlatTenantsResponseDto>>> FlatContactsGetFlatTenantsAsync(int flatContactsFlatId, RelationshipType flatContactsRelationshipType, bool flatContactsIsActive)
        {
            return await ExecuteWithExceptionHandling("FlatContactsGetFlatTenants", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.FlatContacts.Query.GetFlatTenants);
                var parameters = new
                {
                    PRM_FLAT_CONTACTS_FLAT_ID = flatContactsFlatId,
                    PRM_FLAT_CONTACTS_RELATIONSHIP_TYPE = flatContactsRelationshipType,
                    PRM_FLAT_CONTACTS_IS_ACTIVE = flatContactsIsActive
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<FlatContactsGetFlatTenantsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in FlatContacts");
            });
        }

        public async Task<RepoResponse<List<FlatContactsGetContactFlatsResponseDto>>> FlatContactsGetContactFlatsAsync(int flatContactsContactId, bool flatContactsIsActive)
        {
            return await ExecuteWithExceptionHandling("FlatContactsGetContactFlats", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.FlatContacts.Query.GetContactFlats);
                var parameters = new
                {
                    PRM_FLAT_CONTACTS_CONTACT_ID = flatContactsContactId,
                    PRM_FLAT_CONTACTS_IS_ACTIVE = flatContactsIsActive
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<FlatContactsGetContactFlatsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in FlatContacts");
            });
        }

        public async Task<RepoResponse<List<FlatContactsGetContactOwnedFlatsResponseDto>>> FlatContactsGetContactOwnedFlatsAsync(int flatContactsContactId, RelationshipType flatContactsRelationshipType, bool flatContactsIsActive)
        {
            return await ExecuteWithExceptionHandling("FlatContactsGetContactOwnedFlats", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.FlatContacts.Query.GetContactOwnedFlats);
                var parameters = new
                {
                    PRM_FLAT_CONTACTS_CONTACT_ID = flatContactsContactId,
                    PRM_FLAT_CONTACTS_RELATIONSHIP_TYPE = flatContactsRelationshipType,
                    PRM_FLAT_CONTACTS_IS_ACTIVE = flatContactsIsActive
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<FlatContactsGetContactOwnedFlatsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in FlatContacts");
            });
        }

        public async Task<RepoResponse<List<FlatContactsGetContactRentedFlatsResponseDto>>> FlatContactsGetContactRentedFlatsAsync(int flatContactsContactId, RelationshipType flatContactsRelationshipType, bool flatContactsIsActive)
        {
            return await ExecuteWithExceptionHandling("FlatContactsGetContactRentedFlats", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.FlatContacts.Query.GetContactRentedFlats);
                var parameters = new
                {
                    PRM_FLAT_CONTACTS_CONTACT_ID = flatContactsContactId,
                    PRM_FLAT_CONTACTS_RELATIONSHIP_TYPE = flatContactsRelationshipType,
                    PRM_FLAT_CONTACTS_IS_ACTIVE = flatContactsIsActive
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<FlatContactsGetContactRentedFlatsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in FlatContacts");
            });
        }

        public async Task<RepoResponse<bool>> FlatContactsCheckFlatHasOwnerAsync(int flatContactsFlatId, RelationshipType flatContactsRelationshipType, bool flatContactsIsActive)
        {
            return await ExecuteWithExceptionHandling("FlatContactsCheckFlatHasOwner", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.FlatContacts.Query.CheckFlatHasOwner);
                var parameters = new
                {
                    PRM_FLAT_CONTACTS_FLAT_ID = flatContactsFlatId,
                    PRM_FLAT_CONTACTS_RELATIONSHIP_TYPE = flatContactsRelationshipType,
                    PRM_FLAT_CONTACTS_IS_ACTIVE = flatContactsIsActive
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var exists = await connection.ExecuteScalarAsync<bool>(sql, parameters);
                return BuildBoolResponse(exists, $"Not found in FlatContacts");
            });
        }

        public async Task<RepoResponse<bool>> FlatContactsCheckFlatHasTenantAsync(int flatContactsFlatId, RelationshipType flatContactsRelationshipType, bool flatContactsIsActive)
        {
            return await ExecuteWithExceptionHandling("FlatContactsCheckFlatHasTenant", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.FlatContacts.Query.CheckFlatHasTenant);
                var parameters = new
                {
                    PRM_FLAT_CONTACTS_FLAT_ID = flatContactsFlatId,
                    PRM_FLAT_CONTACTS_RELATIONSHIP_TYPE = flatContactsRelationshipType,
                    PRM_FLAT_CONTACTS_IS_ACTIVE = flatContactsIsActive
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var exists = await connection.ExecuteScalarAsync<bool>(sql, parameters);
                return BuildBoolResponse(exists, $"Not found in FlatContacts");
            });
        }

        public async Task<RepoResponse<long>> FlatContactsGetFlatContactsCountAsync(int flatContactsFlatId, bool flatContactsIsActive)
        {
            return await ExecuteWithExceptionHandling("FlatContactsGetFlatContactsCount", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.FlatContacts.Query.GetFlatContactsCount);
                var parameters = new
                {
                    PRM_FLAT_CONTACTS_FLAT_ID = flatContactsFlatId,
                    PRM_FLAT_CONTACTS_IS_ACTIVE = flatContactsIsActive
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var result = await connection.ExecuteScalarAsync<long>(sql, parameters);
                return new RepoResponse<long>(result, "Success");
            });
        }
    }
}