SELECT CI.[ID], CI.[CART_ID], CI.[PRODUCT_ID], CI.[QUANTITY], CI.[UNIT_PRICE] 
FROM [CART_ITEMS] CI 
	INNER JOIN [CARTS] C 
			ON CI.[CART_ID] = C.[ID] 
WHERE CI.[IsDeleted] = 0 
	AND C.[IsDeleted] = 0 
	AND CI.[ID] = @PRM_CART_ITEMS_ID 
	AND C.[ID] = @PRM_CARTS_ID 
ORDER BY CI.[ID] 