SELECT [REQUEST_MODULE], COUNT(*) AS TOTAL_REQUESTS 
FROM [AUDIT_LOGS] AL 
WHERE AL.[ENTITY_NAME] = 'HttpRequest' 
	AND AL.[TIMESTAMP] > DATEADD(DAY, -7,
	GETDATE()) 
GROUP BY AL.[REQUEST_MODULE] 
ORDER BY AL.[REQUEST_MODULE] 