SELECT AFP.[ID], AFP.[SITE_ID], AFP.[APARTMENT_ID], AFP.[YEAR_ID], AFP.[MONTH_ID], AFP.[FEE_AMOUNT], AFP.[IS_ACTIVE] 
FROM [APARTMENT_FEE_PLANS] AFP 
	INNER JOIN [PAYMENT_MONTHS] PM 
			ON AFP.[MONTH_ID] = PM.[ID] 
WHERE AFP.[IsDeleted] = 0 
	AND PM.[ID] = @PRM_PAYMENT_MONTHS_ID 
ORDER BY AFP.[ID] 