SELECT PG.[ID] AS PRODUCT_GROUP_ID,
	PG.[NAME] AS PRODUCT_GROUP_NAME,
	PT.[NAME] AS PRODUCT_TYPE_NAME 
FROM [PRODUCT_GROUPS] PG 
	INNER JOIN [PRODUCT_TYPES] PT 
			ON PG.[PRODUCT_TYPE_ID] = PT.[ID] 
	INNER JOIN [PRODUCTS] P 
			ON P.[PRODUCT_GROUP_ID] = PG.[ID] 
WHERE PG.[IsDeleted] = 0 
	AND PT.[IsDeleted] = 0 
	AND P.[IsDeleted] = 0 
	AND PG.[PRODUCT_TYPE_ID] = @PRM_PRODUCT_GROUPS_PRODUCT_TYPE_ID 
	AND P.[STOCK_QUANTITY] > 0 
ORDER BY PG.[ID] 