SELECT PG.[ID], PG.[NAME], PG.[TITLE], PG.[IMAGE_URL], PG.[DESCRIPTION], PG.[CODE], PG.[PRODUCT_TYPE_ID] 
FROM [PRODUCTS] P 
	INNER JOIN [PRODUCT_GROUPS] PG 
			ON P.[PRODUCT_GROUP_ID] = PG.[ID] 
WHERE P.[IsDeleted] = 0 
	AND PG.[IsDeleted] = 0 
	AND PG.[ID] = @PRM_PRODUCT_GROUPS_ID 
ORDER BY PG.[ID] 