SELECT P.[ID], P.[PRODUCT_GROUP_ID], P.[MODEL], P.[TITLE], P.[DETAILS], P.[DESCRIPTION], P.[OPTIONS], P.[PRICE], P.[CURRENCY], P.[STOCK_QUANTITY] 
FROM [PRODUCTS] P 
	INNER JOIN [PRODUCT_GROUPS] PG 
			ON P.[PRODUCT_GROUP_ID] = PG.[ID] 
WHERE P.[IsDeleted] = 0 
	AND PG.[IsDeleted] = 0 
	AND P.[ID] = @PRM_PRODUCTS_ID 
	AND PG.[ID] = @PRM_PRODUCT_GROUPS_ID 
ORDER BY P.[ID] 