//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.FinanceSettlementModule.Domain.Entities;
using QuickCode.Demo.FinanceSettlementModule.Application.Dtos.CommissionEntry;
using System.Threading.Tasks;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Application.Interfaces.Repositories
{
    public partial interface ICommissionEntryRepository : IBaseRepository<CommissionEntryDto>
    {
        Task<RepoResponse<CommissionEntryDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByOrderIdResponseDto>>> GetByOrderIdAsync(int commissionEntryOrderId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetCommissionsBySellerForPeriodResponseDto>>> GetCommissionsBySellerForPeriodAsync(int commissionEntriesSellerId, int? pageNumber = null, int? pageSize = null);
    }
}