//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Demo.Portal.Models;
using QuickCode.Demo.Portal.Models.UserManagerModule;
using QuickCode.Demo.Portal.Helpers;
using Microsoft.AspNetCore.Mvc;
using UserManagerModuleContracts = QuickCode.Demo.Common.Nswag.Clients.UserManagerModuleApi.Contracts;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using QuickCode.Demo.Portal.Helpers.Authorization;
using Microsoft.AspNetCore.Http;
using System.Threading;
using System.Threading.Tasks;
using AutoRest.Core.Utilities.Collections;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace QuickCode.Demo.Portal.Controllers.UserManagerModule
{
    [Permission("UserManagerModuleApiPermissionGroups")]
    [Area("UserManagerModule")]
    [Route("UserManagerModuleApiPermissionGroups")]
    public partial class ApiPermissionGroupsController : BaseController
    {
        private readonly UserManagerModuleContracts.IApiPermissionGroupsClient pageClient;
        private readonly UserManagerModuleContracts.IPermissionGroupsClient pagePermissionGroupsClient;
        private readonly UserManagerModuleContracts.IApiMethodDefinitionsClient pageApiMethodDefinitionsClient;
        public ApiPermissionGroupsController(UserManagerModuleContracts.IApiPermissionGroupsClient pageClient, UserManagerModuleContracts.IPermissionGroupsClient pagePermissionGroupsClient, UserManagerModuleContracts.IApiMethodDefinitionsClient pageApiMethodDefinitionsClient, UserManagerModuleContracts.ITableComboboxSettingsClient tableComboboxSettingsClient, IHttpContextAccessor httpContextAccessor, IMemoryCache cache) : base(tableComboboxSettingsClient, httpContextAccessor, cache)
        {
            this.pageClient = pageClient;
            this.pagePermissionGroupsClient = pagePermissionGroupsClient;
            this.pageApiMethodDefinitionsClient = pageApiMethodDefinitionsClient;
        }

        [ResponseCache(VaryByQueryKeys = new[] { "ic" }, Duration = 30)]
        public async Task<IActionResult> GetImage(string ic)
        {
            return await GetImageResult(pageClient, ic);
        }

        [Route("List")]
        public async Task<IActionResult> List()
        {
            var model = await PrepareModel();
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("List")]
        [HttpPost]
        public async Task<IActionResult> List(ApiPermissionGroupsData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("Insert")]
        [HttpPost]
        public async Task<IActionResult> Insert(ApiPermissionGroupsData model)
        {
            ModelBinder(ref model);
            var result = await pageClient.ApiPermissionGroupsInsertAsync(model.SelectedItem);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Update")]
        [HttpPost]
        public async Task<IActionResult> Update(ApiPermissionGroupsData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.ApiPermissionGroupsUpdateAsync(request.Id, request);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Delete")]
        [HttpPost]
        public async Task<IActionResult> Delete(ApiPermissionGroupsData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.ApiPermissionGroupsDeleteAsync(request.Id);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("InsertItem")]
        public IActionResult InsertItem(ApiPermissionGroupsData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            SetModelBinder(ref model);
            model.SelectedItem = new();
            return PartialView("Insert", model);
        }

        [Route("DetailItem")]
        public async Task<IActionResult> DetailItem(ApiPermissionGroupsData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Detail", model);
        }

        [Route("UpdateItem")]
        [HttpPost]
        public async Task<IActionResult> UpdateItem(ApiPermissionGroupsData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Update", model);
        }

        [Route("DeleteItem")]
        [HttpPost]
        public async Task<IActionResult> DeleteItem(ApiPermissionGroupsData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Delete", model);
        }

        private async Task<ApiPermissionGroupsData> PrepareModel()
        {
            var model = GetModel<ApiPermissionGroupsData>();
            model.CurrentPage = 1;
            return await PrepareModel(model);
        }

        private async Task<ApiPermissionGroupsData> PrepareModel(ApiPermissionGroupsData model)
        {
            if (model.List == null)
            {
                model.PageSize = PageSize;
                model.NumberOfRecord = await pageClient.ApiPermissionGroupsCountAsync();
                model.TotalPage = (model.NumberOfRecord + PageSize - 1) / PageSize;
                model.List = (await pageClient.ApiPermissionGroupsListAsync(model.CurrentPage, PageSize)).ToList();
            }

            return model;
        }

        private async Task<Dictionary<string, Dictionary<string, string>>> FillPageComboBoxes(Dictionary<string, Dictionary<string, string>> comboBoxList)
        {
            comboBoxList.Clear();
            comboBoxList.AddRange(await FillComboBoxAsync("PermissionGroups", () => pagePermissionGroupsClient.PermissionGroupsListAsync()));
            comboBoxList.AddRange(await FillComboBoxAsync("ApiMethodDefinitions", () => pageApiMethodDefinitionsClient.ApiMethodDefinitionsListAsync()));
            return comboBoxList;
        }
    }
}