SELECT [ID], [MESSAGE_ID], [CAMPAIGN_ID], [SENDER_ID], [RECIPIENT], [SUBJECT], [BODY], [PRIORITY], [STATUS], [PROCESS_DATE] 
FROM [MESSAGE_QUEUES] 
WHERE [IsDeleted] = 0 
	AND [STATUS] = @PRM_MESSAGE_QUEUES_STATUS 
ORDER BY [ID] 