SELECT F.[ID], F.[APARTMENT_ID], F.[SITE_ID], F.[FLAT_NUMBER], F.[FLOOR], F.[SQUARE_METERS], F.[ROOM_COUNT], F.[IS_ACTIVE], F.[CREATED_DATE] 
FROM [FLAT_CONTACTS] FC 
	INNER JOIN [FLATS] F 
			ON FC.[FLAT_ID] = F.[ID] 
WHERE FC.[IsDeleted] = 0 
	AND F.[IsDeleted] = 0 
	AND F.[ID] = @PRM_FLATS_ID 
ORDER BY F.[ID] 