SELECT F.[ID], F.[APARTMENT_ID], F.[SITE_ID], F.[FLAT_NUMBER], F.[FLOOR], F.[SQUARE_METERS], F.[ROOM_COUNT], F.[IS_ACTIVE], F.[CREATED_DATE] 
FROM [FLAT_EXPENSE_INSTALLMENTS] FEI 
	INNER JOIN [FLATS] F 
			ON FEI.[FLAT_ID] = F.[ID] 
WHERE FEI.[IsDeleted] = 0 
	AND F.[IsDeleted] = 0 
	AND F.[ID] = @PRM_FLATS_ID 
ORDER BY FEI.[ID] 