SELECT FC.[ID], FC.[FLAT_ID], FC.[CONTACT_ID], FC.[RELATIONSHIP_TYPE], FC.[START_DATE], FC.[END_DATE], FC.[IS_ACTIVE], FC.[CREATED_DATE] 
FROM [FLAT_CONTACTS] FC 
	INNER JOIN [FLATS] F 
			ON FC.[FLAT_ID] = F.[ID] 
WHERE FC.[IsDeleted] = 0 
	AND F.[IsDeleted] = 0 
	AND FC.[ID] = @PRM_FLAT_CONTACTS_ID 
	AND F.[ID] = @PRM_FLATS_ID 
ORDER BY FC.[ID] 