SELECT USA.[ID], USA.[USER_ID], USA.[SITE_ID], USA.[FLAT_ID], USA.[ACCESS_TYPE], USA.[IS_ACTIVE], USA.[GRANTED_DATE], USA.[GRANTED_BY] 
FROM [USER_SITE_ACCESSES] USA 
	INNER JOIN [FLATS] F 
			ON USA.[FLAT_ID] = F.[ID] 
WHERE USA.[IsDeleted] = 0 
	AND F.[IsDeleted] = 0 
	AND USA.[ID] = @PRM_USER_SITE_ACCESSES_ID 
	AND F.[ID] = @PRM_FLATS_ID 
ORDER BY USA.[ID] 