SELECT F.[ID], F.[APARTMENT_ID], F.[SITE_ID], F.[FLAT_NUMBER], F.[FLOOR], F.[SQUARE_METERS], F.[ROOM_COUNT], F.[IS_ACTIVE], F.[CREATED_DATE] 
FROM [USER_SITE_ACCESSES] USA 
	INNER JOIN [FLATS] F 
			ON USA.[FLAT_ID] = F.[ID] 
WHERE USA.[IsDeleted] = 0 
	AND F.[IsDeleted] = 0 
	AND F.[ID] = @PRM_FLATS_ID 
ORDER BY USA.[ID] 