SELECT PM.[ID], PM.[NAME] 
FROM [COMMON_EXPENSES] CE 
	INNER JOIN [PAYMENT_MONTHS] PM 
			ON CE.[MONTH_ID] = PM.[ID] 
WHERE CE.[IsDeleted] = 0 
	AND PM.[ID] = @PRM_PAYMENT_MONTHS_ID 
ORDER BY CE.[ID] 