SELECT [ID], [SENDER_ID], [OTP_MESSAGE_ID], [RECIPIENT], [OTP_CODE], [HASH_CODE], [PRIORITY], [STATUS], [PROCESS_DATE] 
FROM [OTP_MESSAGE_QUEUES] 
WHERE [IsDeleted] = 0 
	AND [STATUS] = @PRM_OTP_MESSAGE_QUEUES_STATUS 
ORDER BY [ID] 