//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.ApartmentManageModule.Domain.Entities;
using QuickCode.Demo.ApartmentManageModule.Application.Dtos.FeeType;
using System.Threading.Tasks;
using QuickCode.Demo.ApartmentManageModule.Domain.Enums;

namespace QuickCode.Demo.ApartmentManageModule.Application.Interfaces.Repositories
{
    public partial interface IFeeTypeRepository : IBaseRepository<FeeTypeDto>
    {
        Task<RepoResponse<FeeTypeDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetActiveFeeTypesResponseDto>>> GetActiveFeeTypesAsync(bool feeTypesIsActive);
        Task<RepoResponse<List<GetFlatPaymentsForFeeTypesResponseDto>>> GetFlatPaymentsForFeeTypesAsync(int feeTypesId);
        Task<RepoResponse<GetFlatPaymentsForFeeTypesResponseDto>> GetFlatPaymentsForFeeTypesDetailsAsync(int feeTypesId, int flatPaymentsId);
    }
}