//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.ApartmentManageModule.Domain.Entities;
using QuickCode.Demo.ApartmentManageModule.Application.Dtos;
using System.Threading.Tasks;
using QuickCode.Demo.ApartmentManageModule.Domain.Enums;

namespace QuickCode.Demo.ApartmentManageModule.Application.Interfaces.Repositories
{
    public partial interface IPaymentYearsRepository : IBaseRepository<PaymentYearsDto>
    {
        Task<RepoResponse<PaymentYearsDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<PaymentYearsGetAllYearsResponseDto>>> PaymentYearsGetAllYearsAsync();
        Task<RepoResponse<List<PaymentYearsGetApartmentFeePlansForPaymentYearsResponseDto>>> PaymentYearsGetApartmentFeePlansForPaymentYearsAsync(int paymentYearsId);
        Task<RepoResponse<PaymentYearsGetApartmentFeePlansForPaymentYearsResponseDto>> PaymentYearsGetApartmentFeePlansForPaymentYearsDetailsAsync(int paymentYearsId, int apartmentFeePlansId);
        Task<RepoResponse<List<PaymentYearsGetFlatPaymentsForPaymentYearsResponseDto>>> PaymentYearsGetFlatPaymentsForPaymentYearsAsync(int paymentYearsId);
        Task<RepoResponse<PaymentYearsGetFlatPaymentsForPaymentYearsResponseDto>> PaymentYearsGetFlatPaymentsForPaymentYearsDetailsAsync(int paymentYearsId, int flatPaymentsId);
        Task<RepoResponse<List<PaymentYearsGetCommonExpensesForPaymentYearsResponseDto>>> PaymentYearsGetCommonExpensesForPaymentYearsAsync(int paymentYearsId);
        Task<RepoResponse<PaymentYearsGetCommonExpensesForPaymentYearsResponseDto>> PaymentYearsGetCommonExpensesForPaymentYearsDetailsAsync(int paymentYearsId, int commonExpensesId);
    }
}