//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by QuickCode.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuickCode.Demo.PricingEngineModule.Application.Dtos.PromotionalCampaign;

namespace QuickCode.Demo.PricingEngineModule.Persistence.Repositories;
internal static class PromotionalCampaignCrudSqlBindings
{
    public const string StoreTableName = "PROMOTIONAL_CAMPAIGNS";
    public const string ParameterNamePrefix = "PROMOTIONAL_CAMPAIGN";
    public const string IdParameterName = "PRM_PROMOTIONAL_CAMPAIGN_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Deactivate = "Deactivate";
        public const string Delete = "Delete";
        public const string GetActiveCampaigns = "GetActiveCampaigns";
        public const string GetByPk = "GetByPk";
        public const string GetCampaignsInDateRange = "GetCampaignsInDateRange";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("NAME", nameof(PromotionalCampaignDto.Name)),
        ("START_DATE", nameof(PromotionalCampaignDto.StartDate)),
        ("END_DATE", nameof(PromotionalCampaignDto.EndDate)),
        ("DISCOUNT_PERCENTAGE", nameof(PromotionalCampaignDto.DiscountPercentage)),
        ("IS_ACTIVE", nameof(PromotionalCampaignDto.IsActive))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("NAME", nameof(PromotionalCampaignDto.Name)),
        ("START_DATE", nameof(PromotionalCampaignDto.StartDate)),
        ("END_DATE", nameof(PromotionalCampaignDto.EndDate)),
        ("DISCOUNT_PERCENTAGE", nameof(PromotionalCampaignDto.DiscountPercentage)),
        ("IS_ACTIVE", nameof(PromotionalCampaignDto.IsActive)),
        ("ID", nameof(PromotionalCampaignDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(PromotionalCampaignDto.Id))
    };
}