SELECT Q.[ID], Q.[RECIPIENT], C.[NAME] AS CAMPAIGN_NAME,
	S.[NAME] AS SENDER_NAME 
FROM [MESSAGE_QUEUES] Q 
	INNER JOIN [CAMPAIGNS] C 
			ON Q.[CAMPAIGN_ID] = C.[ID] 
	INNER JOIN [SENDERS] S 
			ON Q.[SENDER_ID] = S.[ID] 
WHERE Q.[IsDeleted] = 0 
	AND C.[IsDeleted] = 0 
	AND S.[IsDeleted] = 0 
	AND Q.[STATUS] = @PRM_MESSAGE_QUEUES_STATUS 
	AND C.[IS_ACTIVE] = @PRM_CAMPAIGNS_IS_ACTIVE 
ORDER BY Q.[ID] 