SELECT
    [ID],
    [PAYOUT_ID],
    [ORDER_ID],
    [ITEM_AMOUNT],
    [COMMISSION_AMOUNT],
    [NET_AMOUNT]
FROM [dbo].[PAYOUT_LINE_ITEMS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;