UPDATE [dbo].[PAYOUT_LINE_ITEMS]
SET
    [PAYOUT_ID] = @PRM_PAYOUT_LINE_ITEM_PAYOUT_ID,
    [ORDER_ID] = @PRM_PAYOUT_LINE_ITEM_ORDER_ID,
    [ITEM_AMOUNT] = @PRM_PAYOUT_LINE_ITEM_ITEM_AMOUNT,
    [COMMISSION_AMOUNT] = @PRM_PAYOUT_LINE_ITEM_COMMISSION_AMOUNT,
    [NET_AMOUNT] = @PRM_PAYOUT_LINE_ITEM_NET_AMOUNT
WHERE
    [ID] = @PRM_PAYOUT_LINE_ITEM_ID
    AND [IsDeleted] = 0;