UPDATE [dbo].[PRODUCT_VARIANTS]
SET
    [PRODUCT_ID] = @PRM_PRODUCT_VARIANT_PRODUCT_ID,
    [SKU] = @PRM_PRODUCT_VARIANT_SKU,
    [PRICE] = @PRM_PRODUCT_VARIANT_PRICE,
    [STOCK_QUANTITY] = @PRM_PRODUCT_VARIANT_STOCK_QUANTITY,
    [IS_ACTIVE] = @PRM_PRODUCT_VARIANT_IS_ACTIVE
WHERE
    [ID] = @PRM_PRODUCT_VARIANT_ID
    AND [IsDeleted] = 0;