INSERT INTO [dbo].[PRODUCT_VARIANTS] (
    [PRODUCT_ID],
    [SKU],
    [PRICE],
    [STOCK_QUANTITY],
    [IS_ACTIVE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_PRODUCT_VARIANT_PRODUCT_ID,
    @PRM_PRODUCT_VARIANT_SKU,
    @PRM_PRODUCT_VARIANT_PRICE,
    @PRM_PRODUCT_VARIANT_STOCK_QUANTITY,
    @PRM_PRODUCT_VARIANT_IS_ACTIVE
    );