SELECT AFP.[ID], AFP.[SITE_ID], AFP.[APARTMENT_ID], AFP.[YEAR_ID], AFP.[MONTH_ID], AFP.[FEE_AMOUNT], AFP.[IS_ACTIVE] 
FROM [APARTMENT_FEE_PLANS] AFP 
	INNER JOIN [PAYMENT_YEARS] PY 
			ON AFP.[YEAR_ID] = PY.[ID] 
WHERE AFP.[IsDeleted] = 0 
	AND PY.[ID] = @PRM_PAYMENT_YEARS_ID 
ORDER BY AFP.[ID] 