SELECT CE.[ID], CE.[SITE_ID], CE.[APARTMENT_ID], CE.[NAME], CE.[EXPENSE_TYPE_ID], CE.[YEAR_ID], CE.[MONTH_ID], CE.[EXPENSE_AMOUNT], CE.[DESCRIPTION], CE.[PAID], CE.[PAID_AT], CE.[PAYMENT_TYPE_ID], CE.[CREATED_DATE] 
FROM [COMMON_EXPENSES] CE 
	INNER JOIN [PAYMENT_YEARS] PY 
			ON CE.[YEAR_ID] = PY.[ID] 
WHERE CE.[IsDeleted] = 0 
	AND PY.[ID] = @PRM_PAYMENT_YEARS_ID 
ORDER BY CE.[ID] 