SELECT [REQUEST_MODULE], [ACTION], [REQUEST_PATH], COUNT(*) AS TOTAL_REQUESTS 
FROM [AUDIT_LOGS] AL 
WHERE AL.[ENTITY_NAME] = 'HttpRequest' 
	AND AL.[TIMESTAMP] > DATEADD(DAY, -7,
	GETDATE()) 
GROUP BY AL.[REQUEST_MODULE], AL.[ACTION], AL.[REQUEST_PATH] 
ORDER BY AL.[REQUEST_MODULE], AL.[ACTION], AL.[REQUEST_PATH] 