SELECT [REQUEST_MODULE], [STATUS_CODE], COUNT(*) AS TOTAL_REQUESTS 
FROM [AUDIT_LOGS] AL 
WHERE AL.[ENTITY_NAME] = 'HttpRequest' 
	AND AL.[TIMESTAMP] > DATEADD(DAY, -7,
	GETDATE()) 
GROUP BY AL.[REQUEST_MODULE], AL.[STATUS_CODE] 
ORDER BY AL.[STATUS_CODE] ASC 