SELECT [REQUEST_MODULE], FORMAT([TIMESTAMP], 'yyyy-MM-dd HH:00:00') AS REQUEST_HOUR,
	COUNT(*) AS TOTAL_REQUESTS 
FROM [AUDIT_LOGS] AL 
WHERE AL.[ENTITY_NAME] = 'HttpRequest' 
	AND AL.[TIMESTAMP] > DATEADD(DAY, -1,
	GETDATE()) 
GROUP BY AL.[REQUEST_MODULE], FORMAT([TIMESTAMP], 'yyyy-MM-dd HH:00:00') 
ORDER BY AL.[REQUEST_MODULE], FORMAT([TIMESTAMP], 'yyyy-MM-dd HH:00:00') 