SELECT PC.[ID], PC.[NAME], PC.[DISCOUNT_PERCENTAGE] 
FROM [PROMOTIONAL_CAMPAIGNS] PC 
WHERE PC.[IsDeleted] = 0 
	AND PC.[START_DATE] BETWEEN @PRM_PROMOTIONAL_CAMPAIGN_START_DATE_From 
	AND @PRM_PROMOTIONAL_CAMPAIGN_START_DATE_To 
ORDER BY PC.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 