SELECT PC.[ID], PC.[NAME], PC.[START_DATE], PC.[END_DATE] 
FROM [PROMOTIONAL_CAMPAIGNS] PC 
WHERE PC.[IsDeleted] = 0 
	AND PC.[IS_ACTIVE] = 1 
ORDER BY PC.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 