SELECT CE.[ID], CE.[SITE_ID], CE.[APARTMENT_ID], CE.[NAME], CE.[EXPENSE_TYPE_ID], CE.[YEAR_ID], CE.[MONTH_ID], CE.[EXPENSE_AMOUNT], CE.[DESCRIPTION], CE.[PAID], CE.[PAID_AT], CE.[PAYMENT_TYPE_ID], CE.[CREATED_DATE] 
FROM [EXPENSE_INSTALLMENTS] EI 
	INNER JOIN [COMMON_EXPENSES] CE 
			ON EI.[EXPENSE_ID] = CE.[ID] 
WHERE EI.[IsDeleted] = 0 
	AND CE.[IsDeleted] = 0 
	AND CE.[ID] = @PRM_COMMON_EXPENSES_ID 
ORDER BY CE.[ID] 