SELECT C.[ID], C.[NAME], C.[DESCRIPTION], C.[START_DATE], C.[END_DATE], C.[IS_ACTIVE], C.[PRIORITY], C.[TEMPLATE_NAME] 
FROM [CAMPAIGNS] C 
	INNER JOIN [MESSAGE_TEMPLATES] MT 
			ON C.[TEMPLATE_NAME] = MT.[NAME] 
WHERE C.[IsDeleted] = 0 
	AND C.[ID] = @PRM_CAMPAIGNS_ID 
	AND MT.[NAME] = @PRM_MESSAGE_TEMPLATES_NAME 
ORDER BY C.[ID] 