SELECT RR.[ID], RR.[STATUS], RR.[REASON], RR.[REQUESTED_DATE] 
FROM [RETURN_REQUESTS] RR 
WHERE RR.[IsDeleted] = 0 
	AND RR.[ORDER_ID] = @PRM_RETURN_REQUEST_ORDER_ID 
ORDER BY RR.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 