SELECT R.[ID], R.[ORDER_ID], R.[REASON], R.[REQUESTED_DATE] 
FROM [RETURN_REQUESTS] R 
	INNER JOIN [ORDERS] O 
			ON R.[ORDER_ID] = O.[ID] 
WHERE R.[IsDeleted] = 0 
	AND O.[IsDeleted] = 0 
	AND O.[SELLER_ID] = @PRM_ORDERS_SELLER_ID 
	AND R.[STATUS] = @PRM_RETURN_REQUESTS_STATUS 
ORDER BY R.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 