SELECT O.[ID], O.[USER_ID], O.[ORDER_DATE], O.[TOTAL_AMOUNT], O.[STATUS], O.[PAYMENT_ID], O.[SHIPPING_INFO_ID] 
FROM [ORDERS] O 
	INNER JOIN [SHIPPING_INFOS] SI 
			ON O.[SHIPPING_INFO_ID] = SI.[ID] 
WHERE O.[IsDeleted] = 0 
	AND SI.[IsDeleted] = 0 
	AND O.[ID] = @PRM_ORDERS_ID 
	AND SI.[ID] = @PRM_SHIPPING_INFOS_ID 
ORDER BY O.[ID] 