SELECT SI.[ID], SI.[USER_ID], SI.[RECIPIENT_NAME], SI.[ADDRESS_LINE], SI.[CITY], SI.[DISTRICT], SI.[POSTAL_CODE], SI.[IS_DEFAULT], SI.[COUNTRY], SI.[PHONE] 
FROM [ORDERS] O 
	INNER JOIN [SHIPPING_INFOS] SI 
			ON O.[SHIPPING_INFO_ID] = SI.[ID] 
WHERE O.[IsDeleted] = 0 
	AND SI.[IsDeleted] = 0 
	AND SI.[ID] = @PRM_SHIPPING_INFOS_ID 
ORDER BY SI.[ID] 