SELECT SI.[ID] AS SHIPPING_INFO_ID,
	SI.[RECIPIENT_NAME] AS SHIPPING_RECIPIENT_NAME,
	SI.[ADDRESS_LINE] AS SHIPPING_ADDRESS_LINE 
FROM [SHIPPING_INFOS] SI 
	INNER JOIN [ORDERS] O 
			ON O.[SHIPPING_INFO_ID] = SI.[ID] 
WHERE SI.[IsDeleted] = 0 
	AND O.[IsDeleted] = 0 
	AND SI.[USER_ID] = @PRM_SHIPPING_INFOS_USER_ID 
ORDER BY SI.[ID] 