INSERT INTO [dbo].[RETURN_REQUESTS] (
    [ORDER_ID],
    [ORDER_ITEM_ID],
    [REASON],
    [STATUS],
    [REQUESTED_DATE],
    [UPDATED_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_RETURN_REQUEST_ORDER_ID,
    @PRM_RETURN_REQUEST_ORDER_ITEM_ID,
    @PRM_RETURN_REQUEST_REASON,
    @PRM_RETURN_REQUEST_STATUS,
    @PRM_RETURN_REQUEST_REQUESTED_DATE,
    @PRM_RETURN_REQUEST_UPDATED_DATE
    );