SELECT
    [ID],
    [ORDER_ID],
    [ORDER_ITEM_ID],
    [REASON],
    [STATUS],
    [REQUESTED_DATE],
    [UPDATED_DATE]
FROM [dbo].[RETURN_REQUESTS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;