UPDATE [dbo].[RETURN_REQUESTS]
SET
    [ORDER_ID] = @PRM_RETURN_REQUEST_ORDER_ID,
    [ORDER_ITEM_ID] = @PRM_RETURN_REQUEST_ORDER_ITEM_ID,
    [REASON] = @PRM_RETURN_REQUEST_REASON,
    [STATUS] = @PRM_RETURN_REQUEST_STATUS,
    [REQUESTED_DATE] = @PRM_RETURN_REQUEST_REQUESTED_DATE,
    [UPDATED_DATE] = @PRM_RETURN_REQUEST_UPDATED_DATE
WHERE
    [ID] = @PRM_RETURN_REQUEST_ID
    AND [IsDeleted] = 0;