//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.OnlineShopModule.Domain.Entities;
using QuickCode.Demo.OnlineShopModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Common;
using QuickCode.Demo.Common.Extensions;
using QuickCode.Demo.Common.Helpers;
using QuickCode.Demo.OnlineShopModule.Persistence.Contexts;
using QuickCode.Demo.OnlineShopModule.Application.Dtos.ProductType;
using QuickCode.Demo.OnlineShopModule.Application.Mappings;
using QuickCode.Demo.OnlineShopModule.Persistence.Sql;
using QuickCode.Demo.OnlineShopModule.Domain.Enums;

namespace QuickCode.Demo.OnlineShopModule.Persistence.Repositories
{
    public partial class ProductTypeRepository : BaseRepository, IProductTypeRepository
    {
        public async Task<RepoResponse<List<GetProductTypesResponseDto>>> GetProductTypesAsync(int productGroupsProductTypeId)
        {
            return await ExecuteWithExceptionHandling("GetProductTypes", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProductType.Query.GetProductTypes);
                var parameters = new
                {
                    PRM_PRODUCT_GROUPS_PRODUCT_TYPE_ID = productGroupsProductTypeId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetProductTypesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ProductType");
            });
        }

        public async Task<RepoResponse<List<GetProductGroupsForProductTypesResponseDto>>> GetProductGroupsForProductTypesAsync(int productTypesId)
        {
            return await ExecuteWithExceptionHandling("GetProductGroupsForProductTypes", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProductType.Query.GetProductGroupsForProductTypes);
                var parameters = new
                {
                    PRM_PRODUCT_TYPES_ID = productTypesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetProductGroupsForProductTypesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ProductType");
            });
        }

        public async Task<RepoResponse<GetProductGroupsForProductTypesResponseDto>> GetProductGroupsForProductTypesDetailsAsync(int productTypesId, int productGroupsId)
        {
            return await ExecuteWithExceptionHandling("GetProductGroupsForProductTypesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProductType.Query.GetProductGroupsForProductTypesDetails);
                var parameters = new
                {
                    PRM_PRODUCT_GROUPS_ID = productGroupsId,
                    PRM_PRODUCT_TYPES_ID = productTypesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetProductGroupsForProductTypesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in ProductType");
            });
        }
    }
}