SELECT
    [ID],
    [NAME],
    [IS_ACTIVE],
    [DESCRIPTION]
FROM [dbo].[COMMISSION_MODELS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;