INSERT INTO [dbo].[COMMISSION_MODELS] (
    [NAME],
    [IS_ACTIVE],
    [DESCRIPTION]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_COMMISSION_MODEL_NAME,
    @PRM_COMMISSION_MODEL_IS_ACTIVE,
    @PRM_COMMISSION_MODEL_DESCRIPTION
    );