UPDATE [dbo].[COMMISSION_MODELS]
SET
    [NAME] = @PRM_COMMISSION_MODEL_NAME,
    [IS_ACTIVE] = @PRM_COMMISSION_MODEL_IS_ACTIVE,
    [DESCRIPTION] = @PRM_COMMISSION_MODEL_DESCRIPTION
WHERE
    [ID] = @PRM_COMMISSION_MODEL_ID
    AND [IsDeleted] = 0;