SELECT AFP.[ID], AFP.[SITE_ID], AFP.[APARTMENT_ID], AFP.[YEAR_ID], AFP.[MONTH_ID], AFP.[FEE_AMOUNT], AFP.[IS_ACTIVE] 
FROM [FLAT_PAYMENTS] FP 
	INNER JOIN [APARTMENT_FEE_PLANS] AFP 
			ON FP.[FEE_PLAN_ID] = AFP.[ID] 
WHERE FP.[IsDeleted] = 0 
	AND AFP.[IsDeleted] = 0 
	AND AFP.[ID] = @PRM_APARTMENT_FEE_PLANS_ID 
ORDER BY AFP.[ID] 