SELECT [ID], [FLAT_INSTALLMENT_NUMBER], [TOTAL_FLAT_INSTALLMENTS], [FLAT_INSTALLMENT_AMOUNT], [DUE_DATE], [PAID], [PAYMENT_TYPE_ID] 
FROM [FLAT_EXPENSE_INSTALLMENTS] 
WHERE [IsDeleted] = 0 
	AND [FLAT_ID] = @PRM_FLAT_EXPENSE_INSTALLMENTS_FLAT_ID 
	AND [EXPENSE_ID] = @PRM_FLAT_EXPENSE_INSTALLMENTS_EXPENSE_ID 
ORDER BY [ID] 