SELECT F.[ID] AS FLAT_ID,
	F.[FLAT_NUMBER], P.[NAME] AS CONTACT_NAME,
	P.[PHONE] AS CONTACT_PHONE,
	FP.[RELATIONSHIP_TYPE] 
FROM [FLATS] F 
	INNER JOIN [FLAT_CONTACTS] FP 
			ON F.[FLAT_ID] = FP.[ID] 
	INNER JOIN [CONTACTS] P 
			ON FP.[CONTACT_ID] = P.[ID] 
WHERE F.[IsDeleted] = 0 
	AND FP.[IsDeleted] = 0 
	AND P.[IsDeleted] = 0 
	AND F.[ID] = @PRM_FLATS_ID 
ORDER BY F.[ID] 