SELECT MT.[NAME], MT.[CONTENT], MT.[TYPE] 
FROM [CAMPAIGNS] C 
	INNER JOIN [MESSAGE_TEMPLATES] MT 
			ON C.[TEMPLATE_NAME] = MT.[NAME] 
WHERE C.[IsDeleted] = 0 
	AND MT.[NAME] = @PRM_MESSAGE_TEMPLATES_NAME 
ORDER BY MT.[NAME] 