SELECT MT.[NAME], MT.[CONTENT], MT.[TYPE] 
FROM [MESSAGE_LOGS] ML 
	INNER JOIN [MESSAGE_TEMPLATES] MT 
			ON ML.[TEMPLATE_NAME] = MT.[NAME] 
WHERE ML.[IsDeleted] = 0 
	AND MT.[NAME] = @PRM_MESSAGE_TEMPLATES_NAME 
ORDER BY MT.[NAME] 