SELECT ML.[ID], ML.[MESSAGE_ID], ML.[CAMPAIGN_ID], ML.[SENDER_ID], ML.[ATTEMPT_DATE], ML.[RECIPIENT], ML.[SUBJECT], ML.[BODY], ML.[TEMPLATE_NAME], ML.[STATUS], ML.[ATTEMPT_COUNT], ML.[SENT_DATE] 
FROM [MESSAGE_LOGS] ML 
	INNER JOIN [MESSAGE_TEMPLATES] MT 
			ON ML.[TEMPLATE_NAME] = MT.[NAME] 
WHERE ML.[IsDeleted] = 0 
	AND ML.[ID] = @PRM_MESSAGE_LOGS_ID 
	AND MT.[NAME] = @PRM_MESSAGE_TEMPLATES_NAME 
ORDER BY ML.[ID] 