SELECT MT.[NAME], MT.[CONTENT], MT.[TYPE] 
FROM [OTP_MESSAGE_LOGS] OML 
	INNER JOIN [MESSAGE_TEMPLATES] MT 
			ON OML.[TEMPLATE_NAME] = MT.[NAME] 
WHERE OML.[IsDeleted] = 0 
	AND MT.[NAME] = @PRM_MESSAGE_TEMPLATES_NAME 
ORDER BY MT.[NAME] 