SELECT OML.[ID], OML.[SENDER_ID], OML.[OTP_MESSAGE_ID], OML.[RECIPIENT], OML.[OTP_CODE], OML.[HASH_CODE], OML.[TEMPLATE_NAME], OML.[STATUS], OML.[EXPIRE_TIME_SECONDS] 
FROM [OTP_MESSAGE_LOGS] OML 
	INNER JOIN [MESSAGE_TEMPLATES] MT 
			ON OML.[TEMPLATE_NAME] = MT.[NAME] 
WHERE OML.[IsDeleted] = 0 
	AND OML.[ID] = @PRM_OTP_MESSAGE_LOGS_ID 
	AND MT.[NAME] = @PRM_MESSAGE_TEMPLATES_NAME 
ORDER BY OML.[ID] 