SELECT FA.[ID], FA.[AMOUNT], FA.[REASON], FA.[NOTES], FA.[CREATED_DATE] 
FROM [FINANCIAL_ADJUSTMENTS] FA 
WHERE FA.[IsDeleted] = 0 
	AND FA.[SELLER_ID] = @PRM_FINANCIAL_ADJUSTMENT_SELLER_ID 
ORDER BY FA.[CREATED_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 