// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickCode.Demo.EmailManagerModule.Persistence.Contexts;

#nullable disable

namespace QuickCode.Demo.EmailManagerModule.Persistence.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20260119125543_AutoMigration_20260119_125536_211")]
    partial class AutoMigration_20260119_125536_211
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ACTION");

                    b.Property<string>("ChangeSummary")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHANGE_SUMMARY");

                    b.Property<string>("ChangedColumns")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHANGED_COLUMNS");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CORRELATION_ID");

                    b.Property<string>("EntityId")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ENTITY_ID");

                    b.Property<string>("EntityName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ENTITY_NAME");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ERROR_MESSAGE");

                    b.Property<string>("Hash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("HASH");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IP_ADDRESS");

                    b.Property<bool>("IsChanged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IS_CHANGED");

                    b.Property<bool>("IsSuccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IS_SUCCESS");

                    b.Property<string>("NewValues")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NEW_VALUES");

                    b.Property<string>("OldValues")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OLD_VALUES");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("TIMESTAMP");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("USER_AGENT");

                    b.Property<string>("UserGroup")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("USER_GROUP");

                    b.Property<string>("UserId")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("USER_ID");

                    b.Property<string>("UserName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("Id");

                    b.ToTable("AUDIT_LOGS");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.BlackList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Reason")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("REASON");

                    b.Property<string>("ReasonType")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("REASON_TYPE");

                    b.Property<string>("Recipient")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("RECIPIENT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("BLACK_LISTS");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("END_DATE");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NAME");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PRIORITY")
                        .HasDefaultValueSql("1");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("START_DATE");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TEMPLATE_NAME");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("TemplateName");

                    b.ToTable("CAMPAIGNS");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ATTEMPT_COUNT")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Body")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("BODY");

                    b.Property<int>("CampaignId")
                        .HasColumnType("int")
                        .HasColumnName("CAMPAIGN_ID");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastAttemptDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("LAST_ATTEMPT_DATE");

                    b.Property<string>("Recipient")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("RECIPIENT");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("SENT_DATE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Subject")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("SUBJECT");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TEMPLATE_NAME");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("TemplateName");

                    b.ToTable("MESSAGES");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.MessageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ATTEMPT_COUNT")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime>("AttemptDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ATTEMPT_DATE");

                    b.Property<string>("Body")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("BODY");

                    b.Property<int>("CampaignId")
                        .HasColumnType("int")
                        .HasColumnName("CAMPAIGN_ID");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int>("MessageId")
                        .HasColumnType("int")
                        .HasColumnName("MESSAGE_ID");

                    b.Property<string>("Recipient")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("RECIPIENT");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("SENDER_ID");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("SENT_DATE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Subject")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("SUBJECT");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TEMPLATE_NAME");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("MessageId");

                    b.HasIndex("SenderId");

                    b.HasIndex("TemplateName");

                    b.ToTable("MESSAGE_LOGS");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.MessageQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("BODY");

                    b.Property<int>("CampaignId")
                        .HasColumnType("int")
                        .HasColumnName("CAMPAIGN_ID");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int>("MessageId")
                        .HasColumnType("int")
                        .HasColumnName("MESSAGE_ID");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PRIORITY")
                        .HasDefaultValueSql("1");

                    b.Property<DateTime?>("ProcessDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PROCESS_DATE");

                    b.Property<string>("Recipient")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("RECIPIENT");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("SENDER_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Subject")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("SUBJECT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("MessageId");

                    b.HasIndex("SenderId");

                    b.ToTable("MESSAGE_QUEUES");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.MessageTemplate", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NAME");

                    b.Property<string>("Content")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("CONTENT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TYPE");

                    b.HasKey("Name");

                    b.ToTable("MESSAGE_TEMPLATES");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.OtpMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ATTEMPT_COUNT")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<int>("ExpireTimeSeconds")
                        .HasColumnType("int")
                        .HasColumnName("EXPIRE_TIME_SECONDS");

                    b.Property<string>("HashCode")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("HASH_CODE");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("OtpCode")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("OTP_CODE");

                    b.Property<string>("Recipient")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("RECIPIENT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("STATUS");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TEMPLATE_NAME");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("TemplateName");

                    b.ToTable("OTP_MESSAGES");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.OtpMessageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<int>("ExpireTimeSeconds")
                        .HasColumnType("int")
                        .HasColumnName("EXPIRE_TIME_SECONDS");

                    b.Property<string>("HashCode")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("HASH_CODE");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("OtpCode")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("OTP_CODE");

                    b.Property<int>("OtpMessageId")
                        .HasColumnType("int")
                        .HasColumnName("OTP_MESSAGE_ID");

                    b.Property<string>("Recipient")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("RECIPIENT");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("SENDER_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("STATUS");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TEMPLATE_NAME");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("OtpMessageId");

                    b.HasIndex("SenderId");

                    b.HasIndex("TemplateName");

                    b.ToTable("OTP_MESSAGE_LOGS");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.OtpMessageQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<string>("HashCode")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("HASH_CODE");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("OtpCode")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("OTP_CODE");

                    b.Property<int>("OtpMessageId")
                        .HasColumnType("int")
                        .HasColumnName("OTP_MESSAGE_ID");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PRIORITY")
                        .HasDefaultValueSql("1");

                    b.Property<DateTime?>("ProcessDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PROCESS_DATE");

                    b.Property<string>("Recipient")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("RECIPIENT");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("SENDER_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("OtpMessageId");

                    b.HasIndex("SenderId");

                    b.ToTable("OTP_MESSAGE_QUEUES");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.Sender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("API_URL");

                    b.Property<int>("DailyLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DAILY_LIMIT")
                        .HasDefaultValueSql("1000");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("EMAIL_ADDRESS");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NAME");

                    b.Property<string>("Password")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("PASSWORD");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PRIORITY")
                        .HasDefaultValueSql("1");

                    b.Property<string>("Username")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("SENDERS");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.Campaign", b =>
                {
                    b.HasOne("QuickCode.Demo.EmailManagerModule.Domain.Entities.MessageTemplate", "Template")
                        .WithMany("Campaigns")
                        .HasForeignKey("TemplateName")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Template");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.Message", b =>
                {
                    b.HasOne("QuickCode.Demo.EmailManagerModule.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Messages")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickCode.Demo.EmailManagerModule.Domain.Entities.MessageTemplate", "Template")
                        .WithMany("Messages")
                        .HasForeignKey("TemplateName")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Campaign");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.MessageLog", b =>
                {
                    b.HasOne("QuickCode.Demo.EmailManagerModule.Domain.Entities.Message", "Message")
                        .WithMany("MessageLogs")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickCode.Demo.EmailManagerModule.Domain.Entities.Sender", "Sender")
                        .WithMany("MessageLogs")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuickCode.Demo.EmailManagerModule.Domain.Entities.MessageTemplate", "Template")
                        .WithMany("MessageLogs")
                        .HasForeignKey("TemplateName")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Message");

                    b.Navigation("Sender");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.MessageQueue", b =>
                {
                    b.HasOne("QuickCode.Demo.EmailManagerModule.Domain.Entities.Campaign", "Campaign")
                        .WithMany("MessageQueues")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickCode.Demo.EmailManagerModule.Domain.Entities.Message", "Message")
                        .WithMany("MessageQueues")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickCode.Demo.EmailManagerModule.Domain.Entities.Sender", "Sender")
                        .WithMany("MessageQueues")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Campaign");

                    b.Navigation("Message");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.OtpMessage", b =>
                {
                    b.HasOne("QuickCode.Demo.EmailManagerModule.Domain.Entities.MessageTemplate", "Template")
                        .WithMany("OtpMessages")
                        .HasForeignKey("TemplateName")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Template");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.OtpMessageLog", b =>
                {
                    b.HasOne("QuickCode.Demo.EmailManagerModule.Domain.Entities.OtpMessage", "OtpMessage")
                        .WithMany("OtpMessageLogs")
                        .HasForeignKey("OtpMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickCode.Demo.EmailManagerModule.Domain.Entities.Sender", "Sender")
                        .WithMany("OtpMessageLogs")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuickCode.Demo.EmailManagerModule.Domain.Entities.MessageTemplate", "Template")
                        .WithMany("OtpMessageLogs")
                        .HasForeignKey("TemplateName")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OtpMessage");

                    b.Navigation("Sender");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.OtpMessageQueue", b =>
                {
                    b.HasOne("QuickCode.Demo.EmailManagerModule.Domain.Entities.OtpMessage", "OtpMessage")
                        .WithMany("OtpMessageQueues")
                        .HasForeignKey("OtpMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickCode.Demo.EmailManagerModule.Domain.Entities.Sender", "Sender")
                        .WithMany("OtpMessageQueues")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OtpMessage");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("MessageQueues");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.Message", b =>
                {
                    b.Navigation("MessageLogs");

                    b.Navigation("MessageQueues");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.MessageTemplate", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("MessageLogs");

                    b.Navigation("Messages");

                    b.Navigation("OtpMessageLogs");

                    b.Navigation("OtpMessages");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.OtpMessage", b =>
                {
                    b.Navigation("OtpMessageLogs");

                    b.Navigation("OtpMessageQueues");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.Sender", b =>
                {
                    b.Navigation("MessageLogs");

                    b.Navigation("MessageQueues");

                    b.Navigation("OtpMessageLogs");

                    b.Navigation("OtpMessageQueues");
                });
#pragma warning restore 612, 618
        }
    }
}
