INSERT INTO [dbo].[PRODUCT_VARIANT_ATTRIBUTES] (
    [VARIANT_ID],
    [ATTRIBUTE_VALUE_ID]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_PRODUCT_VARIANT_ATTRIBUTE_VARIANT_ID,
    @PRM_PRODUCT_VARIANT_ATTRIBUTE_ATTRIBUTE_VALUE_ID
    );