DELETE FROM [CAMPAIGN_APPLICABILITIES] 
WHERE [CAMPAIGN_ID] = @PRM_CAMPAIGN_APPLICABILITY_CAMPAIGN_ID 
	AND [SCOPE] = @PRM_CAMPAIGN_APPLICABILITY_SCOPE 
	AND [SCOPE_ID] = @PRM_CAMPAIGN_APPLICABILITY_SCOPE_ID