//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.UserManagerModule.Domain.Entities;
using QuickCode.Demo.UserManagerModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Common;
using QuickCode.Demo.Common.Extensions;
using QuickCode.Demo.Common.Helpers;
using QuickCode.Demo.UserManagerModule.Persistence.Contexts;
using QuickCode.Demo.UserManagerModule.Application.Dtos.PortalMenu;
using QuickCode.Demo.UserManagerModule.Application.Mappings;
using QuickCode.Demo.UserManagerModule.Persistence.Sql;
using QuickCode.Demo.UserManagerModule.Domain.Enums;

namespace QuickCode.Demo.UserManagerModule.Persistence.Repositories
{
    public partial class PortalMenuRepository : BaseRepository, IPortalMenuRepository
    {
        public async Task<RepoResponse<int>> DeletePortalMenuItemsWithModuleNameAsync(string portalMenusKey)
        {
            return await ExecuteWithExceptionHandling("PortalMenu", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalMenu.Command.DeletePortalMenuItemsWithModuleName);
                var parameters = new
                {
                    PRM_PortalMenus_Key = portalMenusKey
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }

        public async Task<RepoResponse<int>> DeletePortalMenuItemsWithModelNameAsync(string portalMenusKey, string portalMenusName)
        {
            return await ExecuteWithExceptionHandling("PortalMenu", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalMenu.Command.DeletePortalMenuItemsWithModelName);
                var parameters = new
                {
                    PRM_PortalMenus_Key = portalMenusKey,
                    PRM_PortalMenus_Name = portalMenusName
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}