SELECT S.[ID], S.[TRACKING_NUMBER], S.[STATUS], S.[SHIPPED_DATE] 
FROM [SHIPMENTS] S 
WHERE S.[IsDeleted] = 0 
	AND S.[ORDER_ID] = @PRM_SHIPMENT_ORDER_ID 
ORDER BY S.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 