SELECT [ID], [NAME], [DESCRIPTION], [TARGET_AUDIENCE], [MIN_ORDER_AMOUNT] 
FROM [CAMPAIGNS] 
WHERE [IsDeleted] = 0 
	AND [IS_ACTIVE] = @PRM_CAMPAIGNS_IS_ACTIVE 
	AND [START_DATE] <= GETDATE() 
	AND [END_DATE] >= GETDATE() 
ORDER BY [ID] 