SELECT C2.[ID], C2.[NAME], C2.[DESCRIPTION], C2.[START_DATE], C2.[END_DATE], C2.[IS_ACTIVE], C2.[BUDGET], C2.[TARGET_AUDIENCE], C2.[MIN_ORDER_AMOUNT] 
FROM [COUPONS] C 
	INNER JOIN [CAMPAIGNS] C2 
			ON C.[CAMPAIGN_ID] = C2.[ID] 
WHERE C.[IsDeleted] = 0 
	AND C2.[IsDeleted] = 0 
	AND C2.[ID] = @PRM_CAMPAIGNS_ID 
ORDER BY C2.[ID] 