SELECT C.[ID], C.[COUPON_CODE], C.[CAMPAIGN_ID], C.[USER_ID], C.[DISCOUNT_RATE], C.[DISCOUNT_AMOUNT], C.[MAX_USAGE], C.[USED_COUNT], C.[START_DATE], C.[END_DATE], C.[IS_SINGLE_USE] 
FROM [COUPONS] C 
	INNER JOIN [CAMPAIGNS] C2 
			ON C.[CAMPAIGN_ID] = C2.[ID] 
WHERE C.[IsDeleted] = 0 
	AND C2.[IsDeleted] = 0 
	AND C.[ID] = @PRM_COUPONS_ID 
	AND C2.[ID] = @PRM_CAMPAIGNS_ID 
ORDER BY C.[ID] 