SELECT TOP 1 AVG(SPR.[RATING]) AS AVERAGE_RATING,
	COUNT(*) AS REVIEW_COUNT 
FROM [SELLER_PERFORMANCE_REVIEWS] SPR 
WHERE SPR.[IsDeleted] = 0 
	AND SPR.[SELLER_ID] = @PRM_SELLER_PERFORMANCE_REVIEW_SELLER_ID 