SELECT SPR.[ID], SPR.[RATING], SPR.[COMMENT], SPR.[REVIEW_DATE] 
FROM [SELLER_PERFORMANCE_REVIEWS] SPR 
WHERE SPR.[IsDeleted] = 0 
	AND SPR.[SELLER_ID] = @PRM_SELLER_PERFORMANCE_REVIEW_SELLER_ID 
ORDER BY SPR.[REVIEW_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 