SELECT CE.[ID], CE.[SITE_ID], CE.[APARTMENT_ID], CE.[NAME], CE.[EXPENSE_TYPE_ID], CE.[YEAR_ID], CE.[MONTH_ID], CE.[EXPENSE_AMOUNT], CE.[DESCRIPTION], CE.[PAID], CE.[PAID_AT], CE.[PAYMENT_TYPE_ID], CE.[CREATED_DATE] 
FROM [COMMON_EXPENSES] CE 
	INNER JOIN [PAYMENT_TYPES] PT 
			ON CE.[PAYMENT_TYPE_ID] = PT.[ID] 
WHERE CE.[IsDeleted] = 0 
	AND PT.[IsDeleted] = 0 
	AND PT.[ID] = @PRM_PAYMENT_TYPES_ID 
ORDER BY CE.[ID] 