SELECT FEI.[ID], FEI.[SITE_ID], FEI.[APARTMENT_ID], FEI.[FLAT_ID], FEI.[EXPENSE_ID], FEI.[EXPENSE_INSTALLMENT_ID], FEI.[FLAT_INSTALLMENT_NUMBER], FEI.[TOTAL_FLAT_INSTALLMENTS], FEI.[FLAT_INSTALLMENT_AMOUNT], FEI.[DUE_DATE], FEI.[PAID], FEI.[PAID_AT], FEI.[PAYMENT_TYPE_ID], FEI.[CREATED_DATE] 
FROM [FLAT_EXPENSE_INSTALLMENTS] FEI 
	INNER JOIN [PAYMENT_TYPES] PT 
			ON FEI.[PAYMENT_TYPE_ID] = PT.[ID] 
WHERE FEI.[IsDeleted] = 0 
	AND PT.[IsDeleted] = 0 
	AND PT.[ID] = @PRM_PAYMENT_TYPES_ID 
ORDER BY FEI.[ID] 