UPDATE [dbo].[PAYOUT_PERIODS]
SET
    [START_DATE] = @PRM_PAYOUT_PERIOD_START_DATE,
    [END_DATE] = @PRM_PAYOUT_PERIOD_END_DATE,
    [IS_CLOSED] = @PRM_PAYOUT_PERIOD_IS_CLOSED
WHERE
    [ID] = @PRM_PAYOUT_PERIOD_ID
    AND [IsDeleted] = 0;