INSERT INTO [dbo].[PAYOUT_PERIODS] (
    [START_DATE],
    [END_DATE],
    [IS_CLOSED]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_PAYOUT_PERIOD_START_DATE,
    @PRM_PAYOUT_PERIOD_END_DATE,
    @PRM_PAYOUT_PERIOD_IS_CLOSED
    );