SELECT
    [ID],
    [START_DATE],
    [END_DATE],
    [IS_CLOSED]
FROM [dbo].[PAYOUT_PERIODS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;