SELECT CR.[ID], CR.[SCOPE], CR.[SCOPE_ID], CR.[COMMISSION_TYPE] 
FROM [COMMISSION_RULES] CR 
WHERE CR.[IsDeleted] = 0 
	AND CR.[COMMISSION_MODEL_ID] = @PRM_COMMISSION_RULE_COMMISSION_MODEL_ID 
	AND CR.[IS_ACTIVE] = 1 
ORDER BY CR.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 