SELECT CAST(YEAR([ORDER_DATE]) AS varchar) AS ORDER_DATE,
	MAX([TOTAL_AMOUNT]) AS MAX_TOTAL,
	COUNT([TOTAL_AMOUNT]) AS COUNT_TOTAL 
FROM [ORDERS] 
WHERE [IsDeleted] = 0 
	AND [USER_ID] = @PRM_ORDERS_USER_ID 
GROUP BY CAST(YEAR([ORDER_DATE]) AS varchar) 
HAVING MAX([TOTAL_AMOUNT]) > @PRM_ORDERS_TOTAL_AMOUNT 
ORDER BY CAST(YEAR([ORDER_DATE]) AS varchar) 