SELECT O.[ID], O.[USER_ID], O.[ORDER_DATE], O.[TOTAL_AMOUNT], O.[STATUS], O.[PAYMENT_ID], O.[SHIPPING_INFO_ID] 
FROM [ORDER_ITEMS] OI 
	INNER JOIN [ORDERS] O 
			ON OI.[ORDER_ID] = O.[ID] 
WHERE OI.[IsDeleted] = 0 
	AND O.[IsDeleted] = 0 
	AND O.[ID] = @PRM_ORDERS_ID 
ORDER BY O.[ID] 