SELECT O.[ID], O.[USER_ID], O.[ORDER_DATE], O.[TOTAL_AMOUNT], O.[STATUS], O.[PAYMENT_ID], O.[SHIPPING_INFO_ID] 
FROM [SHIPMENTS] S 
	INNER JOIN [ORDERS] O 
			ON S.[ORDER_ID] = O.[ID] 
WHERE S.[IsDeleted] = 0 
	AND O.[IsDeleted] = 0 
	AND O.[ID] = @PRM_ORDERS_ID 
ORDER BY O.[ID] 