SELECT S.[ID], S.[ORDER_ID], S.[CARGO_COMPANY], S.[TRACKING_CODE], S.[SHIPPED_DATE], S.[DELIVERED_DATE], S.[STATUS], S.[NOTE] 
FROM [SHIPMENTS] S 
	INNER JOIN [ORDERS] O 
			ON S.[ORDER_ID] = O.[ID] 
WHERE S.[IsDeleted] = 0 
	AND O.[IsDeleted] = 0 
	AND S.[ID] = @PRM_SHIPMENTS_ID 
	AND O.[ID] = @PRM_ORDERS_ID 
ORDER BY S.[ID] 