SELECT O.[ID] AS ORDER_ID,
	O.[ORDER_DATE], O.[TOTAL_AMOUNT] AS ORDER_TOTAL_AMOUNT 
FROM [ORDERS] O 
	INNER JOIN [PAYMENTS] P 
			ON O.[PAYMENT_ID] = P.[ID] 
WHERE O.[IsDeleted] = 0 
	AND P.[IsDeleted] = 0 
	AND O.[USER_ID] = @PRM_ORDERS_USER_ID 
	AND P.[STATUS] = @PRM_PAYMENTS_STATUS 
ORDER BY O.[ID] 