UPDATE [dbo].[ORDER_ITEMS]
SET
    [ORDER_ID] = @PRM_ORDER_ITEM_ORDER_ID,
    [PRODUCT_VARIANT_ID] = @PRM_ORDER_ITEM_PRODUCT_VARIANT_ID,
    [PRODUCT_NAME] = @PRM_ORDER_ITEM_PRODUCT_NAME,
    [SKU] = @PRM_ORDER_ITEM_SKU,
    [QUANTITY] = @PRM_ORDER_ITEM_QUANTITY,
    [UNIT_PRICE] = @PRM_ORDER_ITEM_UNIT_PRICE,
    [TOTAL_PRICE] = @PRM_ORDER_ITEM_TOTAL_PRICE
WHERE
    [ID] = @PRM_ORDER_ITEM_ID
    AND [IsDeleted] = 0;