INSERT INTO [dbo].[ORDER_ITEMS] (
    [ORDER_ID],
    [PRODUCT_VARIANT_ID],
    [PRODUCT_NAME],
    [SKU],
    [QUANTITY],
    [UNIT_PRICE],
    [TOTAL_PRICE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_ORDER_ITEM_ORDER_ID,
    @PRM_ORDER_ITEM_PRODUCT_VARIANT_ID,
    @PRM_ORDER_ITEM_PRODUCT_NAME,
    @PRM_ORDER_ITEM_SKU,
    @PRM_ORDER_ITEM_QUANTITY,
    @PRM_ORDER_ITEM_UNIT_PRICE,
    @PRM_ORDER_ITEM_TOTAL_PRICE
    );