SELECT
    [ID],
    [ORDER_ID],
    [PRODUCT_VARIANT_ID],
    [PRODUCT_NAME],
    [SKU],
    [QUANTITY],
    [UNIT_PRICE],
    [TOTAL_PRICE]
FROM [dbo].[ORDER_ITEMS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;