//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.ApartmentManageModule.Domain.Enums;

namespace QuickCode.Demo.ApartmentManageModule.Application.Dtos
{
    public record FlatPaymentsGetUnpaidPaymentsCountBySiteResponseDto
    {
        public int Id { get; init; }
        public int SiteId { get; init; }
        public int FlatId { get; init; }
        public int ApartmentId { get; init; }
        public int YearId { get; init; }
        public int MonthId { get; init; }
        public decimal PaymentAmount { get; init; }
        public int FeeTypeId { get; init; }
        public string Description { get; init; }
        public int FeePlanId { get; init; }
        public int? ExpenseId { get; init; }
        public bool Paid { get; init; }
        public DateTime? PaidAt { get; init; }
        public int PaymentTypeId { get; init; }
        public DateTime CreatedDate { get; init; }
    }
}