INSERT INTO [dbo].[PRODUCTS] (
    [SELLER_ID],
    [BRAND_ID],
    [PRIMARY_CATEGORY_ID],
    [SKU],
    [NAME],
    [DESCRIPTION],
    [STATUS],
    [IS_FEATURED],
    [CREATED_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_PRODUCT_SELLER_ID,
    @PRM_PRODUCT_BRAND_ID,
    @PRM_PRODUCT_PRIMARY_CATEGORY_ID,
    @PRM_PRODUCT_SKU,
    @PRM_PRODUCT_NAME,
    @PRM_PRODUCT_DESCRIPTION,
    @PRM_PRODUCT_STATUS,
    @PRM_PRODUCT_IS_FEATURED,
    @PRM_PRODUCT_CREATED_DATE
    );