UPDATE [dbo].[PRODUCTS]
SET
    [SELLER_ID] = @PRM_PRODUCT_SELLER_ID,
    [BRAND_ID] = @PRM_PRODUCT_BRAND_ID,
    [PRIMARY_CATEGORY_ID] = @PRM_PRODUCT_PRIMARY_CATEGORY_ID,
    [SKU] = @PRM_PRODUCT_SKU,
    [NAME] = @PRM_PRODUCT_NAME,
    [DESCRIPTION] = @PRM_PRODUCT_DESCRIPTION,
    [STATUS] = @PRM_PRODUCT_STATUS,
    [IS_FEATURED] = @PRM_PRODUCT_IS_FEATURED,
    [CREATED_DATE] = @PRM_PRODUCT_CREATED_DATE
WHERE
    [ID] = @PRM_PRODUCT_ID
    AND [IsDeleted] = 0;