SELECT
    [ID],
    [SELLER_ID],
    [BRAND_ID],
    [PRIMARY_CATEGORY_ID],
    [SKU],
    [NAME],
    [DESCRIPTION],
    [STATUS],
    [IS_FEATURED],
    [CREATED_DATE]
FROM [dbo].[PRODUCTS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;