SELECT C.[ID], C.[NAME], C.[PHONE], C.[EMAIL], C.[IDENTITY_NUMBER], C.[ADDRESS], C.[IS_ACTIVE], C.[CREATED_DATE] 
FROM [FLAT_CONTACTS] FC 
	INNER JOIN [CONTACTS] C 
			ON FC.[CONTACT_ID] = C.[ID] 
WHERE FC.[IsDeleted] = 0 
	AND C.[IsDeleted] = 0 
	AND C.[ID] = @PRM_CONTACTS_ID 
ORDER BY FC.[ID] 