SELECT C.[ID], C.[NAME], C.[PHONE], C.[EMAIL], C.[IDENTITY_NUMBER], C.[ADDRESS], C.[IS_ACTIVE], C.[CREATED_DATE] 
FROM [SITE_MANAGERS] SM 
	INNER JOIN [CONTACTS] C 
			ON SM.[CONTACT_ID] = C.[ID] 
WHERE SM.[IsDeleted] = 0 
	AND C.[IsDeleted] = 0 
	AND C.[ID] = @PRM_CONTACTS_ID 
ORDER BY C.[ID] 