SELECT P.[ID], P.[NAME], P.[DESCRIPTION], P.[START_DATE], P.[END_DATE], P.[CREATED_AT], P.[UPDATED_AT], P.[USER_ID] 
FROM [PROJECTS] P 
	INNER JOIN [USERS] U 
			ON P.[USER_ID] = U.[ID] 
WHERE P.[IsDeleted] = 0 
	AND U.[IsDeleted] = 0 
	AND P.[ID] = @PRM_PROJECTS_ID 
	AND U.[ID] = @PRM_USERS_ID 
ORDER BY P.[ID] 