SELECT T.[ID], T.[TITLE], T.[DESCRIPTION], T.[STATUS], T.[PRIORITY], T.[DUE_DATE], T.[CREATED_AT], T.[UPDATED_AT], T.[USER_ID] 
FROM [TASKS] T 
	INNER JOIN [USERS] U 
			ON T.[USER_ID] = U.[ID] 
WHERE T.[IsDeleted] = 0 
	AND U.[IsDeleted] = 0 
	AND T.[ID] = @PRM_TASKS_ID 
	AND U.[ID] = @PRM_USERS_ID 
ORDER BY T.[ID] 