SELECT TC.[ID], TC.[TASK_ID], TC.[USER_ID], TC.[COMMENT], TC.[CREATED_AT] 
FROM [TASK_COMMENTS] TC 
	INNER JOIN [USERS] U 
			ON TC.[USER_ID] = U.[ID] 
WHERE TC.[IsDeleted] = 0 
	AND U.[IsDeleted] = 0 
	AND TC.[ID] = @PRM_TASK_COMMENTS_ID 
	AND U.[ID] = @PRM_USERS_ID 
ORDER BY TC.[ID] 