SELECT U.[ID], U.[USERNAME], U.[EMAIL], U.[PASSWORD], U.[IS_ACTIVE] 
FROM [TASKS] T 
	INNER JOIN [USERS] U 
			ON T.[USER_ID] = U.[ID] 
WHERE T.[IsDeleted] = 0 
	AND U.[IsDeleted] = 0 
	AND U.[ID] = @PRM_USERS_ID 
ORDER BY U.[ID] 