SELECT U.[ID], U.[USERNAME], U.[EMAIL], U.[PASSWORD], U.[IS_ACTIVE] 
FROM [TASK_COMMENTS] TC 
	INNER JOIN [USERS] U 
			ON TC.[USER_ID] = U.[ID] 
WHERE TC.[IsDeleted] = 0 
	AND U.[IsDeleted] = 0 
	AND U.[ID] = @PRM_USERS_ID 
ORDER BY U.[ID] 