//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.UserManagerModule.Application.Dtos;
using QuickCode.Demo.UserManagerModule.Domain.Entities;

namespace QuickCode.Demo.UserManagerModule.Application.Mappings
{
    public static class ApiMethodDefinitionsMappings
    {
        public static List<ApiMethodDefinitionsDto> ToDto(this IEnumerable<ApiMethodDefinitions> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ApiMethodDefinitionsDto ToDto(this ApiMethodDefinitions model)
        {
            return new ApiMethodDefinitionsDto
            {
                Id = model.Id,
                HttpMethod = model.HttpMethod,
                ControllerName = model.ControllerName,
                UrlPath = model.UrlPath,
                ItemType = model.ItemType
            };
        }

        public static ApiMethodDefinitions ToModel(this ApiMethodDefinitionsDto model)
        {
            return new ApiMethodDefinitions
            {
                Id = model.Id,
                HttpMethod = model.HttpMethod,
                ControllerName = model.ControllerName,
                UrlPath = model.UrlPath,
                ItemType = model.ItemType
            };
        }
    }
}