//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.UserManagerModule.Application.Dtos;
using QuickCode.Demo.UserManagerModule.Domain.Entities;
using QuickCode.Demo.UserManagerModule.Domain.Enums;

namespace QuickCode.Demo.UserManagerModule.Application.Mappings
{
    public static class KafkaEventsMappings
    {
        public static List<KafkaEventsDto> ToDto(this IEnumerable<KafkaEvents> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static KafkaEventsDto ToDto(this KafkaEvents model)
        {
            return new KafkaEventsDto
            {
                TopicName = model.TopicName,
                ApiMethodDefinitionKey = model.ApiMethodDefinitionKey,
                IsActive = model.IsActive
            };
        }

        public static KafkaEvents ToModel(this KafkaEventsDto model)
        {
            return new KafkaEvents
            {
                TopicName = model.TopicName,
                ApiMethodDefinitionKey = model.ApiMethodDefinitionKey,
                IsActive = model.IsActive
            };
        }
    }
}