//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.UserManagerModule.Application.Dtos;
using QuickCode.Demo.UserManagerModule.Domain.Entities;

namespace QuickCode.Demo.UserManagerModule.Application.Mappings
{
    public static class PortalPermissionGroupsMappings
    {
        public static List<PortalPermissionGroupsDto> ToDto(this IEnumerable<PortalPermissionGroups> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static PortalPermissionGroupsDto ToDto(this PortalPermissionGroups model)
        {
            return new PortalPermissionGroupsDto
            {
                Id = model.Id,
                PortalPermissionId = model.PortalPermissionId,
                PermissionGroupId = model.PermissionGroupId,
                PortalPermissionTypeId = model.PortalPermissionTypeId
            };
        }

        public static PortalPermissionGroups ToModel(this PortalPermissionGroupsDto model)
        {
            return new PortalPermissionGroups
            {
                Id = model.Id,
                PortalPermissionId = model.PortalPermissionId,
                PermissionGroupId = model.PermissionGroupId,
                PortalPermissionTypeId = model.PortalPermissionTypeId
            };
        }
    }
}