//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.UserManagerModule.Application.Dtos.PortalPermissionType;
using QuickCode.Demo.UserManagerModule.Domain.Entities;
using QuickCode.Demo.UserManagerModule.Domain.Enums;

namespace QuickCode.Demo.UserManagerModule.Application.Mappings
{
    public static class PortalPermissionTypeMappings
    {
        public static List<PortalPermissionTypeDto> ToDto(this IEnumerable<PortalPermissionType> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static PortalPermissionTypeDto ToDto(this PortalPermissionType model)
        {
            return new PortalPermissionTypeDto
            {
                Id = model.Id,
                Name = model.Name,
                Description = model.Description
            };
        }

        public static PortalPermissionType ToModel(this PortalPermissionTypeDto model)
        {
            return new PortalPermissionType
            {
                Id = model.Id,
                Name = model.Name,
                Description = model.Description
            };
        }
    }
}