//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.UserManagerModule.Application.Dtos;
using QuickCode.Demo.UserManagerModule.Domain.Entities;
using QuickCode.Demo.UserManagerModule.Domain.Enums;

namespace QuickCode.Demo.UserManagerModule.Application.Mappings
{
    public static class TableComboboxSettingsMappings
    {
        public static List<TableComboboxSettingsDto> ToDto(this IEnumerable<TableComboboxSettings> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static TableComboboxSettingsDto ToDto(this TableComboboxSettings model)
        {
            return new TableComboboxSettingsDto
            {
                TableName = model.TableName,
                IdColumn = model.IdColumn,
                TextColumns = model.TextColumns,
                StringFormat = model.StringFormat
            };
        }

        public static TableComboboxSettings ToModel(this TableComboboxSettingsDto model)
        {
            return new TableComboboxSettings
            {
                TableName = model.TableName,
                IdColumn = model.IdColumn,
                TextColumns = model.TextColumns,
                StringFormat = model.StringFormat
            };
        }
    }
}