SELECT
    [ID],
    [CATEGORY_ID],
    [COMMISSION_MODEL_ID],
    [EFFECTIVE_DATE]
FROM [dbo].[CATEGORY_COMMISSION_OVERRIDES]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;