UPDATE [dbo].[CATEGORY_COMMISSION_OVERRIDES]
SET
    [CATEGORY_ID] = @PRM_CATEGORY_COMMISSION_OVERRIDE_CATEGORY_ID,
    [COMMISSION_MODEL_ID] = @PRM_CATEGORY_COMMISSION_OVERRIDE_COMMISSION_MODEL_ID,
    [EFFECTIVE_DATE] = @PRM_CATEGORY_COMMISSION_OVERRIDE_EFFECTIVE_DATE
WHERE
    [ID] = @PRM_CATEGORY_COMMISSION_OVERRIDE_ID
    AND [IsDeleted] = 0;