INSERT INTO [dbo].[CATEGORY_COMMISSION_OVERRIDES] (
    [CATEGORY_ID],
    [COMMISSION_MODEL_ID],
    [EFFECTIVE_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_CATEGORY_COMMISSION_OVERRIDE_CATEGORY_ID,
    @PRM_CATEGORY_COMMISSION_OVERRIDE_COMMISSION_MODEL_ID,
    @PRM_CATEGORY_COMMISSION_OVERRIDE_EFFECTIVE_DATE
    );