SELECT
    [ID],
    [CATEGORY_ID],
    [COMMISSION_MODEL_ID],
    [EFFECTIVE_DATE]
FROM [dbo].[CATEGORY_COMMISSION_OVERRIDES]
WHERE
    [ID] = @PRM_CATEGORY_COMMISSION_OVERRIDE_ID
    AND [IsDeleted] = 0;