//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.OnlineShopModule.Domain.Entities;
using QuickCode.Demo.OnlineShopModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Common;
using QuickCode.Demo.Common.Extensions;
using QuickCode.Demo.Common.Helpers;
using QuickCode.Demo.OnlineShopModule.Persistence.Contexts;
using QuickCode.Demo.OnlineShopModule.Application.Dtos.User;
using QuickCode.Demo.OnlineShopModule.Application.Mappings;
using QuickCode.Demo.OnlineShopModule.Persistence.Sql;
using QuickCode.Demo.OnlineShopModule.Domain.Enums;

namespace QuickCode.Demo.OnlineShopModule.Persistence.Repositories
{
    public partial class UserRepository : BaseRepository, IUserRepository
    {
        public async Task<RepoResponse<List<GetNewUsersResponseDto>>> GetNewUsersAsync(bool usersIsNew)
        {
            return await ExecuteWithExceptionHandling("GetNewUsers", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.User.Query.GetNewUsers);
                var parameters = new
                {
                    PRM_USERS_IS_NEW = usersIsNew
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetNewUsersResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in User");
            });
        }

        public async Task<RepoResponse<List<GetCouponsForUsersResponseDto>>> GetCouponsForUsersAsync(int usersId)
        {
            return await ExecuteWithExceptionHandling("GetCouponsForUsers", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.User.Query.GetCouponsForUsers);
                var parameters = new
                {
                    PRM_USERS_ID = usersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetCouponsForUsersResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in User");
            });
        }

        public async Task<RepoResponse<GetCouponsForUsersResponseDto>> GetCouponsForUsersDetailsAsync(int usersId, int couponsId)
        {
            return await ExecuteWithExceptionHandling("GetCouponsForUsersDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.User.Query.GetCouponsForUsersDetails);
                var parameters = new
                {
                    PRM_COUPONS_ID = couponsId,
                    PRM_USERS_ID = usersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetCouponsForUsersResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in User");
            });
        }

        public async Task<RepoResponse<List<GetUserCouponsForUsersResponseDto>>> GetUserCouponsForUsersAsync(int usersId)
        {
            return await ExecuteWithExceptionHandling("GetUserCouponsForUsers", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.User.Query.GetUserCouponsForUsers);
                var parameters = new
                {
                    PRM_USERS_ID = usersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetUserCouponsForUsersResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in User");
            });
        }

        public async Task<RepoResponse<GetUserCouponsForUsersResponseDto>> GetUserCouponsForUsersDetailsAsync(int usersId, int userCouponsUserId)
        {
            return await ExecuteWithExceptionHandling("GetUserCouponsForUsersDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.User.Query.GetUserCouponsForUsersDetails);
                var parameters = new
                {
                    PRM_USER_COUPONS_USER_ID = userCouponsUserId,
                    PRM_USERS_ID = usersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetUserCouponsForUsersResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in User");
            });
        }

        public async Task<RepoResponse<List<GetProductReviewsForUsersResponseDto>>> GetProductReviewsForUsersAsync(int usersId)
        {
            return await ExecuteWithExceptionHandling("GetProductReviewsForUsers", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.User.Query.GetProductReviewsForUsers);
                var parameters = new
                {
                    PRM_USERS_ID = usersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetProductReviewsForUsersResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in User");
            });
        }

        public async Task<RepoResponse<GetProductReviewsForUsersResponseDto>> GetProductReviewsForUsersDetailsAsync(int usersId, int productReviewsId)
        {
            return await ExecuteWithExceptionHandling("GetProductReviewsForUsersDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.User.Query.GetProductReviewsForUsersDetails);
                var parameters = new
                {
                    PRM_PRODUCT_REVIEWS_ID = productReviewsId,
                    PRM_USERS_ID = usersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetProductReviewsForUsersResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in User");
            });
        }

        public async Task<RepoResponse<List<GetCartsForUsersResponseDto>>> GetCartsForUsersAsync(int usersId)
        {
            return await ExecuteWithExceptionHandling("GetCartsForUsers", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.User.Query.GetCartsForUsers);
                var parameters = new
                {
                    PRM_USERS_ID = usersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetCartsForUsersResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in User");
            });
        }

        public async Task<RepoResponse<GetCartsForUsersResponseDto>> GetCartsForUsersDetailsAsync(int usersId, int cartsId)
        {
            return await ExecuteWithExceptionHandling("GetCartsForUsersDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.User.Query.GetCartsForUsersDetails);
                var parameters = new
                {
                    PRM_CARTS_ID = cartsId,
                    PRM_USERS_ID = usersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetCartsForUsersResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in User");
            });
        }

        public async Task<RepoResponse<List<GetOrdersForUsersResponseDto>>> GetOrdersForUsersAsync(int usersId)
        {
            return await ExecuteWithExceptionHandling("GetOrdersForUsers", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.User.Query.GetOrdersForUsers);
                var parameters = new
                {
                    PRM_USERS_ID = usersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetOrdersForUsersResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in User");
            });
        }

        public async Task<RepoResponse<GetOrdersForUsersResponseDto>> GetOrdersForUsersDetailsAsync(int usersId, int ordersId)
        {
            return await ExecuteWithExceptionHandling("GetOrdersForUsersDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.User.Query.GetOrdersForUsersDetails);
                var parameters = new
                {
                    PRM_ORDERS_ID = ordersId,
                    PRM_USERS_ID = usersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetOrdersForUsersResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in User");
            });
        }
    }
}