//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.ApartmentManageModule.Domain.Entities;
using QuickCode.Demo.ApartmentManageModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Common;
using QuickCode.Demo.Common.Extensions;
using QuickCode.Demo.ApartmentManageModule.Persistence.Contexts;
using QuickCode.Demo.ApartmentManageModule.Application.Dtos;
using QuickCode.Demo.ApartmentManageModule.Application.Mappings;
using QuickCode.Demo.ApartmentManageModule.Domain.Enums;

namespace QuickCode.Demo.ApartmentManageModule.Persistence.Repositories
{
    public partial class ApartmentsRepository : BaseRepository, IApartmentsRepository
    {
        const int DefaultPageSize = 20;
        const int MinPageNumber = 1;
        private readonly WriteDbContext _writeContext;
        private readonly ReadDbContext _readContext;
        public ApartmentsRepository(ILogger<ApartmentsRepository> logger, WriteDbContext writeContext, ReadDbContext readContext) : base(logger, "Apartments")
        {
            _writeContext = writeContext;
            _readContext = readContext;
        }

        public async Task<RepoResponse<ApartmentsDto>> InsertAsync(ApartmentsDto value)
        {
            return await ExecuteWithExceptionHandling("Insert", async () =>
            {
                await _writeContext.Apartments.AddAsync(value.ToModel());
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<ApartmentsDto>(value, "Not Defined");
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(ApartmentsDto value)
        {
            return await ExecuteWithExceptionHandling("Update", async () =>
            {
                _writeContext.Set<Apartments>().Update(value.ToModel());
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<bool>(true, "Success");
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(ApartmentsDto value)
        {
            return await ExecuteWithExceptionHandling("Delete", async () =>
            {
                _writeContext.Apartments.Remove(value.ToModel());
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<bool>(true, "Success");
            });
        }

        public async Task<RepoResponse<ApartmentsDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling("GetByPk", async () =>
            {
                var result =
                    from apartments in _readContext.Apartments
                    where apartments.Id.Equals(id)
                    select apartments;
                var response = await result.FirstOrDefaultAsync();
                return response == null ? new RepoResponse<ApartmentsDto>
                {
                    Code = 404,
                    Message = "Not found in Apartments"
                }

                : new RepoResponse<ApartmentsDto>(response.ToDto(), "Success");
            });
        }

        public async Task<RepoResponse<List<ApartmentsDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling("Select", async () =>
            {
                if (pageNumber.HasValue && pageNumber < MinPageNumber)
                {
                    return new RepoResponse<List<ApartmentsDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {MinPageNumber}"};
                }

                var query = _readContext.Apartments.OrderBy(o => o.Id).AsQueryable();
                if (pageNumber.HasValue && pageSize.HasValue)
                {
                    query = ApplyPagination(query, pageNumber.Value, pageSize.Value);
                }

                var result = await query.ToListAsync();
                return new RepoResponse<List<ApartmentsDto>>(result.ToDto(), "Success");
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling("Count", async () =>
            {
                return new RepoResponse<int>(await _readContext.Apartments.CountAsync(), "Success");
            });
        }
    }
}