SELECT CASE WHEN EXISTS (
SELECT 1 
FROM [FLAT_CONTACTS] 
WHERE [IsDeleted] = 0 
	AND [FLAT_ID] = @PRM_FLAT_CONTACTS_FLAT_ID 
	AND [RELATIONSHIP_TYPE] = @PRM_FLAT_CONTACTS_RELATIONSHIP_TYPE 
	AND [IS_ACTIVE] = @PRM_FLAT_CONTACTS_IS_ACTIVE 
ORDER BY [ID] ) THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END