SELECT [FLAT_ID], [RELATIONSHIP_TYPE], [START_DATE] 
FROM [FLAT_CONTACTS] 
WHERE [IsDeleted] = 0 
	AND [CONTACT_ID] = @PRM_FLAT_CONTACTS_CONTACT_ID 
	AND [IS_ACTIVE] = @PRM_FLAT_CONTACTS_IS_ACTIVE 
ORDER BY [ID] 