SELECT [FLAT_ID] 
FROM [FLAT_CONTACTS] 
WHERE [IsDeleted] = 0 
	AND [CONTACT_ID] = @PRM_FLAT_CONTACTS_CONTACT_ID 
	AND [RELATIONSHIP_TYPE] = @PRM_FLAT_CONTACTS_RELATIONSHIP_TYPE 
	AND [IS_ACTIVE] = @PRM_FLAT_CONTACTS_IS_ACTIVE 
ORDER BY [ID] 