//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.UserManagerModule.Domain.Entities;
using QuickCode.Demo.UserManagerModule.Application.Dtos;
using System.Threading.Tasks;
using QuickCode.Demo.UserManagerModule.Domain.Enums;

namespace QuickCode.Demo.UserManagerModule.Application.Interfaces.Repositories
{
    public partial interface IPermissionGroupsRepository : IBaseRepository<PermissionGroupsDto>
    {
        Task<RepoResponse<PermissionGroupsDto>> GetByPkAsync(string name);
        Task<RepoResponse<List<PermissionGroupsGetAspNetUsersForPermissionGroupsResponseDto>>> PermissionGroupsGetAspNetUsersForPermissionGroupsAsync(string permissionGroupsName);
        Task<RepoResponse<PermissionGroupsGetAspNetUsersForPermissionGroupsResponseDto>> PermissionGroupsGetAspNetUsersForPermissionGroupsDetailsAsync(string permissionGroupsName, string aspNetUsersId);
        Task<RepoResponse<List<PermissionGroupsGetPortalPermissionGroupsForPermissionGroupsResponseDto>>> PermissionGroupsGetPortalPermissionGroupsForPermissionGroupsAsync(string permissionGroupsName);
        Task<RepoResponse<PermissionGroupsGetPortalPermissionGroupsForPermissionGroupsResponseDto>> PermissionGroupsGetPortalPermissionGroupsForPermissionGroupsDetailsAsync(string permissionGroupsName, string portalPermissionGroupsPortalPermissionName);
        Task<RepoResponse<List<PermissionGroupsGetApiPermissionGroupsForPermissionGroupsResponseDto>>> PermissionGroupsGetApiPermissionGroupsForPermissionGroupsAsync(string permissionGroupsName);
        Task<RepoResponse<PermissionGroupsGetApiPermissionGroupsForPermissionGroupsResponseDto>> PermissionGroupsGetApiPermissionGroupsForPermissionGroupsDetailsAsync(string permissionGroupsName, string apiPermissionGroupsPermissionGroupName);
    }
}