SELECT A.[ID], A.[SITE_ID], A.[NAME], A.[ADDRESS], A.[TOTAL_FLATS], A.[IS_ACTIVE], A.[CREATED_DATE] 
FROM [APARTMENT_FEE_PLANS] AFP 
	INNER JOIN [APARTMENTS] A 
			ON AFP.[APARTMENT_ID] = A.[ID] 
WHERE AFP.[IsDeleted] = 0 
	AND A.[IsDeleted] = 0 
	AND A.[ID] = @PRM_APARTMENTS_ID 
ORDER BY AFP.[ID] 