SELECT A.[ID], A.[SITE_ID], A.[NAME], A.[ADDRESS], A.[TOTAL_FLATS], A.[IS_ACTIVE], A.[CREATED_DATE] 
FROM [COMMON_EXPENSES] CE 
	INNER JOIN [APARTMENTS] A 
			ON CE.[APARTMENT_ID] = A.[ID] 
WHERE CE.[IsDeleted] = 0 
	AND A.[IsDeleted] = 0 
	AND A.[ID] = @PRM_APARTMENTS_ID 
ORDER BY CE.[ID] 