SELECT A.[ID], A.[SITE_ID], A.[NAME], A.[ADDRESS], A.[TOTAL_FLATS], A.[IS_ACTIVE], A.[CREATED_DATE] 
FROM [FLATS] F 
	INNER JOIN [APARTMENTS] A 
			ON F.[APARTMENT_ID] = A.[ID] 
WHERE F.[IsDeleted] = 0 
	AND A.[IsDeleted] = 0 
	AND A.[ID] = @PRM_APARTMENTS_ID 
ORDER BY A.[ID] 