SELECT A.[ID], A.[SITE_ID], A.[NAME], A.[ADDRESS], A.[TOTAL_FLATS], A.[IS_ACTIVE], A.[CREATED_DATE] 
FROM [FLAT_PAYMENTS] FP 
	INNER JOIN [APARTMENTS] A 
			ON FP.[APARTMENT_ID] = A.[ID] 
WHERE FP.[IsDeleted] = 0 
	AND A.[IsDeleted] = 0 
	AND A.[ID] = @PRM_APARTMENTS_ID 
ORDER BY A.[ID] 