SELECT CASE WHEN EXISTS (
SELECT 1 
FROM [SITE_MANAGERS] 
WHERE [IsDeleted] = 0 
	AND [SITE_ID] = @PRM_SITE_MANAGERS_SITE_ID 
	AND [IS_ACTIVE] = @PRM_SITE_MANAGERS_IS_ACTIVE ) THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END