SELECT TL.[ID], TL.[AMOUNT], TL.[DESCRIPTION], TL.[TRANSACTION_DATE] 
FROM [TRANSACTION_LEDGERS] TL 
WHERE TL.[IsDeleted] = 0 
	AND TL.[SELLER_ID] = @PRM_TRANSACTION_LEDGER_SELLER_ID 
	AND TL.[TRANSACTION_TYPE] = @PRM_TRANSACTION_LEDGER_TRANSACTION_TYPE 
	AND TL.[TRANSACTION_DATE] BETWEEN @PRM_TRANSACTION_LEDGER_TRANSACTION_DATE_From 
	AND @PRM_TRANSACTION_LEDGER_TRANSACTION_DATE_To 
ORDER BY TL.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 