// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.Demo.FinanceSettlementModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class TransactionLedger
    {
        public static class Query
        {
            private const string _prefix = "FinanceSettlementModule.TransactionLedger.Query";
            private const string _sqlScriptStem = "TransactionLedger";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string GetBySellerId => ResourceKey($"{_sqlScriptStem}.GetBySellerId.g.sql");
            public static string GetSellerBalance => ResourceKey($"{_sqlScriptStem}.GetSellerBalance.g.sql");
            public static string GetTransactionsByTypeAndDate => ResourceKey($"{_sqlScriptStem}.GetTransactionsByTypeAndDate.g.sql");
        }
    }
}