SELECT AFP.[ID], AFP.[SITE_ID], AFP.[APARTMENT_ID], AFP.[YEAR_ID], AFP.[MONTH_ID], AFP.[FEE_AMOUNT], AFP.[IS_ACTIVE] 
FROM [APARTMENT_FEE_PLANS] AFP 
	INNER JOIN [SITES] S 
			ON AFP.[SITE_ID] = S.[ID] 
WHERE AFP.[IsDeleted] = 0 
	AND S.[IsDeleted] = 0 
	AND AFP.[ID] = @PRM_APARTMENT_FEE_PLANS_ID 
	AND S.[ID] = @PRM_SITES_ID 
ORDER BY AFP.[ID] 