SELECT S.[ID], S.[NAME], S.[ADDRESS], S.[CITY], S.[DISTRICT], S.[POSTAL_CODE], S.[COUNTRY], S.[PHONE], S.[EMAIL], S.[IS_ACTIVE], S.[CREATED_DATE] 
FROM [COMMON_EXPENSES] CE 
	INNER JOIN [SITES] S 
			ON CE.[SITE_ID] = S.[ID] 
WHERE CE.[IsDeleted] = 0 
	AND S.[IsDeleted] = 0 
	AND S.[ID] = @PRM_SITES_ID 
ORDER BY S.[ID] 