SELECT S.[ID], S.[NAME], S.[ADDRESS], S.[CITY], S.[DISTRICT], S.[POSTAL_CODE], S.[COUNTRY], S.[PHONE], S.[EMAIL], S.[IS_ACTIVE], S.[CREATED_DATE] 
FROM [EXPENSE_INSTALLMENTS] EI 
	INNER JOIN [SITES] S 
			ON EI.[SITE_ID] = S.[ID] 
WHERE EI.[IsDeleted] = 0 
	AND S.[IsDeleted] = 0 
	AND S.[ID] = @PRM_SITES_ID 
ORDER BY S.[ID] 