SELECT S.[ID], S.[NAME], S.[ADDRESS], S.[CITY], S.[DISTRICT], S.[POSTAL_CODE], S.[COUNTRY], S.[PHONE], S.[EMAIL], S.[IS_ACTIVE], S.[CREATED_DATE] 
FROM [FLAT_EXPENSE_INSTALLMENTS] FEI 
	INNER JOIN [SITES] S 
			ON FEI.[SITE_ID] = S.[ID] 
WHERE FEI.[IsDeleted] = 0 
	AND S.[IsDeleted] = 0 
	AND S.[ID] = @PRM_SITES_ID 
ORDER BY FEI.[ID] 