SELECT SM.[ID], SM.[SITE_ID], SM.[CONTACT_ID], SM.[START_DATE], SM.[END_DATE], SM.[IS_ACTIVE], SM.[CREATED_DATE] 
FROM [SITE_MANAGERS] SM 
	INNER JOIN [SITES] S 
			ON SM.[SITE_ID] = S.[ID] 
WHERE SM.[IsDeleted] = 0 
	AND S.[IsDeleted] = 0 
	AND SM.[ID] = @PRM_SITE_MANAGERS_ID 
	AND S.[ID] = @PRM_SITES_ID 
ORDER BY SM.[ID] 