SELECT TOP 1 [ID], [MESSAGE_ID], [CAMPAIGN_ID], [SENDER_ID], [ATTEMPT_DATE], [RECIPIENT], [SUBJECT], [BODY], [TEMPLATE_NAME], [STATUS], [ATTEMPT_COUNT], [SENT_DATE] 
FROM [MESSAGE_LOGS] 
WHERE [IsDeleted] = 0 
	AND [ID] = @PRM_MESSAGE_LOGS_ID 
ORDER BY [ID] 