SELECT ML.[ID], ML.[RECIPIENT], S.[NAME] AS SENDER_NAME 
FROM [MESSAGE_LOGS] ML 
	INNER JOIN [SENDERS] S 
			ON ML.[SENDER_ID] = S.[ID] 
WHERE ML.[IsDeleted] = 0 
	AND S.[IsDeleted] = 0 
	AND S.[IS_ACTIVE] = @PRM_SENDERS_IS_ACTIVE 
ORDER BY ML.[ID] 