UPDATE [FLAT_EXPENSE_INSTALLMENTS] 
	SET [PAID] = true, [PAID_AT] = GETDATE(), [PAYMENT_TYPE_ID] = @FLAT_EXPENSE_INSTALLMENTS_PAYMENT_TYPE_ID 
WHERE [IsDeleted] = 0 
	AND [ID] = @PRM_FLAT_EXPENSE_INSTALLMENTS_ID