//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.ApartmentManageModule.Domain.Entities;
using QuickCode.Demo.ApartmentManageModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Common;
using QuickCode.Demo.Common.Extensions;
using QuickCode.Demo.Common.Helpers;
using QuickCode.Demo.ApartmentManageModule.Persistence.Contexts;
using QuickCode.Demo.ApartmentManageModule.Application.Dtos;
using QuickCode.Demo.ApartmentManageModule.Application.Mappings;
using QuickCode.Demo.ApartmentManageModule.Application.Sql;
using QuickCode.Demo.ApartmentManageModule.Domain.Enums;

namespace QuickCode.Demo.ApartmentManageModule.Persistence.Repositories
{
    public partial class ExpenseInstallmentsRepository : BaseRepository, IExpenseInstallmentsRepository
    {
        public async Task<RepoResponse<List<ExpenseInstallmentsGetExpenseInstallmentsResponseDto>>> ExpenseInstallmentsGetExpenseInstallmentsAsync(int expenseInstallmentsExpenseId)
        {
            return await ExecuteWithExceptionHandling("ExpenseInstallmentsGetExpenseInstallments", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ExpenseInstallments.Query.GetExpenseInstallments);
                var parameters = new
                {
                    PRM_EXPENSE_INSTALLMENTS_EXPENSE_ID = expenseInstallmentsExpenseId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<ExpenseInstallmentsGetExpenseInstallmentsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ExpenseInstallments");
            });
        }

        public async Task<RepoResponse<List<ExpenseInstallmentsGetUnpaidInstallmentsResponseDto>>> ExpenseInstallmentsGetUnpaidInstallmentsAsync(int expenseInstallmentsExpenseId, bool expenseInstallmentsPaid)
        {
            return await ExecuteWithExceptionHandling("ExpenseInstallmentsGetUnpaidInstallments", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ExpenseInstallments.Query.GetUnpaidInstallments);
                var parameters = new
                {
                    PRM_EXPENSE_INSTALLMENTS_EXPENSE_ID = expenseInstallmentsExpenseId,
                    PRM_EXPENSE_INSTALLMENTS_PAID = expenseInstallmentsPaid
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<ExpenseInstallmentsGetUnpaidInstallmentsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ExpenseInstallments");
            });
        }

        public async Task<RepoResponse<List<ExpenseInstallmentsGetOverdueInstallmentsResponseDto>>> ExpenseInstallmentsGetOverdueInstallmentsAsync(bool expenseInstallmentsPaid)
        {
            return await ExecuteWithExceptionHandling("ExpenseInstallmentsGetOverdueInstallments", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ExpenseInstallments.Query.GetOverdueInstallments);
                var parameters = new
                {
                    PRM_EXPENSE_INSTALLMENTS_PAID = expenseInstallmentsPaid
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<ExpenseInstallmentsGetOverdueInstallmentsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ExpenseInstallments");
            });
        }

        public async Task<RepoResponse<List<ExpenseInstallmentsGetApartmentInstallmentsResponseDto>>> ExpenseInstallmentsGetApartmentInstallmentsAsync(int expenseInstallmentsSiteId, int expenseInstallmentsApartmentId)
        {
            return await ExecuteWithExceptionHandling("ExpenseInstallmentsGetApartmentInstallments", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ExpenseInstallments.Query.GetApartmentInstallments);
                var parameters = new
                {
                    PRM_EXPENSE_INSTALLMENTS_SITE_ID = expenseInstallmentsSiteId,
                    PRM_EXPENSE_INSTALLMENTS_APARTMENT_ID = expenseInstallmentsApartmentId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<ExpenseInstallmentsGetApartmentInstallmentsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ExpenseInstallments");
            });
        }

        public async Task<RepoResponse<List<ExpenseInstallmentsGetSiteInstallmentsResponseDto>>> ExpenseInstallmentsGetSiteInstallmentsAsync(int expenseInstallmentsSiteId)
        {
            return await ExecuteWithExceptionHandling("ExpenseInstallmentsGetSiteInstallments", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ExpenseInstallments.Query.GetSiteInstallments);
                var parameters = new
                {
                    PRM_EXPENSE_INSTALLMENTS_SITE_ID = expenseInstallmentsSiteId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<ExpenseInstallmentsGetSiteInstallmentsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ExpenseInstallments");
            });
        }

        public async Task<RepoResponse<List<ExpenseInstallmentsGetFlatExpenseInstallmentsForExpenseInstallmentsResponseDto>>> ExpenseInstallmentsGetFlatExpenseInstallmentsForExpenseInstallmentsAsync(int expenseInstallmentsId)
        {
            return await ExecuteWithExceptionHandling("ExpenseInstallmentsGetFlatExpenseInstallmentsForExpenseInstallments", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ExpenseInstallments.Query.GetFlatExpenseInstallmentsForExpenseInstallments);
                var parameters = new
                {
                    PRM_EXPENSE_INSTALLMENTS_ID = expenseInstallmentsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<ExpenseInstallmentsGetFlatExpenseInstallmentsForExpenseInstallmentsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ExpenseInstallments");
            });
        }

        public async Task<RepoResponse<ExpenseInstallmentsGetFlatExpenseInstallmentsForExpenseInstallmentsResponseDto>> ExpenseInstallmentsGetFlatExpenseInstallmentsForExpenseInstallmentsDetailsAsync(int expenseInstallmentsId, int flatExpenseInstallmentsId)
        {
            return await ExecuteWithExceptionHandling("ExpenseInstallmentsGetFlatExpenseInstallmentsForExpenseInstallmentsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ExpenseInstallments.Query.GetFlatExpenseInstallmentsForExpenseInstallmentsDetails);
                var parameters = new
                {
                    PRM_FLAT_EXPENSE_INSTALLMENTS_ID = flatExpenseInstallmentsId,
                    PRM_EXPENSE_INSTALLMENTS_ID = expenseInstallmentsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<ExpenseInstallmentsGetFlatExpenseInstallmentsForExpenseInstallmentsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in ExpenseInstallments");
            });
        }
    }
}