IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PAYOUT_LINE_ITEMS_SELLER_PAYOUTS_PAYOUT_ID' AND parent_object_id = OBJECT_ID(N'dbo.PAYOUT_LINE_ITEMS'))
BEGIN
    ALTER TABLE [dbo].[PAYOUT_LINE_ITEMS] ADD CONSTRAINT [FK_PAYOUT_LINE_ITEMS_SELLER_PAYOUTS_PAYOUT_ID] FOREIGN KEY ([PAYOUT_ID]) REFERENCES [dbo].[SELLER_PAYOUTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SELLER_PAYOUTS_PAYOUT_PERIODS_PAYOUT_PERIOD_ID' AND parent_object_id = OBJECT_ID(N'dbo.SELLER_PAYOUTS'))
BEGIN
    ALTER TABLE [dbo].[SELLER_PAYOUTS] ADD CONSTRAINT [FK_SELLER_PAYOUTS_PAYOUT_PERIODS_PAYOUT_PERIOD_ID] FOREIGN KEY ([PAYOUT_PERIOD_ID]) REFERENCES [dbo].[PAYOUT_PERIODS] ([ID]);
END