IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TRANSACTION_LEDGERS', N'U') AND name = N'IX_TRANSACTION_LEDGERS_SELLER_ID_TRANSACTION_TYPE')
BEGIN
    CREATE INDEX [IX_TRANSACTION_LEDGERS_SELLER_ID_TRANSACTION_TYPE] ON [dbo].[TRANSACTION_LEDGERS] ([SELLER_ID], [TRANSACTION_TYPE]);
END