IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SELLER_PAYOUTS', N'U') AND name = N'IX_SELLER_PAYOUTS_PAYOUT_PERIOD_ID')
BEGIN
    CREATE INDEX [IX_SELLER_PAYOUTS_PAYOUT_PERIOD_ID] ON [dbo].[SELLER_PAYOUTS] ([PAYOUT_PERIOD_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SELLER_PAYOUTS', N'U') AND name = N'IX_SELLER_PAYOUTS_SELLER_ID')
BEGIN
    CREATE INDEX [IX_SELLER_PAYOUTS_SELLER_ID] ON [dbo].[SELLER_PAYOUTS] ([SELLER_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SELLER_PAYOUTS', N'U') AND name = N'IX_SELLER_PAYOUTS_STATUS')
BEGIN
    CREATE INDEX [IX_SELLER_PAYOUTS_STATUS] ON [dbo].[SELLER_PAYOUTS] ([STATUS]);
END