IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMISSION_ENTRIES', N'U') AND name = N'IX_COMMISSION_ENTRIES_ORDER_ID')
BEGIN
    CREATE INDEX [IX_COMMISSION_ENTRIES_ORDER_ID] ON [dbo].[COMMISSION_ENTRIES] ([ORDER_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMISSION_ENTRIES', N'U') AND name = N'IX_COMMISSION_ENTRIES_SELLER_ID')
BEGIN
    CREATE INDEX [IX_COMMISSION_ENTRIES_SELLER_ID] ON [dbo].[COMMISSION_ENTRIES] ([SELLER_ID]);
END