SELECT
    [ID],
    [USER_ID],
    [COMPANY_NAME],
    [CONTACT_EMAIL],
    [CONTACT_PHONE],
    [STATUS],
    [SELLER_TIER_ID],
    [JOINED_DATE]
FROM [dbo].[SELLERS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;