SELECT SM.[ID], P.[NAME], P.[PHONE], P.[EMAIL], SM.[START_DATE], SM.[END_DATE] 
FROM [SITE_MANAGERS] SM 
	INNER JOIN [CONTACTS] P 
			ON SM.[CONTACT_ID] = P.[ID] 
WHERE SM.[IsDeleted] = 0 
	AND P.[IsDeleted] = 0 
	AND SM.[CONTACT_ID] = @PRM_SITE_MANAGERS_CONTACT_ID 
ORDER BY SM.[ID] 