SELECT [ID], [FLAT_ID], [EXPENSE_ID], [FLAT_INSTALLMENT_NUMBER], [FLAT_INSTALLMENT_AMOUNT], [DUE_DATE], [PAID] 
FROM [FLAT_EXPENSE_INSTALLMENTS] 
WHERE [IsDeleted] = 0 
	AND [SITE_ID] = @PRM_FLAT_EXPENSE_INSTALLMENTS_SITE_ID 
	AND [APARTMENT_ID] = @PRM_FLAT_EXPENSE_INSTALLMENTS_APARTMENT_ID 
ORDER BY [ID] 