SELECT [ID], [EXPENSE_ID], [FLAT_INSTALLMENT_NUMBER], [FLAT_INSTALLMENT_AMOUNT], [DUE_DATE] 
FROM [FLAT_EXPENSE_INSTALLMENTS] 
WHERE [IsDeleted] = 0 
	AND [FLAT_ID] = @PRM_FLAT_EXPENSE_INSTALLMENTS_FLAT_ID 
	AND [PAID] = @PRM_FLAT_EXPENSE_INSTALLMENTS_PAID 
ORDER BY [ID] 