SELECT SUM([FLAT_INSTALLMENT_AMOUNT]) AS TOTAL_DEBT 
FROM [FLAT_EXPENSE_INSTALLMENTS] 
WHERE [IsDeleted] = 0 
	AND [FLAT_ID] = @PRM_FLAT_EXPENSE_INSTALLMENTS_FLAT_ID 
	AND [PAID] = @PRM_FLAT_EXPENSE_INSTALLMENTS_PAID 