//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.EmailManagerModule.Application.Dtos.CampaignMessage;
using QuickCode.Demo.EmailManagerModule.Domain.Entities;

namespace QuickCode.Demo.EmailManagerModule.Application.Mappings
{
    public static class CampaignMessageMappings
    {
        public static List<CampaignMessageDto> ToDto(this IEnumerable<CampaignMessage> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static CampaignMessageDto ToDto(this CampaignMessage model)
        {
            return new CampaignMessageDto
            {
                Id = model.Id,
                EmailSenderId = model.EmailSenderId,
                CampaignTypeId = model.CampaignTypeId,
                GsmNumber = model.GsmNumber,
                Message = model.Message,
                MessageDate = model.MessageDate,
                MessageSid = model.MessageSid,
                DailyCounter = model.DailyCounter
            };
        }

        public static CampaignMessage ToModel(this CampaignMessageDto model)
        {
            return new CampaignMessage
            {
                Id = model.Id,
                EmailSenderId = model.EmailSenderId,
                CampaignTypeId = model.CampaignTypeId,
                GsmNumber = model.GsmNumber,
                Message = model.Message,
                MessageDate = model.MessageDate,
                MessageSid = model.MessageSid,
                DailyCounter = model.DailyCounter
            };
        }
    }
}