//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.EmailManagerModule.Application.Dtos.InfoType;
using QuickCode.Demo.EmailManagerModule.Domain.Entities;

namespace QuickCode.Demo.EmailManagerModule.Application.Mappings
{
    public static class InfoTypeMappings
    {
        public static List<InfoTypeDto> ToDto(this IEnumerable<InfoType> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static InfoTypeDto ToDto(this InfoType model)
        {
            return new InfoTypeDto
            {
                Id = model.Id,
                Name = model.Name,
                Template = model.Template
            };
        }

        public static InfoType ToEntity(this InfoTypeDto model)
        {
            return new InfoType
            {
                Id = model.Id,
                Name = model.Name,
                Template = model.Template
            };
        }
    }
}