//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.EmailManagerModule.Application.Dtos;
using QuickCode.Demo.EmailManagerModule.Domain.Entities;

namespace QuickCode.Demo.EmailManagerModule.Application.Mappings
{
    public static class OtpMessagesMappings
    {
        public static List<OtpMessagesDto> ToDto(this IEnumerable<OtpMessages> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static OtpMessagesDto ToDto(this OtpMessages model)
        {
            return new OtpMessagesDto
            {
                Id = model.Id,
                EmailSenderId = model.EmailSenderId,
                OtpTypeId = model.OtpTypeId,
                GsmNumber = model.GsmNumber,
                OtpCode = model.OtpCode,
                Message = model.Message,
                ExpireSeconds = model.ExpireSeconds,
                MessageDate = model.MessageDate,
                MessageSid = model.MessageSid,
                DailyCounter = model.DailyCounter
            };
        }

        public static OtpMessages ToModel(this OtpMessagesDto model)
        {
            return new OtpMessages
            {
                Id = model.Id,
                EmailSenderId = model.EmailSenderId,
                OtpTypeId = model.OtpTypeId,
                GsmNumber = model.GsmNumber,
                OtpCode = model.OtpCode,
                Message = model.Message,
                ExpireSeconds = model.ExpireSeconds,
                MessageDate = model.MessageDate,
                MessageSid = model.MessageSid,
                DailyCounter = model.DailyCounter
            };
        }
    }
}