//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Demo.Portal.Models;
using QuickCode.Demo.Portal.Models.EmailManagerModule;
using QuickCode.Demo.Portal.Helpers;
using Microsoft.AspNetCore.Mvc;
using UserManagerModuleContracts = QuickCode.Demo.Common.Nswag.Clients.UserManagerModuleApi.Contracts;
using EmailManagerModuleContracts = QuickCode.Demo.Common.Nswag.Clients.EmailManagerModuleApi.Contracts;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using QuickCode.Demo.Portal.Helpers.Authorization;
using Microsoft.AspNetCore.Http;
using System.Threading;
using System.Threading.Tasks;
using AutoRest.Core.Utilities.Collections;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace QuickCode.Demo.Portal.Controllers.EmailManagerModule
{
    [Permission("EmailManagerModuleMessageLogs")]
    [Area("EmailManagerModule")]
    [Route("EmailManagerModuleMessageLogs")]
    public partial class MessageLogsController : BaseController
    {
        private readonly EmailManagerModuleContracts.IMessageLogsClient pageClient;
        private readonly EmailManagerModuleContracts.IMessagesClient pageMessageClient;
        private readonly EmailManagerModuleContracts.ISendersClient pageSenderClient;
        private readonly EmailManagerModuleContracts.IMessageTemplatesClient pageMessageTemplateClient;
        public MessageLogsController(EmailManagerModuleContracts.IMessageLogsClient pageClient, EmailManagerModuleContracts.IMessagesClient pageMessageClient, EmailManagerModuleContracts.ISendersClient pageSenderClient, EmailManagerModuleContracts.IMessageTemplatesClient pageMessageTemplateClient, UserManagerModuleContracts.ITableComboboxSettingsClient tableComboboxSettingsClient, IHttpContextAccessor httpContextAccessor, IMemoryCache cache) : base(tableComboboxSettingsClient, httpContextAccessor, cache)
        {
            this.pageClient = pageClient;
            this.pageMessageClient = pageMessageClient;
            this.pageSenderClient = pageSenderClient;
            this.pageMessageTemplateClient = pageMessageTemplateClient;
        }

        [ResponseCache(VaryByQueryKeys = new[] { "ic" }, Duration = 30)]
        public async Task<IActionResult> GetImage(string ic)
        {
            return await GetImageResult(pageClient, ic);
        }

        [Route("List")]
        public async Task<IActionResult> List()
        {
            var model = await PrepareModel();
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("List")]
        [HttpPost]
        public async Task<IActionResult> List(MessageLogData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("Insert")]
        [HttpPost]
        public async Task<IActionResult> Insert(MessageLogData model)
        {
            ModelBinder(ref model);
            var result = await pageClient.MessageLogsInsertAsync(model.SelectedItem);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Update")]
        [HttpPost]
        public async Task<IActionResult> Update(MessageLogData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.MessageLogsUpdateAsync(request.Id, request);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Delete")]
        [HttpPost]
        public async Task<IActionResult> Delete(MessageLogData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.MessageLogsDeleteAsync(request.Id);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("InsertItem")]
        public IActionResult InsertItem(MessageLogData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            SetModelBinder(ref model);
            model.SelectedItem = new();
            return PartialView("Insert", model);
        }

        [Route("DetailItem")]
        public async Task<IActionResult> DetailItem(MessageLogData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Detail", model);
        }

        [Route("UpdateItem")]
        [HttpPost]
        public async Task<IActionResult> UpdateItem(MessageLogData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Update", model);
        }

        [Route("DeleteItem")]
        [HttpPost]
        public async Task<IActionResult> DeleteItem(MessageLogData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Delete", model);
        }

        private async Task<MessageLogData> PrepareModel()
        {
            var model = GetModel<MessageLogData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            return await PrepareModel(model);
        }

        private async Task<MessageLogData> PrepareModel(MessageLogData model)
        {
            model.NumberOfRecord = await pageClient.MessageLogsCountAsync();
            model.TotalPage = (model.NumberOfRecord + PageSize - 1) / PageSize;
            model.List = (await pageClient.MessageLogsListAsync(model.CurrentPage, PageSize)).ToList();
            return model;
        }

        private async Task<Dictionary<string, Dictionary<string, string>>> FillPageComboBoxes(Dictionary<string, Dictionary<string, string>> comboBoxList)
        {
            comboBoxList.Clear();
            comboBoxList.AddRange(await FillComboBoxAsync("Messages", () => pageMessageClient.MessagesListAsync()));
            comboBoxList.AddRange(await FillComboBoxAsync("Senders", () => pageSenderClient.SendersListAsync()));
            comboBoxList.AddRange(await FillComboBoxAsync("MessageTemplates", () => pageMessageTemplateClient.MessageTemplatesListAsync()));
            return comboBoxList;
        }
    }
}