//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.SmsManagerModule.Domain.Entities;
using QuickCode.Demo.SmsManagerModule.Application.Dtos.CampaignType;
using System.Threading.Tasks;

namespace QuickCode.Demo.SmsManagerModule.Application.Interfaces.Repositories
{
    public partial interface ICampaignTypeRepository : IBaseRepository<CampaignTypeDto>
    {
        Task<RepoResponse<CampaignTypeDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetCampaignMessagesForCampaignTypesResponseDto>>> GetCampaignMessagesForCampaignTypesAsync(int campaignTypesId);
        Task<RepoResponse<GetCampaignMessagesForCampaignTypesResponseDto>> GetCampaignMessagesForCampaignTypesDetailsAsync(int campaignTypesId, int campaignMessagesId);
    }
}