SELECT [ID], [INSTALLMENT_NUMBER], [TOTAL_INSTALLMENTS], [INSTALLMENT_AMOUNT], [DUE_DATE], [PAID], [PAYMENT_TYPE_ID] 
FROM [EXPENSE_INSTALLMENTS] 
WHERE [IsDeleted] = 0 
	AND [EXPENSE_ID] = @PRM_EXPENSE_INSTALLMENTS_EXPENSE_ID 
ORDER BY [ID] 