SELECT EI.[ID], EI.[SITE_ID], EI.[APARTMENT_ID], EI.[EXPENSE_ID], EI.[INSTALLMENT_NUMBER], EI.[TOTAL_INSTALLMENTS], EI.[INSTALLMENT_AMOUNT], EI.[DUE_DATE], EI.[PAID], EI.[PAID_AT], EI.[PAYMENT_TYPE_ID], EI.[CREATED_DATE] 
FROM [FLAT_EXPENSE_INSTALLMENTS] FEI 
	INNER JOIN [EXPENSE_INSTALLMENTS] EI 
			ON FEI.[EXPENSE_INSTALLMENT_ID] = EI.[ID] 
WHERE FEI.[IsDeleted] = 0 
	AND EI.[IsDeleted] = 0 
	AND EI.[ID] = @PRM_EXPENSE_INSTALLMENTS_ID 
ORDER BY EI.[ID] 