SELECT PY.[ID], PY.[NAME] 
FROM [APARTMENT_FEE_PLANS] AFP 
	INNER JOIN [PAYMENT_YEARS] PY 
			ON AFP.[YEAR_ID] = PY.[ID] 
WHERE AFP.[IsDeleted] = 0 
	AND PY.[ID] = @PRM_PAYMENT_YEARS_ID 
ORDER BY PY.[ID] 