INSERT INTO [dbo].[SELLER_PAYOUTS] (
    [SELLER_ID],
    [PAYOUT_PERIOD_ID],
    [TOTAL_EARNINGS],
    [TOTAL_COMMISSION],
    [NET_PAYOUT_AMOUNT],
    [STATUS],
    [REQUESTED_DATE],
    [PROCESSED_DATE],
    [TRANSACTION_ID]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_SELLER_PAYOUT_SELLER_ID,
    @PRM_SELLER_PAYOUT_PAYOUT_PERIOD_ID,
    @PRM_SELLER_PAYOUT_TOTAL_EARNINGS,
    @PRM_SELLER_PAYOUT_TOTAL_COMMISSION,
    @PRM_SELLER_PAYOUT_NET_PAYOUT_AMOUNT,
    @PRM_SELLER_PAYOUT_STATUS,
    @PRM_SELLER_PAYOUT_REQUESTED_DATE,
    @PRM_SELLER_PAYOUT_PROCESSED_DATE,
    @PRM_SELLER_PAYOUT_TRANSACTION_ID
    );