SELECT
    [ID],
    [SELLER_ID],
    [PAYOUT_PERIOD_ID],
    [TOTAL_EARNINGS],
    [TOTAL_COMMISSION],
    [NET_PAYOUT_AMOUNT],
    [STATUS],
    [REQUESTED_DATE],
    [PROCESSED_DATE],
    [TRANSACTION_ID]
FROM [dbo].[SELLER_PAYOUTS]
WHERE
    [ID] = @PRM_SELLER_PAYOUT_ID
    AND [IsDeleted] = 0;