SELECT
    [ID],
    [SELLER_ID],
    [PAYOUT_PERIOD_ID],
    [TOTAL_EARNINGS],
    [TOTAL_COMMISSION],
    [NET_PAYOUT_AMOUNT],
    [STATUS],
    [REQUESTED_DATE],
    [PROCESSED_DATE],
    [TRANSACTION_ID]
FROM [dbo].[SELLER_PAYOUTS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;