UPDATE [dbo].[SELLER_PAYOUTS]
SET
    [SELLER_ID] = @PRM_SELLER_PAYOUT_SELLER_ID,
    [PAYOUT_PERIOD_ID] = @PRM_SELLER_PAYOUT_PAYOUT_PERIOD_ID,
    [TOTAL_EARNINGS] = @PRM_SELLER_PAYOUT_TOTAL_EARNINGS,
    [TOTAL_COMMISSION] = @PRM_SELLER_PAYOUT_TOTAL_COMMISSION,
    [NET_PAYOUT_AMOUNT] = @PRM_SELLER_PAYOUT_NET_PAYOUT_AMOUNT,
    [STATUS] = @PRM_SELLER_PAYOUT_STATUS,
    [REQUESTED_DATE] = @PRM_SELLER_PAYOUT_REQUESTED_DATE,
    [PROCESSED_DATE] = @PRM_SELLER_PAYOUT_PROCESSED_DATE,
    [TRANSACTION_ID] = @PRM_SELLER_PAYOUT_TRANSACTION_ID
WHERE
    [ID] = @PRM_SELLER_PAYOUT_ID
    AND [IsDeleted] = 0;