SELECT TOP 1 CCO.[COMMISSION_MODEL_ID], CCO.[EFFECTIVE_DATE] 
FROM [CATEGORY_COMMISSION_OVERRIDES] CCO 
WHERE CCO.[IsDeleted] = 0 
	AND CCO.[CATEGORY_ID] = @PRM_CATEGORY_COMMISSION_OVERRIDE_CATEGORY_ID 
ORDER BY  