SELECT O.[ID], O.[USER_ID], O.[ORDER_DATE], O.[TOTAL_AMOUNT], O.[STATUS], O.[PAYMENT_ID], O.[SHIPPING_INFO_ID] 
FROM [ORDERS] O 
	INNER JOIN [PAYMENTS] P 
			ON O.[PAYMENT_ID] = P.[ID] 
WHERE O.[IsDeleted] = 0 
	AND P.[IsDeleted] = 0 
	AND O.[ID] = @PRM_ORDERS_ID 
	AND P.[ID] = @PRM_PAYMENTS_ID 
ORDER BY O.[ID] 