SELECT P.[ID], P.[USER_ID], P.[ORDER_ID], P.[PAYMENT_DATE], P.[PAYMENT_METHOD], P.[TRANSACTION_ID], P.[AMOUNT], P.[STATUS] 
FROM [ORDERS] O 
	INNER JOIN [PAYMENTS] P 
			ON O.[PAYMENT_ID] = P.[ID] 
WHERE O.[IsDeleted] = 0 
	AND P.[IsDeleted] = 0 
	AND P.[ID] = @PRM_PAYMENTS_ID 
ORDER BY P.[ID] 