SELECT [ID], [CAMPAIGN_ID], [RECIPIENT], [SUBJECT], [BODY], [TEMPLATE_NAME], [STATUS], [ATTEMPT_COUNT], [LAST_ATTEMPT_DATE], [SENT_DATE] 
FROM [MESSAGES] 
WHERE [IsDeleted] = 0 
	AND [STATUS] = @PRM_MESSAGES_STATUS 
ORDER BY [ID] 