SELECT SP.[ID], SP.[NET_PAYOUT_AMOUNT], SP.[STATUS], SP.[REQUESTED_DATE] 
FROM [SELLER_PAYOUTS] SP 
WHERE SP.[IsDeleted] = 0 
	AND SP.[SELLER_ID] = @PRM_SELLER_PAYOUT_SELLER_ID 
ORDER BY SP.[REQUESTED_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 