SELECT SP.[ID], SP.[SELLER_ID], SP.[NET_PAYOUT_AMOUNT], SP.[STATUS] 
FROM [SELLER_PAYOUTS] SP 
WHERE SP.[IsDeleted] = 0 
	AND SP.[STATUS] = @PRM_SELLER_PAYOUT_STATUS 
ORDER BY SP.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 