SELECT C.[ID], C.[COUPON_CODE], C.[CAMPAIGN_ID], C.[USER_ID], C.[DISCOUNT_RATE], C.[DISCOUNT_AMOUNT], C.[MAX_USAGE], C.[USED_COUNT], C.[START_DATE], C.[END_DATE], C.[IS_SINGLE_USE] 
FROM [COUPONS] C 
	INNER JOIN [USERS] U 
			ON C.[USER_ID] = U.[ID] 
WHERE C.[IsDeleted] = 0 
	AND U.[IsDeleted] = 0 
	AND C.[ID] = @PRM_COUPONS_ID 
	AND U.[ID] = @PRM_USERS_ID 
ORDER BY C.[ID] 