SELECT U.[ID], U.[EMAIL], U.[NAME], U.[CREATED_AT], U.[IS_NEW], U.[COMPANY_ID] 
FROM [ORDERS] O 
	INNER JOIN [USERS] U 
			ON O.[USER_ID] = U.[ID] 
WHERE O.[IsDeleted] = 0 
	AND U.[IsDeleted] = 0 
	AND U.[ID] = @PRM_USERS_ID 
ORDER BY U.[ID] 