SELECT O.[ID], O.[USER_ID], O.[ORDER_DATE], O.[TOTAL_AMOUNT], O.[STATUS], O.[PAYMENT_ID], O.[SHIPPING_INFO_ID] 
FROM [ORDERS] O 
	INNER JOIN [USERS] U 
			ON O.[USER_ID] = U.[ID] 
WHERE O.[IsDeleted] = 0 
	AND U.[IsDeleted] = 0 
	AND O.[ID] = @PRM_ORDERS_ID 
	AND U.[ID] = @PRM_USERS_ID 
ORDER BY O.[ID] 