SELECT PR.[ID], PR.[PRODUCT_ID], PR.[USER_ID], PR.[RATING], PR.[COMMENT], PR.[CREATED_AT] 
FROM [PRODUCT_REVIEWS] PR 
	INNER JOIN [USERS] U 
			ON PR.[USER_ID] = U.[ID] 
WHERE PR.[IsDeleted] = 0 
	AND U.[IsDeleted] = 0 
	AND PR.[ID] = @PRM_PRODUCT_REVIEWS_ID 
	AND U.[ID] = @PRM_USERS_ID 
ORDER BY PR.[ID] 