SELECT U.[ID], U.[EMAIL], U.[NAME], U.[CREATED_AT], U.[IS_NEW], U.[COMPANY_ID] 
FROM [USER_COUPONS] UC 
	INNER JOIN [USERS] U 
			ON UC.[USER_ID] = U.[ID] 
WHERE U.[IsDeleted] = 0 
	AND U.[ID] = @PRM_USERS_ID 
ORDER BY U.[ID] 