SELECT UC.[USER_ID], UC.[COUPON_ID], UC.[IS_USED], UC.[USED_AT] 
FROM [USER_COUPONS] UC 
	INNER JOIN [USERS] U 
			ON UC.[USER_ID] = U.[ID] 
WHERE U.[IsDeleted] = 0 
	AND UC.[USER_ID] = @PRM_USER_COUPONS_USER_ID 
	AND U.[ID] = @PRM_USERS_ID 
ORDER BY UC.[USER_ID], UC.[COUPON_ID] 