//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.PricingEngineModule.Application.Dtos.SellerCommissionAssignment;
using SellerCommissionAssignmentEntity = QuickCode.Demo.PricingEngineModule.Domain.Entities.SellerCommissionAssignment;
using QuickCode.Demo.PricingEngineModule.Domain.Enums;

namespace QuickCode.Demo.PricingEngineModule.Application.Mappings
{
    public static class SellerCommissionAssignmentMappings
    {
        public static List<SellerCommissionAssignmentDto> ToDto(this IEnumerable<SellerCommissionAssignmentEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static SellerCommissionAssignmentDto ToDto(this SellerCommissionAssignmentEntity model)
        {
            return new SellerCommissionAssignmentDto
            {
                SellerId = model.SellerId,
                CommissionModelId = model.CommissionModelId,
                EffectiveDate = model.EffectiveDate
            };
        }

        public static SellerCommissionAssignmentEntity ToEntity(this SellerCommissionAssignmentDto model)
        {
            return new SellerCommissionAssignmentEntity
            {
                SellerId = model.SellerId,
                CommissionModelId = model.CommissionModelId,
                EffectiveDate = model.EffectiveDate
            };
        }
    }
}