//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.OnlineShopModule.Domain.Enums;

namespace QuickCode.Demo.OnlineShopModule.Application.Dtos.Coupon
{
    public record GetValidCouponsResponseDto
    {
        public int Id { get; init; }
        public string CouponCode { get; init; }
        public decimal DiscountRate { get; init; }
        public decimal DiscountAmount { get; init; }
    }
}