//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.SmsManagerModule.Application.Dtos.OtpMessage;
using QuickCode.Demo.SmsManagerModule.Domain.Entities;

namespace QuickCode.Demo.SmsManagerModule.Application.Mappings
{
    public static class OtpMessageMappings
    {
        public static List<OtpMessageDto> ToDto(this IEnumerable<OtpMessage> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static OtpMessageDto ToDto(this OtpMessage model)
        {
            return new OtpMessageDto
            {
                Id = model.Id,
                SmsSenderId = model.SmsSenderId,
                OtpTypeId = model.OtpTypeId,
                GsmNumber = model.GsmNumber,
                OtpCode = model.OtpCode,
                Message = model.Message,
                ExpireSeconds = model.ExpireSeconds,
                MessageDate = model.MessageDate,
                MessageSid = model.MessageSid,
                DailyCounter = model.DailyCounter
            };
        }

        public static OtpMessage ToEntity(this OtpMessageDto model)
        {
            return new OtpMessage
            {
                Id = model.Id,
                SmsSenderId = model.SmsSenderId,
                OtpTypeId = model.OtpTypeId,
                GsmNumber = model.GsmNumber,
                OtpCode = model.OtpCode,
                Message = model.Message,
                ExpireSeconds = model.ExpireSeconds,
                MessageDate = model.MessageDate,
                MessageSid = model.MessageSid,
                DailyCounter = model.DailyCounter
            };
        }
    }
}