//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.ProductCatalogModule.Application.Dtos.Brand;
using BrandEntity = QuickCode.Demo.ProductCatalogModule.Domain.Entities.Brand;
using QuickCode.Demo.ProductCatalogModule.Domain.Enums;

namespace QuickCode.Demo.ProductCatalogModule.Application.Mappings
{
    public static class BrandMappings
    {
        public static List<BrandDto> ToDto(this IEnumerable<BrandEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static BrandDto ToDto(this BrandEntity model)
        {
            return new BrandDto
            {
                Id = model.Id,
                Name = model.Name,
                LogoUrl = model.LogoUrl,
                IsActive = model.IsActive
            };
        }

        public static BrandEntity ToEntity(this BrandDto model)
        {
            return new BrandEntity
            {
                Id = model.Id,
                Name = model.Name,
                LogoUrl = model.LogoUrl,
                IsActive = model.IsActive
            };
        }
    }
}