//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.ApartmentManageModule.Application.Dtos;
using QuickCode.Demo.ApartmentManageModule.Domain.Entities;
using QuickCode.Demo.ApartmentManageModule.Domain.Enums;

namespace QuickCode.Demo.ApartmentManageModule.Application.Mappings
{
    public static class ContactsMappings
    {
        public static List<ContactsDto> ToDto(this IEnumerable<Contacts> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ContactsDto ToDto(this Contacts model)
        {
            return new ContactsDto
            {
                Id = model.Id,
                Name = model.Name,
                Phone = model.Phone,
                Email = model.Email,
                IdentityNumber = model.IdentityNumber,
                Address = model.Address,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }

        public static Contacts ToModel(this ContactsDto model)
        {
            return new Contacts
            {
                Id = model.Id,
                Name = model.Name,
                Phone = model.Phone,
                Email = model.Email,
                IdentityNumber = model.IdentityNumber,
                Address = model.Address,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }
    }
}