//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.ApartmentManageModule.Application.Dtos;
using QuickCode.Demo.ApartmentManageModule.Domain.Entities;
using QuickCode.Demo.ApartmentManageModule.Domain.Enums;

namespace QuickCode.Demo.ApartmentManageModule.Application.Mappings
{
    public static class FlatPaymentsMappings
    {
        public static List<FlatPaymentsDto> ToDto(this IEnumerable<FlatPayments> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static FlatPaymentsDto ToDto(this FlatPayments model)
        {
            return new FlatPaymentsDto
            {
                Id = model.Id,
                SiteId = model.SiteId,
                FlatId = model.FlatId,
                ApartmentId = model.ApartmentId,
                YearId = model.YearId,
                MonthId = model.MonthId,
                PaymentAmount = model.PaymentAmount,
                FeeTypeId = model.FeeTypeId,
                Description = model.Description,
                FeePlanId = model.FeePlanId,
                ExpenseId = model.ExpenseId,
                Paid = model.Paid,
                PaidAt = model.PaidAt,
                PaymentTypeId = model.PaymentTypeId,
                CreatedDate = model.CreatedDate
            };
        }

        public static FlatPayments ToModel(this FlatPaymentsDto model)
        {
            return new FlatPayments
            {
                Id = model.Id,
                SiteId = model.SiteId,
                FlatId = model.FlatId,
                ApartmentId = model.ApartmentId,
                YearId = model.YearId,
                MonthId = model.MonthId,
                PaymentAmount = model.PaymentAmount,
                FeeTypeId = model.FeeTypeId,
                Description = model.Description,
                FeePlanId = model.FeePlanId,
                ExpenseId = model.ExpenseId,
                Paid = model.Paid,
                PaidAt = model.PaidAt,
                PaymentTypeId = model.PaymentTypeId,
                CreatedDate = model.CreatedDate
            };
        }
    }
}