//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.ApartmentManageModule.Application.Dtos.PaymentMonth;
using QuickCode.Demo.ApartmentManageModule.Domain.Entities;
using QuickCode.Demo.ApartmentManageModule.Domain.Enums;

namespace QuickCode.Demo.ApartmentManageModule.Application.Mappings
{
    public static class PaymentMonthMappings
    {
        public static List<PaymentMonthDto> ToDto(this IEnumerable<PaymentMonth> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static PaymentMonthDto ToDto(this PaymentMonth model)
        {
            return new PaymentMonthDto
            {
                Id = model.Id,
                Name = model.Name
            };
        }

        public static PaymentMonth ToModel(this PaymentMonthDto model)
        {
            return new PaymentMonth
            {
                Id = model.Id,
                Name = model.Name
            };
        }
    }
}