//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.ApartmentManageModule.Application.Dtos.PaymentYear;
using QuickCode.Demo.ApartmentManageModule.Domain.Entities;
using QuickCode.Demo.ApartmentManageModule.Domain.Enums;

namespace QuickCode.Demo.ApartmentManageModule.Application.Mappings
{
    public static class PaymentYearMappings
    {
        public static List<PaymentYearDto> ToDto(this IEnumerable<PaymentYear> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static PaymentYearDto ToDto(this PaymentYear model)
        {
            return new PaymentYearDto
            {
                Id = model.Id,
                Name = model.Name
            };
        }

        public static PaymentYear ToEntity(this PaymentYearDto model)
        {
            return new PaymentYear
            {
                Id = model.Id,
                Name = model.Name
            };
        }
    }
}