//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.ApartmentManageModule.Application.Dtos;
using QuickCode.Demo.ApartmentManageModule.Domain.Entities;
using QuickCode.Demo.ApartmentManageModule.Domain.Enums;

namespace QuickCode.Demo.ApartmentManageModule.Application.Mappings
{
    public static class SiteManagersMappings
    {
        public static List<SiteManagersDto> ToDto(this IEnumerable<SiteManagers> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static SiteManagersDto ToDto(this SiteManagers model)
        {
            return new SiteManagersDto
            {
                Id = model.Id,
                SiteId = model.SiteId,
                ContactId = model.ContactId,
                StartDate = model.StartDate,
                EndDate = model.EndDate,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }

        public static SiteManagers ToModel(this SiteManagersDto model)
        {
            return new SiteManagers
            {
                Id = model.Id,
                SiteId = model.SiteId,
                ContactId = model.ContactId,
                StartDate = model.StartDate,
                EndDate = model.EndDate,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }
    }
}