SELECT
    [ID],
    [ORDER_ID],
    [SHIPPING_METHOD_ID],
    [TRACKING_NUMBER],
    [STATUS],
    [SHIPPED_DATE],
    [DELIVERED_DATE]
FROM [dbo].[SHIPMENTS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;