UPDATE [dbo].[SHIPMENTS]
SET
    [ORDER_ID] = @PRM_SHIPMENT_ORDER_ID,
    [SHIPPING_METHOD_ID] = @PRM_SHIPMENT_SHIPPING_METHOD_ID,
    [TRACKING_NUMBER] = @PRM_SHIPMENT_TRACKING_NUMBER,
    [STATUS] = @PRM_SHIPMENT_STATUS,
    [SHIPPED_DATE] = @PRM_SHIPMENT_SHIPPED_DATE,
    [DELIVERED_DATE] = @PRM_SHIPMENT_DELIVERED_DATE
WHERE
    [ID] = @PRM_SHIPMENT_ID
    AND [IsDeleted] = 0;