INSERT INTO [dbo].[SHIPMENTS] (
    [ORDER_ID],
    [SHIPPING_METHOD_ID],
    [TRACKING_NUMBER],
    [STATUS],
    [SHIPPED_DATE],
    [DELIVERED_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_SHIPMENT_ORDER_ID,
    @PRM_SHIPMENT_SHIPPING_METHOD_ID,
    @PRM_SHIPMENT_TRACKING_NUMBER,
    @PRM_SHIPMENT_STATUS,
    @PRM_SHIPMENT_SHIPPED_DATE,
    @PRM_SHIPMENT_DELIVERED_DATE
    );