SELECT PV.[ID], PV.[SKU], PV.[PRICE], PV.[STOCK_QUANTITY] 
FROM [PRODUCT_VARIANTS] PV 
WHERE PV.[IsDeleted] = 0 
	AND PV.[PRODUCT_ID] = @PRM_PRODUCT_VARIANT_PRODUCT_ID 
	AND PV.[IS_ACTIVE] = 1 
ORDER BY PV.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 