SELECT OI.[ID] AS ORDER_ITEM_ID,
	OI.[QUANTITY] AS ORDER_ITEM_QUANTITY,
	OI.[UNIT_PRICE] AS ORDER_ITEM_UNIT_PRICE,
	P.[TITLE] AS PRODUCT_TITLE 
FROM [ORDER_ITEMS] OI 
	INNER JOIN [PRODUCTS] P 
			ON OI.[PRODUCT_ID] = P.[ID] 
WHERE OI.[IsDeleted] = 0 
	AND P.[IsDeleted] = 0 
	AND OI.[ORDER_ID] = @PRM_ORDER_ITEMS_ORDER_ID 
ORDER BY OI.[ID] 