// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickCode.Demo.SmsManagerModule.Persistence.Contexts;

#nullable disable

namespace QuickCode.Demo.SmsManagerModule.Persistence.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20251016073938_AutoMigration_20251016_073931_451")]
    partial class AutoMigration_20251016_073931_451
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuickCode.Demo.SmsManagerModule.Domain.Entities.CampaignMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignTypeId")
                        .HasColumnType("int")
                        .HasColumnName("CAMPAIGN_TYPE_ID");

                    b.Property<int>("DailyCounter")
                        .HasColumnType("int")
                        .HasColumnName("DAILY_COUNTER");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<string>("GsmNumber")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("GSM_NUMBER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Message")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("MESSAGE");

                    b.Property<DateTime>("MessageDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("MESSAGE_DATE")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("MessageSid")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("MESSAGE_SID");

                    b.Property<int>("SmsSenderId")
                        .HasColumnType("int")
                        .HasColumnName("SMS_SENDER_ID");

                    b.HasKey("Id");

                    b.HasIndex("CampaignTypeId");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("SmsSenderId");

                    b.ToTable("CAMPAIGN_MESSAGES");
                });

            modelBuilder.Entity("QuickCode.Demo.SmsManagerModule.Domain.Entities.CampaignType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NAME");

                    b.Property<string>("Template")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TEMPLATE");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("CAMPAIGN_TYPES");
                });

            modelBuilder.Entity("QuickCode.Demo.SmsManagerModule.Domain.Entities.InfoMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DailyCounter")
                        .HasColumnType("int")
                        .HasColumnName("DAILY_COUNTER");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<string>("GsmNumber")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("GSM_NUMBER");

                    b.Property<int>("InfoTypeId")
                        .HasColumnType("int")
                        .HasColumnName("INFO_TYPE_ID");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Message")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("MESSAGE");

                    b.Property<DateTime>("MessageDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("MESSAGE_DATE")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("MessageSid")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("MESSAGE_SID");

                    b.Property<int>("SmsSenderId")
                        .HasColumnType("int")
                        .HasColumnName("SMS_SENDER_ID");

                    b.HasKey("Id");

                    b.HasIndex("InfoTypeId");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("SmsSenderId");

                    b.ToTable("INFO_MESSAGES");
                });

            modelBuilder.Entity("QuickCode.Demo.SmsManagerModule.Domain.Entities.InfoType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NAME");

                    b.Property<string>("Template")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TEMPLATE");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("INFO_TYPES");
                });

            modelBuilder.Entity("QuickCode.Demo.SmsManagerModule.Domain.Entities.OtpMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DailyCounter")
                        .HasColumnType("int")
                        .HasColumnName("DAILY_COUNTER");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<int>("ExpireSeconds")
                        .HasColumnType("int")
                        .HasColumnName("EXPIRE_SECONDS");

                    b.Property<string>("GsmNumber")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("GSM_NUMBER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Message")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("MESSAGE");

                    b.Property<DateTime>("MessageDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("MESSAGE_DATE")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("MessageSid")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("MESSAGE_SID");

                    b.Property<string>("OtpCode")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("OTP_CODE");

                    b.Property<int>("OtpTypeId")
                        .HasColumnType("int")
                        .HasColumnName("OTP_TYPE_ID");

                    b.Property<int>("SmsSenderId")
                        .HasColumnType("int")
                        .HasColumnName("SMS_SENDER_ID");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("OtpTypeId");

                    b.HasIndex("SmsSenderId");

                    b.ToTable("OTP_MESSAGES");
                });

            modelBuilder.Entity("QuickCode.Demo.SmsManagerModule.Domain.Entities.OtpType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NAME");

                    b.Property<string>("Template")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TEMPLATE");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("OTP_TYPES");
                });

            modelBuilder.Entity("QuickCode.Demo.SmsManagerModule.Domain.Entities.SmsSender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<string>("GsmNumber")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("GSM_NUMBER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("PROVIDER_NAME");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("SMS_SENDERS");
                });

            modelBuilder.Entity("QuickCode.Demo.SmsManagerModule.Domain.Entities.CampaignMessage", b =>
                {
                    b.HasOne("QuickCode.Demo.SmsManagerModule.Domain.Entities.CampaignType", "CampaignType")
                        .WithMany("CampaignMessages")
                        .HasForeignKey("CampaignTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickCode.Demo.SmsManagerModule.Domain.Entities.SmsSender", "SmsSender")
                        .WithMany("CampaignMessages")
                        .HasForeignKey("SmsSenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CampaignType");

                    b.Navigation("SmsSender");
                });

            modelBuilder.Entity("QuickCode.Demo.SmsManagerModule.Domain.Entities.InfoMessage", b =>
                {
                    b.HasOne("QuickCode.Demo.SmsManagerModule.Domain.Entities.InfoType", "InfoType")
                        .WithMany("InfoMessages")
                        .HasForeignKey("InfoTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickCode.Demo.SmsManagerModule.Domain.Entities.SmsSender", "SmsSender")
                        .WithMany("InfoMessages")
                        .HasForeignKey("SmsSenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InfoType");

                    b.Navigation("SmsSender");
                });

            modelBuilder.Entity("QuickCode.Demo.SmsManagerModule.Domain.Entities.OtpMessage", b =>
                {
                    b.HasOne("QuickCode.Demo.SmsManagerModule.Domain.Entities.OtpType", "OtpType")
                        .WithMany("OtpMessages")
                        .HasForeignKey("OtpTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickCode.Demo.SmsManagerModule.Domain.Entities.SmsSender", "SmsSender")
                        .WithMany("OtpMessages")
                        .HasForeignKey("SmsSenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OtpType");

                    b.Navigation("SmsSender");
                });

            modelBuilder.Entity("QuickCode.Demo.SmsManagerModule.Domain.Entities.CampaignType", b =>
                {
                    b.Navigation("CampaignMessages");
                });

            modelBuilder.Entity("QuickCode.Demo.SmsManagerModule.Domain.Entities.InfoType", b =>
                {
                    b.Navigation("InfoMessages");
                });

            modelBuilder.Entity("QuickCode.Demo.SmsManagerModule.Domain.Entities.OtpType", b =>
                {
                    b.Navigation("OtpMessages");
                });

            modelBuilder.Entity("QuickCode.Demo.SmsManagerModule.Domain.Entities.SmsSender", b =>
                {
                    b.Navigation("CampaignMessages");

                    b.Navigation("InfoMessages");

                    b.Navigation("OtpMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
