SELECT AFP.[ID], AFP.[SITE_ID], AFP.[APARTMENT_ID], AFP.[YEAR_ID], AFP.[MONTH_ID], AFP.[FEE_AMOUNT], AFP.[IS_ACTIVE] 
FROM [APARTMENT_FEE_PLANS] AFP 
	INNER JOIN [APARTMENTS] A 
			ON AFP.[APARTMENT_ID] = A.[ID] 
WHERE AFP.[IsDeleted] = 0 
	AND A.[IsDeleted] = 0 
	AND AFP.[ID] = @PRM_APARTMENT_FEE_PLANS_ID 
	AND A.[ID] = @PRM_APARTMENTS_ID 
ORDER BY AFP.[ID] 