SELECT F.[ID], F.[APARTMENT_ID], F.[SITE_ID], F.[FLAT_NUMBER], F.[FLOOR], F.[SQUARE_METERS], F.[ROOM_COUNT], F.[IS_ACTIVE], F.[CREATED_DATE] 
FROM [FLATS] F 
	INNER JOIN [APARTMENTS] A 
			ON F.[APARTMENT_ID] = A.[ID] 
WHERE F.[IsDeleted] = 0 
	AND A.[IsDeleted] = 0 
	AND A.[ID] = @PRM_APARTMENTS_ID 
ORDER BY F.[ID] 