SELECT FEI.[ID], FEI.[SITE_ID], FEI.[APARTMENT_ID], FEI.[FLAT_ID], FEI.[EXPENSE_ID], FEI.[EXPENSE_INSTALLMENT_ID], FEI.[FLAT_INSTALLMENT_NUMBER], FEI.[TOTAL_FLAT_INSTALLMENTS], FEI.[FLAT_INSTALLMENT_AMOUNT], FEI.[DUE_DATE], FEI.[PAID], FEI.[PAID_AT], FEI.[PAYMENT_TYPE_ID], FEI.[CREATED_DATE] 
FROM [FLAT_EXPENSE_INSTALLMENTS] FEI 
	INNER JOIN [APARTMENTS] A 
			ON FEI.[APARTMENT_ID] = A.[ID] 
WHERE FEI.[IsDeleted] = 0 
	AND A.[IsDeleted] = 0 
	AND FEI.[ID] = @PRM_FLAT_EXPENSE_INSTALLMENTS_ID 
	AND A.[ID] = @PRM_APARTMENTS_ID 
ORDER BY FEI.[ID] 