SELECT FC.[ID], FC.[FLAT_ID], FC.[CONTACT_ID], FC.[RELATIONSHIP_TYPE], FC.[START_DATE], FC.[END_DATE], FC.[IS_ACTIVE], FC.[CREATED_DATE] 
FROM [FLAT_CONTACTS] FC 
	INNER JOIN [CONTACTS] C 
			ON FC.[CONTACT_ID] = C.[ID] 
WHERE FC.[IsDeleted] = 0 
	AND C.[IsDeleted] = 0 
	AND C.[ID] = @PRM_CONTACTS_ID 
ORDER BY FC.[ID] 