SELECT SM.[ID], SM.[SITE_ID], SM.[CONTACT_ID], SM.[START_DATE], SM.[END_DATE], SM.[IS_ACTIVE], SM.[CREATED_DATE] 
FROM [SITE_MANAGERS] SM 
	INNER JOIN [CONTACTS] C 
			ON SM.[CONTACT_ID] = C.[ID] 
WHERE SM.[IsDeleted] = 0 
	AND C.[IsDeleted] = 0 
	AND C.[ID] = @PRM_CONTACTS_ID 
ORDER BY SM.[ID] 