SELECT
    [ID],
    [COMMISSION_MODEL_ID],
    [SCOPE],
    [SCOPE_ID],
    [COMMISSION_TYPE],
    [PERCENTAGE_RATE],
    [FIXED_AMOUNT],
    [IS_ACTIVE]
FROM [dbo].[COMMISSION_RULES]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;