UPDATE [dbo].[COMMISSION_RULES]
SET
    [COMMISSION_MODEL_ID] = @PRM_COMMISSION_RULE_COMMISSION_MODEL_ID,
    [SCOPE] = @PRM_COMMISSION_RULE_SCOPE,
    [SCOPE_ID] = @PRM_COMMISSION_RULE_SCOPE_ID,
    [COMMISSION_TYPE] = @PRM_COMMISSION_RULE_COMMISSION_TYPE,
    [PERCENTAGE_RATE] = @PRM_COMMISSION_RULE_PERCENTAGE_RATE,
    [FIXED_AMOUNT] = @PRM_COMMISSION_RULE_FIXED_AMOUNT,
    [IS_ACTIVE] = @PRM_COMMISSION_RULE_IS_ACTIVE
WHERE
    [ID] = @PRM_COMMISSION_RULE_ID
    AND [IsDeleted] = 0;