//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.UserManagerModule.Domain.Entities;
using QuickCode.Demo.UserManagerModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Common.Extensions;
using QuickCode.Demo.UserManagerModule.Persistence.Contexts;
using QuickCode.Demo.UserManagerModule.Application.Dtos;

namespace QuickCode.Demo.UserManagerModule.Persistence.Repositories
{
    public partial class PortalPermissionTypesRepository : IPortalPermissionTypesRepository
    {
        private readonly WriteDbContext _writeContext;
        private readonly ReadDbContext _readContext;
        private readonly ILogger<PortalPermissionTypesRepository> _logger;
        public PortalPermissionTypesRepository(ILogger<PortalPermissionTypesRepository> logger, WriteDbContext writeContext, ReadDbContext readContext)
        {
            _writeContext = writeContext;
            _readContext = readContext;
            _logger = logger;
        }

        public async Task<RepoResponse<PortalPermissionTypes>> InsertAsync(PortalPermissionTypes value)
        {
            try
            {
                await _writeContext.PortalPermissionTypes.AddAsync(value);
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<PortalPermissionTypes>(value, "Success");
            }
            catch (Exception ex)
            {
                return _logger.LogExceptionAndCreateResponse<PortalPermissionTypes>(ex, "PortalPermissionTypes", "Insert");
            }
        }

        public async Task<RepoResponse<bool>> UpdateAsync(PortalPermissionTypes value)
        {
            try
            {
                _writeContext.Set<PortalPermissionTypes>().Update(value);
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<bool>(true, "Success");
            }
            catch (Exception ex)
            {
                return _logger.LogExceptionAndCreateResponse<bool>(ex, "PortalPermissionTypes", "Update");
            }
        }

        public async Task<RepoResponse<bool>> DeleteAsync(PortalPermissionTypes value)
        {
            try
            {
                _writeContext.PortalPermissionTypes.Remove(value);
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<bool>(true, "Success");
            }
            catch (Exception ex)
            {
                return _logger.LogExceptionAndCreateResponse<bool>(ex, "PortalPermissionTypes", "Delete");
            }
        }

        public async Task<RepoResponse<PortalPermissionTypes>> GetByPkAsync(int id)
        {
            try
            {
                var result =
                    from portal_permission_types in _readContext.PortalPermissionTypes
                    where portal_permission_types.Id.Equals(id)select portal_permission_types;
                var response = await result.FirstOrDefaultAsync();
                return response == null ? new RepoResponse<PortalPermissionTypes>
                {
                    Code = 404,
                    Message = "Not found in PortalPermissionTypes"
                }

                : new RepoResponse<PortalPermissionTypes>(response, "Success");
            }
            catch (Exception ex)
            {
                return _logger.LogExceptionAndCreateResponse<PortalPermissionTypes>(ex, "PortalPermissionTypes", "GetByPk");
            }
        }

        public async Task<RepoResponse<List<PortalPermissionTypes>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            try
            {
                if (pageNumber.HasValue && pageNumber < 1)
                {
                    return new RepoResponse<List<PortalPermissionTypes>>
                    {
                        Code = 404,
                        Message = "Page Number must be greater than 1"
                    };
                }

                var query = _readContext.PortalPermissionTypes.AsQueryable();
                if (pageNumber.HasValue && pageSize.HasValue)
                {
                    query = query.Skip((pageNumber.Value - 1) * pageSize.Value).Take(pageSize.Value);
                }

                return new RepoResponse<List<PortalPermissionTypes>>(await query.ToListAsync(), "Success");
            }
            catch (Exception ex)
            {
                return _logger.LogExceptionAndCreateResponse<List<PortalPermissionTypes>>(ex, "PortalPermissionTypes", "List");
            }
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            try
            {
                return new RepoResponse<int>(await _readContext.PortalPermissionTypes.CountAsync(), "Success");
            }
            catch (Exception ex)
            {
                return _logger.LogExceptionAndCreateResponse<int>(ex, "PortalPermissionTypes", "Count");
            }
        }

        public async Task<RepoResponse<List<PortalPermissionTypesPortalPermissionGroups_RESTResponseDto>>> PortalPermissionTypesPortalPermissionGroups_RESTAsync(int portalPermissionTypesId)
        {
            try
            {
                var queryableResult =
                    from portal_permission_groups in _readContext.PortalPermissionGroups
                    join portal_permission_types in _readContext.PortalPermissionTypes on portal_permission_groups.PortalPermissionTypeId equals portal_permission_types.Id
                    where portal_permission_types.Id.Equals(portalPermissionTypesId)select new PortalPermissionTypesPortalPermissionGroups_RESTResponseDto()
                    {
                        Id = portal_permission_groups.Id,
                        PortalPermissionId = portal_permission_groups.PortalPermissionId,
                        PermissionGroupId = portal_permission_groups.PermissionGroupId,
                        PortalPermissionTypeId = portal_permission_groups.PortalPermissionTypeId
                    };
                var result = await queryableResult.ToListAsync();
                return new RepoResponse<List<PortalPermissionTypesPortalPermissionGroups_RESTResponseDto>>(result, "Success");
            }
            catch (Exception ex)
            {
                return _logger.LogExceptionAndCreateResponse<List<PortalPermissionTypesPortalPermissionGroups_RESTResponseDto>>(ex, "PortalPermissionTypes", "PortalPermissionTypesPortalPermissionGroups_REST");
            }
        }

        public async Task<RepoResponse<PortalPermissionTypesPortalPermissionGroups_KEY_RESTResponseDto>> PortalPermissionTypesPortalPermissionGroups_KEY_RESTAsync(int portalPermissionTypesId, int portalPermissionGroupsId)
        {
            try
            {
                var returnValue = new RepoResponse<PortalPermissionTypesPortalPermissionGroups_KEY_RESTResponseDto>();
                var queryableResult =
                    from portal_permission_groups in _readContext.PortalPermissionGroups
                    join portal_permission_types in _readContext.PortalPermissionTypes on portal_permission_groups.PortalPermissionTypeId equals portal_permission_types.Id
                    where portal_permission_types.Id.Equals(portalPermissionTypesId) && portal_permission_groups.Id.Equals(portalPermissionGroupsId)select new PortalPermissionTypesPortalPermissionGroups_KEY_RESTResponseDto()
                    {
                        Id = portal_permission_groups.Id,
                        PortalPermissionId = portal_permission_groups.PortalPermissionId,
                        PermissionGroupId = portal_permission_groups.PermissionGroupId,
                        PortalPermissionTypeId = portal_permission_groups.PortalPermissionTypeId
                    };
                var result = await queryableResult.FirstOrDefaultAsync();
                if (result == null)
                {
                    returnValue.Code = 404;
                    returnValue.Message = $"Not found in PortalPermissionTypes";
                }
                else
                {
                    returnValue.Value = result;
                }

                return returnValue;
            }
            catch (Exception ex)
            {
                return _logger.LogExceptionAndCreateResponse<PortalPermissionTypesPortalPermissionGroups_KEY_RESTResponseDto>(ex, "PortalPermissionTypes", "PortalPermissionTypesPortalPermissionGroups_KEY_REST");
            }
        }
    }
}