//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.UserManagerModule.Domain.Entities;
using QuickCode.Demo.UserManagerModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Common;
using QuickCode.Demo.Common.Extensions;
using QuickCode.Demo.UserManagerModule.Persistence.Contexts;
using QuickCode.Demo.UserManagerModule.Application.Dtos;
using QuickCode.Demo.UserManagerModule.Application.Mappings;

namespace QuickCode.Demo.UserManagerModule.Persistence.Repositories
{
    public partial class TopicWorkflowsRepository : BaseRepository, ITopicWorkflowsRepository
    {
        private readonly WriteDbContext _writeContext;
        private readonly ReadDbContext _readContext;
        public TopicWorkflowsRepository(ILogger<TopicWorkflowsRepository> logger, WriteDbContext writeContext, ReadDbContext readContext) : base(logger, "TopicWorkflows")
        {
            _writeContext = writeContext;
            _readContext = readContext;
        }

        public async Task<RepoResponse<TopicWorkflowsDto>> InsertAsync(TopicWorkflowsDto value)
        {
            return await ExecuteWithExceptionHandling("Insert", async () =>
            {
                await _writeContext.TopicWorkflows.AddAsync(value.ToModel());
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<TopicWorkflowsDto>(value, "Not Defined");
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(TopicWorkflowsDto value)
        {
            return await ExecuteWithExceptionHandling("Update", async () =>
            {
                _writeContext.Set<TopicWorkflows>().Update(value.ToModel());
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<bool>(true, "Success");
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(TopicWorkflowsDto value)
        {
            return await ExecuteWithExceptionHandling("Delete", async () =>
            {
                _writeContext.TopicWorkflows.Remove(value.ToModel());
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<bool>(true, "Success");
            });
        }

        public async Task<RepoResponse<TopicWorkflowsDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling("GetByPk", async () =>
            {
                var result =
                    from topic_workflows in _readContext.TopicWorkflows
                    where topic_workflows.Id.Equals(id)
                    select topic_workflows;
                var response = await result.FirstOrDefaultAsync();
                return response == null ? new RepoResponse<TopicWorkflowsDto>
                {
                    Code = 404,
                    Message = "Not found in TopicWorkflows"
                }

                : new RepoResponse<TopicWorkflowsDto>(response.ToDto(), "Success");
            });
        }

        public async Task<RepoResponse<List<TopicWorkflowsDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            const int MinPageNumber = 1;
            return await ExecuteWithExceptionHandling("Select", async () =>
            {
                if (pageNumber.HasValue && pageNumber < MinPageNumber)
                {
                    return new RepoResponse<List<TopicWorkflowsDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {MinPageNumber}"};
                }

                var query = _readContext.TopicWorkflows.AsQueryable();
                if (pageNumber.HasValue && pageSize.HasValue)
                {
                    query = ApplyPagination(query, pageNumber.Value, pageSize.Value);
                }

                var result = await query.ToListAsync();
                return new RepoResponse<List<TopicWorkflowsDto>>(result.ToDto(), "Success");
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling("Count", async () =>
            {
                return new RepoResponse<int>(await _readContext.TopicWorkflows.CountAsync(), "Success");
            });
        }

        public async Task<RepoResponse<List<TopicWorkflowsGetWorkflowsResponseDto>>> TopicWorkflowsGetWorkflowsAsync(string topicWorkflowsKafkaEventsTopicName)
        {
            return await ExecuteWithExceptionHandling("TopicWorkflowsGetWorkflows", async () =>
            {
                var queryableResult =
                    from topic_workflows in _readContext.TopicWorkflows
                    where topic_workflows.KafkaEventsTopicName.Equals(topicWorkflowsKafkaEventsTopicName)
                    select new TopicWorkflowsGetWorkflowsResponseDto()
                    {
                        Id = topic_workflows.Id,
                        KafkaEventsTopicName = topic_workflows.KafkaEventsTopicName,
                        WorkflowContent = topic_workflows.WorkflowContent
                    };
                var result = await queryableResult.ToListAsync();
                return new RepoResponse<List<TopicWorkflowsGetWorkflowsResponseDto>>(result, "Success");
            });
        }

        public async Task<RepoResponse<List<TopicWorkflowsGetTopicWorkflowsResponseDto>>> TopicWorkflowsGetTopicWorkflowsAsync(string kafkaEventsTopicName, string apiMethodDefinitionsHttpMethod)
        {
            return await ExecuteWithExceptionHandling("TopicWorkflowsGetTopicWorkflows", async () =>
            {
                var queryableResult =
                    from topic_workflows in _readContext.TopicWorkflows
                    join kafka_events in _readContext.KafkaEvents on topic_workflows.KafkaEventsTopicName equals kafka_events.TopicName
                    join api_method_definitions in _readContext.ApiMethodDefinitions on kafka_events.ApiMethodDefinitionId equals api_method_definitions.Id
                    where kafka_events.TopicName.Equals(kafkaEventsTopicName) && kafka_events.IsActive.Equals(true) && api_method_definitions.HttpMethod.Equals(apiMethodDefinitionsHttpMethod)
                    select new TopicWorkflowsGetTopicWorkflowsResponseDto()
                    {
                        Id = topic_workflows.Id,
                        KafkaEventsTopicName = topic_workflows.KafkaEventsTopicName,
                        WorkflowContent = topic_workflows.WorkflowContent
                    };
                var result = await queryableResult.ToListAsync();
                return new RepoResponse<List<TopicWorkflowsGetTopicWorkflowsResponseDto>>(result, "Success");
            });
        }
    }
}