SELECT
    [ID],
    [SELLER_ID],
    [REVIEWER_ID],
    [RATING],
    [COMMENT],
    [REVIEW_DATE]
FROM [dbo].[SELLER_PERFORMANCE_REVIEWS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;