UPDATE [dbo].[SELLER_PERFORMANCE_REVIEWS]
SET
    [SELLER_ID] = @PRM_SELLER_PERFORMANCE_REVIEW_SELLER_ID,
    [REVIEWER_ID] = @PRM_SELLER_PERFORMANCE_REVIEW_REVIEWER_ID,
    [RATING] = @PRM_SELLER_PERFORMANCE_REVIEW_RATING,
    [COMMENT] = @PRM_SELLER_PERFORMANCE_REVIEW_COMMENT,
    [REVIEW_DATE] = @PRM_SELLER_PERFORMANCE_REVIEW_REVIEW_DATE
WHERE
    [ID] = @PRM_SELLER_PERFORMANCE_REVIEW_ID
    AND [IsDeleted] = 0;