SELECT
    [ID],
    [SELLER_ID],
    [REVIEWER_ID],
    [RATING],
    [COMMENT],
    [REVIEW_DATE]
FROM [dbo].[SELLER_PERFORMANCE_REVIEWS]
WHERE
    [ID] = @PRM_SELLER_PERFORMANCE_REVIEW_ID
    AND [IsDeleted] = 0;