SELECT
    [ID],
    [NAME],
    [MIN_SALES_VOLUME],
    [BENEFITS_DESCRIPTION]
FROM [dbo].[SELLER_TIERS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;