INSERT INTO [dbo].[SELLER_TIERS] (
    [NAME],
    [MIN_SALES_VOLUME],
    [BENEFITS_DESCRIPTION]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_SELLER_TIER_NAME,
    @PRM_SELLER_TIER_MIN_SALES_VOLUME,
    @PRM_SELLER_TIER_BENEFITS_DESCRIPTION
    );