UPDATE [dbo].[SELLER_TIERS]
SET
    [NAME] = @PRM_SELLER_TIER_NAME,
    [MIN_SALES_VOLUME] = @PRM_SELLER_TIER_MIN_SALES_VOLUME,
    [BENEFITS_DESCRIPTION] = @PRM_SELLER_TIER_BENEFITS_DESCRIPTION
WHERE
    [ID] = @PRM_SELLER_TIER_ID
    AND [IsDeleted] = 0;