SELECT U.[ID], U.[EMAIL], U.[NAME], U.[CREATED_AT], U.[IS_NEW], U.[COMPANY_ID] 
FROM [USERS] U 
	INNER JOIN [COMPANIES] C 
			ON U.[COMPANY_ID] = C.[ID] 
WHERE U.[IsDeleted] = 0 
	AND C.[IsDeleted] = 0 
	AND U.[ID] = @PRM_USERS_ID 
	AND C.[ID] = @PRM_COMPANIES_ID 
ORDER BY U.[ID] 