//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.TaskManagerModule.Domain.Entities;
using QuickCode.Demo.TaskManagerModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Common;
using QuickCode.Demo.Common.Extensions;
using QuickCode.Demo.Common.Helpers;
using QuickCode.Demo.TaskManagerModule.Persistence.Contexts;
using QuickCode.Demo.TaskManagerModule.Application.Dtos.Task;
using QuickCode.Demo.TaskManagerModule.Application.Mappings;
using QuickCode.Demo.TaskManagerModule.Persistence.Sql;
using QuickCode.Demo.TaskManagerModule.Domain.Enums;

namespace QuickCode.Demo.TaskManagerModule.Persistence.Repositories
{
    public partial class TaskRepository : BaseRepository, ITaskRepository
    {
        public async Task<RepoResponse<int>> UpdateTaskStatusAsync(int tasksId, UpdateTaskStatusRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Task", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Task.Command.UpdateTaskStatus);
                var parameters = new
                {
                    TASKS_STATUS = updateRequest.TasksStatus,
                    PRM_TASKS_ID = tasksId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }

        public async Task<RepoResponse<int>> UpdateTaskPriorityAsync(int tasksId, UpdateTaskPriorityRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Task", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Task.Command.UpdateTaskPriority);
                var parameters = new
                {
                    TASKS_PRIORITY = updateRequest.TasksPriority,
                    PRM_TASKS_ID = tasksId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }

        public async Task<RepoResponse<int>> DeleteTaskAsync(int tasksId)
        {
            return await ExecuteWithExceptionHandling("Task", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Task.Command.DeleteTask);
                var parameters = new
                {
                    PRM_TASKS_ID = tasksId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}