//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.ApartmentManageModule.Domain.Entities;
using QuickCode.Demo.ApartmentManageModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Common;
using QuickCode.Demo.Common.Extensions;
using QuickCode.Demo.Common.Helpers;
using QuickCode.Demo.ApartmentManageModule.Persistence.Contexts;
using QuickCode.Demo.ApartmentManageModule.Application.Dtos;
using QuickCode.Demo.ApartmentManageModule.Application.Mappings;
using QuickCode.Demo.ApartmentManageModule.Application.Sql;
using QuickCode.Demo.ApartmentManageModule.Domain.Enums;

namespace QuickCode.Demo.ApartmentManageModule.Persistence.Repositories
{
    public partial class CommonExpensesRepository : BaseRepository, ICommonExpensesRepository
    {
        public async Task<RepoResponse<List<CommonExpensesGetExpensesByApartmentMonthResponseDto>>> CommonExpensesGetExpensesByApartmentMonthAsync(int commonExpensesSiteId, int commonExpensesApartmentId, int commonExpensesYearId, int commonExpensesMonthId)
        {
            return await ExecuteWithExceptionHandling("CommonExpensesGetExpensesByApartmentMonth", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommonExpenses.Query.GetExpensesByApartmentMonth);
                var parameters = new
                {
                    PRM_COMMON_EXPENSES_SITE_ID = commonExpensesSiteId,
                    PRM_COMMON_EXPENSES_APARTMENT_ID = commonExpensesApartmentId,
                    PRM_COMMON_EXPENSES_YEAR_ID = commonExpensesYearId,
                    PRM_COMMON_EXPENSES_MONTH_ID = commonExpensesMonthId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<CommonExpensesGetExpensesByApartmentMonthResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in CommonExpenses");
            });
        }

        public async Task<RepoResponse<List<CommonExpensesGetExpensesBySiteResponseDto>>> CommonExpensesGetExpensesBySiteAsync(int commonExpensesSiteId)
        {
            return await ExecuteWithExceptionHandling("CommonExpensesGetExpensesBySite", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommonExpenses.Query.GetExpensesBySite);
                var parameters = new
                {
                    PRM_COMMON_EXPENSES_SITE_ID = commonExpensesSiteId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<CommonExpensesGetExpensesBySiteResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in CommonExpenses");
            });
        }

        public async Task<RepoResponse<List<CommonExpensesGetExpensesSummaryByYearResponseDto>>> CommonExpensesGetExpensesSummaryByYearAsync(int commonExpensesSiteId, int commonExpensesApartmentId, int commonExpensesYearId)
        {
            return await ExecuteWithExceptionHandling("CommonExpensesGetExpensesSummaryByYear", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommonExpenses.Query.GetExpensesSummaryByYear);
                var parameters = new
                {
                    PRM_COMMON_EXPENSES_SITE_ID = commonExpensesSiteId,
                    PRM_COMMON_EXPENSES_APARTMENT_ID = commonExpensesApartmentId,
                    PRM_COMMON_EXPENSES_YEAR_ID = commonExpensesYearId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<CommonExpensesGetExpensesSummaryByYearResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in CommonExpenses");
            });
        }

        public async Task<RepoResponse<List<CommonExpensesGetExpensesByTypeResponseDto>>> CommonExpensesGetExpensesByTypeAsync(int commonExpensesSiteId, int commonExpensesApartmentId, int commonExpensesExpenseTypeId, int commonExpensesYearId, int commonExpensesMonthId)
        {
            return await ExecuteWithExceptionHandling("CommonExpensesGetExpensesByType", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommonExpenses.Query.GetExpensesByType);
                var parameters = new
                {
                    PRM_COMMON_EXPENSES_SITE_ID = commonExpensesSiteId,
                    PRM_COMMON_EXPENSES_APARTMENT_ID = commonExpensesApartmentId,
                    PRM_COMMON_EXPENSES_EXPENSE_TYPE_ID = commonExpensesExpenseTypeId,
                    PRM_COMMON_EXPENSES_YEAR_ID = commonExpensesYearId,
                    PRM_COMMON_EXPENSES_MONTH_ID = commonExpensesMonthId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<CommonExpensesGetExpensesByTypeResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in CommonExpenses");
            });
        }

        public async Task<RepoResponse<List<CommonExpensesGetUnpaidExpensesByApartmentResponseDto>>> CommonExpensesGetUnpaidExpensesByApartmentAsync(int commonExpensesApartmentId, bool commonExpensesPaid)
        {
            return await ExecuteWithExceptionHandling("CommonExpensesGetUnpaidExpensesByApartment", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommonExpenses.Query.GetUnpaidExpensesByApartment);
                var parameters = new
                {
                    PRM_COMMON_EXPENSES_APARTMENT_ID = commonExpensesApartmentId,
                    PRM_COMMON_EXPENSES_PAID = commonExpensesPaid
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<CommonExpensesGetUnpaidExpensesByApartmentResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in CommonExpenses");
            });
        }

        public async Task<RepoResponse<long>> CommonExpensesGetExpensesCountByApartmentAsync(int commonExpensesApartmentId)
        {
            return await ExecuteWithExceptionHandling("CommonExpensesGetExpensesCountByApartment", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommonExpenses.Query.GetExpensesCountByApartment);
                var parameters = new
                {
                    PRM_COMMON_EXPENSES_APARTMENT_ID = commonExpensesApartmentId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var result = await connection.ExecuteScalarAsync<long>(sql, parameters);
                return new RepoResponse<long>(result, "Success");
            });
        }

        public async Task<RepoResponse<CommonExpensesGetTotalExpenseAmountByApartmentResponseDto>> CommonExpensesGetTotalExpenseAmountByApartmentAsync(int commonExpensesApartmentId)
        {
            return await ExecuteWithExceptionHandling("CommonExpensesGetTotalExpenseAmountByApartment", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommonExpenses.Query.GetTotalExpenseAmountByApartment);
                var parameters = new
                {
                    PRM_COMMON_EXPENSES_APARTMENT_ID = commonExpensesApartmentId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<CommonExpensesGetTotalExpenseAmountByApartmentResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in CommonExpenses");
            });
        }

        public async Task<RepoResponse<List<CommonExpensesGetFlatPaymentsForCommonExpensesResponseDto>>> CommonExpensesGetFlatPaymentsForCommonExpensesAsync(int commonExpensesId)
        {
            return await ExecuteWithExceptionHandling("CommonExpensesGetFlatPaymentsForCommonExpenses", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommonExpenses.Query.GetFlatPaymentsForCommonExpenses);
                var parameters = new
                {
                    PRM_COMMON_EXPENSES_ID = commonExpensesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<CommonExpensesGetFlatPaymentsForCommonExpensesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in CommonExpenses");
            });
        }

        public async Task<RepoResponse<CommonExpensesGetFlatPaymentsForCommonExpensesResponseDto>> CommonExpensesGetFlatPaymentsForCommonExpensesDetailsAsync(int commonExpensesId, int flatPaymentsId)
        {
            return await ExecuteWithExceptionHandling("CommonExpensesGetFlatPaymentsForCommonExpensesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommonExpenses.Query.GetFlatPaymentsForCommonExpensesDetails);
                var parameters = new
                {
                    PRM_FLAT_PAYMENTS_ID = flatPaymentsId,
                    PRM_COMMON_EXPENSES_ID = commonExpensesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<CommonExpensesGetFlatPaymentsForCommonExpensesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in CommonExpenses");
            });
        }

        public async Task<RepoResponse<List<CommonExpensesGetExpenseInstallmentsForCommonExpensesResponseDto>>> CommonExpensesGetExpenseInstallmentsForCommonExpensesAsync(int commonExpensesId)
        {
            return await ExecuteWithExceptionHandling("CommonExpensesGetExpenseInstallmentsForCommonExpenses", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommonExpenses.Query.GetExpenseInstallmentsForCommonExpenses);
                var parameters = new
                {
                    PRM_COMMON_EXPENSES_ID = commonExpensesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<CommonExpensesGetExpenseInstallmentsForCommonExpensesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in CommonExpenses");
            });
        }

        public async Task<RepoResponse<CommonExpensesGetExpenseInstallmentsForCommonExpensesResponseDto>> CommonExpensesGetExpenseInstallmentsForCommonExpensesDetailsAsync(int commonExpensesId, int expenseInstallmentsId)
        {
            return await ExecuteWithExceptionHandling("CommonExpensesGetExpenseInstallmentsForCommonExpensesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommonExpenses.Query.GetExpenseInstallmentsForCommonExpensesDetails);
                var parameters = new
                {
                    PRM_EXPENSE_INSTALLMENTS_ID = expenseInstallmentsId,
                    PRM_COMMON_EXPENSES_ID = commonExpensesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<CommonExpensesGetExpenseInstallmentsForCommonExpensesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in CommonExpenses");
            });
        }

        public async Task<RepoResponse<List<CommonExpensesGetFlatExpenseInstallmentsForCommonExpensesResponseDto>>> CommonExpensesGetFlatExpenseInstallmentsForCommonExpensesAsync(int commonExpensesId)
        {
            return await ExecuteWithExceptionHandling("CommonExpensesGetFlatExpenseInstallmentsForCommonExpenses", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommonExpenses.Query.GetFlatExpenseInstallmentsForCommonExpenses);
                var parameters = new
                {
                    PRM_COMMON_EXPENSES_ID = commonExpensesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<CommonExpensesGetFlatExpenseInstallmentsForCommonExpensesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in CommonExpenses");
            });
        }

        public async Task<RepoResponse<CommonExpensesGetFlatExpenseInstallmentsForCommonExpensesResponseDto>> CommonExpensesGetFlatExpenseInstallmentsForCommonExpensesDetailsAsync(int commonExpensesId, int flatExpenseInstallmentsId)
        {
            return await ExecuteWithExceptionHandling("CommonExpensesGetFlatExpenseInstallmentsForCommonExpensesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommonExpenses.Query.GetFlatExpenseInstallmentsForCommonExpensesDetails);
                var parameters = new
                {
                    PRM_FLAT_EXPENSE_INSTALLMENTS_ID = flatExpenseInstallmentsId,
                    PRM_COMMON_EXPENSES_ID = commonExpensesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<CommonExpensesGetFlatExpenseInstallmentsForCommonExpensesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in CommonExpenses");
            });
        }
    }
}