//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.ApartmentManageModule.Domain.Entities;
using QuickCode.Demo.ApartmentManageModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Common;
using QuickCode.Demo.Common.Extensions;
using QuickCode.Demo.Common.Helpers;
using QuickCode.Demo.ApartmentManageModule.Persistence.Contexts;
using QuickCode.Demo.ApartmentManageModule.Application.Dtos;
using QuickCode.Demo.ApartmentManageModule.Application.Mappings;
using QuickCode.Demo.ApartmentManageModule.Application.Sql;
using QuickCode.Demo.ApartmentManageModule.Domain.Enums;

namespace QuickCode.Demo.ApartmentManageModule.Persistence.Repositories
{
    public partial class PaymentMonthsRepository : BaseRepository, IPaymentMonthsRepository
    {
        public async Task<RepoResponse<List<PaymentMonthsGetAllMonthsResponseDto>>> PaymentMonthsGetAllMonthsAsync()
        {
            return await ExecuteWithExceptionHandling("PaymentMonthsGetAllMonths", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PaymentMonths.Query.GetAllMonths);
                var parameters = new
                {
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<PaymentMonthsGetAllMonthsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in PaymentMonths");
            });
        }

        public async Task<RepoResponse<List<PaymentMonthsGetApartmentFeePlansForPaymentMonthsResponseDto>>> PaymentMonthsGetApartmentFeePlansForPaymentMonthsAsync(int paymentMonthsId)
        {
            return await ExecuteWithExceptionHandling("PaymentMonthsGetApartmentFeePlansForPaymentMonths", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PaymentMonths.Query.GetApartmentFeePlansForPaymentMonths);
                var parameters = new
                {
                    PRM_PAYMENT_MONTHS_ID = paymentMonthsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<PaymentMonthsGetApartmentFeePlansForPaymentMonthsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in PaymentMonths");
            });
        }

        public async Task<RepoResponse<PaymentMonthsGetApartmentFeePlansForPaymentMonthsResponseDto>> PaymentMonthsGetApartmentFeePlansForPaymentMonthsDetailsAsync(int paymentMonthsId, int apartmentFeePlansId)
        {
            return await ExecuteWithExceptionHandling("PaymentMonthsGetApartmentFeePlansForPaymentMonthsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PaymentMonths.Query.GetApartmentFeePlansForPaymentMonthsDetails);
                var parameters = new
                {
                    PRM_APARTMENT_FEE_PLANS_ID = apartmentFeePlansId,
                    PRM_PAYMENT_MONTHS_ID = paymentMonthsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<PaymentMonthsGetApartmentFeePlansForPaymentMonthsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in PaymentMonths");
            });
        }

        public async Task<RepoResponse<List<PaymentMonthsGetFlatPaymentsForPaymentMonthsResponseDto>>> PaymentMonthsGetFlatPaymentsForPaymentMonthsAsync(int paymentMonthsId)
        {
            return await ExecuteWithExceptionHandling("PaymentMonthsGetFlatPaymentsForPaymentMonths", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PaymentMonths.Query.GetFlatPaymentsForPaymentMonths);
                var parameters = new
                {
                    PRM_PAYMENT_MONTHS_ID = paymentMonthsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<PaymentMonthsGetFlatPaymentsForPaymentMonthsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in PaymentMonths");
            });
        }

        public async Task<RepoResponse<PaymentMonthsGetFlatPaymentsForPaymentMonthsResponseDto>> PaymentMonthsGetFlatPaymentsForPaymentMonthsDetailsAsync(int paymentMonthsId, int flatPaymentsId)
        {
            return await ExecuteWithExceptionHandling("PaymentMonthsGetFlatPaymentsForPaymentMonthsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PaymentMonths.Query.GetFlatPaymentsForPaymentMonthsDetails);
                var parameters = new
                {
                    PRM_FLAT_PAYMENTS_ID = flatPaymentsId,
                    PRM_PAYMENT_MONTHS_ID = paymentMonthsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<PaymentMonthsGetFlatPaymentsForPaymentMonthsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in PaymentMonths");
            });
        }

        public async Task<RepoResponse<List<PaymentMonthsGetCommonExpensesForPaymentMonthsResponseDto>>> PaymentMonthsGetCommonExpensesForPaymentMonthsAsync(int paymentMonthsId)
        {
            return await ExecuteWithExceptionHandling("PaymentMonthsGetCommonExpensesForPaymentMonths", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PaymentMonths.Query.GetCommonExpensesForPaymentMonths);
                var parameters = new
                {
                    PRM_PAYMENT_MONTHS_ID = paymentMonthsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<PaymentMonthsGetCommonExpensesForPaymentMonthsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in PaymentMonths");
            });
        }

        public async Task<RepoResponse<PaymentMonthsGetCommonExpensesForPaymentMonthsResponseDto>> PaymentMonthsGetCommonExpensesForPaymentMonthsDetailsAsync(int paymentMonthsId, int commonExpensesId)
        {
            return await ExecuteWithExceptionHandling("PaymentMonthsGetCommonExpensesForPaymentMonthsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PaymentMonths.Query.GetCommonExpensesForPaymentMonthsDetails);
                var parameters = new
                {
                    PRM_COMMON_EXPENSES_ID = commonExpensesId,
                    PRM_PAYMENT_MONTHS_ID = paymentMonthsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<PaymentMonthsGetCommonExpensesForPaymentMonthsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in PaymentMonths");
            });
        }
    }
}