//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.OrderManagementModule.Application.Dtos.OrderStatusManager;
using OrderStatusManagerEntity = QuickCode.Demo.OrderManagementModule.Domain.Entities.OrderStatusManager;
using QuickCode.Demo.OrderManagementModule.Domain.Enums;

namespace QuickCode.Demo.OrderManagementModule.Application.Mappings
{
    public static class OrderStatusManagerMappings
    {
        public static List<OrderStatusManagerDto> ToDto(this IEnumerable<OrderStatusManagerEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static OrderStatusManagerDto ToDto(this OrderStatusManagerEntity model)
        {
            return new OrderStatusManagerDto
            {
                Id = model.Id,
                OrderId = model.OrderId,
                PreviousStatus = model.PreviousStatus,
                NewStatus = model.NewStatus,
                ChangedByUserId = model.ChangedByUserId,
                ChangeDate = model.ChangeDate,
                Notes = model.Notes
            };
        }

        public static OrderStatusManagerEntity ToEntity(this OrderStatusManagerDto model)
        {
            return new OrderStatusManagerEntity
            {
                Id = model.Id,
                OrderId = model.OrderId,
                PreviousStatus = model.PreviousStatus,
                NewStatus = model.NewStatus,
                ChangedByUserId = model.ChangedByUserId,
                ChangeDate = model.ChangeDate,
                Notes = model.Notes
            };
        }
    }
}