//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.SmsManagerModule.Domain.Enums;

namespace QuickCode.Demo.SmsManagerModule.Application.Dtos.Sender
{
    public record ExistsByPhoneResponseDto
    {
        public int Id { get; init; }
        public string Name { get; init; }
        public string PhoneNumber { get; init; }
        public string ApiUrl { get; init; }
        public string Username { get; init; }
        public string Password { get; init; }
        public bool IsActive { get; init; }
        public int Priority { get; init; }
        public int DailyLimit { get; init; }
    }
}