//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.UserManagerModule.Domain.Entities;
using QuickCode.Demo.UserManagerModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Common;
using QuickCode.Demo.Common.Extensions;
using QuickCode.Demo.Common.Helpers;
using QuickCode.Demo.UserManagerModule.Persistence.Contexts;
using QuickCode.Demo.UserManagerModule.Application.Dtos;
using QuickCode.Demo.UserManagerModule.Application.Mappings;
using QuickCode.Demo.UserManagerModule.Application.Sql;

namespace QuickCode.Demo.UserManagerModule.Persistence.Repositories
{
    public partial class AspNetRolesRepository : BaseRepository, IAspNetRolesRepository
    {
        public async Task<RepoResponse<List<AspNetRolesGetAspNetUserRolesForAspNetRolesResponseDto>>> AspNetRolesGetAspNetUserRolesForAspNetRolesAsync(string aspNetRolesId)
        {
            return await ExecuteWithExceptionHandling("AspNetRolesGetAspNetUserRolesForAspNetRoles", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AspNetRoles.Query.GetAspNetUserRolesForAspNetRoles);
                var parameters = new
                {
                    PRM_AspNetRoles_Id = aspNetRolesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<AspNetRolesGetAspNetUserRolesForAspNetRolesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in AspNetRoles");
            });
        }

        public async Task<RepoResponse<AspNetRolesGetAspNetUserRolesForAspNetRolesResponseDto>> AspNetRolesGetAspNetUserRolesForAspNetRolesDetailsAsync(string aspNetRolesId, string aspNetUserRolesUserId)
        {
            return await ExecuteWithExceptionHandling("AspNetRolesGetAspNetUserRolesForAspNetRolesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AspNetRoles.Query.GetAspNetUserRolesForAspNetRolesDetails);
                var parameters = new
                {
                    PRM_AspNetUserRoles_UserId = aspNetUserRolesUserId,
                    PRM_AspNetRoles_Id = aspNetRolesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<AspNetRolesGetAspNetUserRolesForAspNetRolesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in AspNetRoles");
            });
        }

        public async Task<RepoResponse<List<AspNetRolesGetAspNetRoleClaimsForAspNetRolesResponseDto>>> AspNetRolesGetAspNetRoleClaimsForAspNetRolesAsync(string aspNetRolesId)
        {
            return await ExecuteWithExceptionHandling("AspNetRolesGetAspNetRoleClaimsForAspNetRoles", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AspNetRoles.Query.GetAspNetRoleClaimsForAspNetRoles);
                var parameters = new
                {
                    PRM_AspNetRoles_Id = aspNetRolesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<AspNetRolesGetAspNetRoleClaimsForAspNetRolesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in AspNetRoles");
            });
        }

        public async Task<RepoResponse<AspNetRolesGetAspNetRoleClaimsForAspNetRolesResponseDto>> AspNetRolesGetAspNetRoleClaimsForAspNetRolesDetailsAsync(string aspNetRolesId, int aspNetRoleClaimsId)
        {
            return await ExecuteWithExceptionHandling("AspNetRolesGetAspNetRoleClaimsForAspNetRolesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AspNetRoles.Query.GetAspNetRoleClaimsForAspNetRolesDetails);
                var parameters = new
                {
                    PRM_AspNetRoleClaims_Id = aspNetRoleClaimsId,
                    PRM_AspNetRoles_Id = aspNetRolesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<AspNetRolesGetAspNetRoleClaimsForAspNetRolesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in AspNetRoles");
            });
        }
    }
}