//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.OnlineShopModule.Domain.Entities;
using QuickCode.Demo.OnlineShopModule.Application.Dtos.CartItem;
using System.Threading.Tasks;
using QuickCode.Demo.OnlineShopModule.Domain.Enums;

namespace QuickCode.Demo.OnlineShopModule.Application.Interfaces.Repositories
{
    public partial interface ICartItemRepository : IBaseRepository<CartItemDto>
    {
        Task<RepoResponse<CartItemDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetCartItemsWithTotalResponseDto>>> GetCartItemsWithTotalAsync(int cartItemsCartId);
    }
}