//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Common.Models;
using QuickCode.Demo.OnlineShopModule.Domain.Entities;
using QuickCode.Demo.OnlineShopModule.Application.Dtos.HomePage;
using System.Threading.Tasks;
using QuickCode.Demo.OnlineShopModule.Domain.Enums;

namespace QuickCode.Demo.OnlineShopModule.Application.Interfaces.Repositories
{
    public partial interface IHomePageRepository : IBaseRepository<HomePageDto>
    {
        Task<RepoResponse<HomePageDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetHomePageContentResponseDto>>> GetHomePageContentAsync(string homePagesTitleImageUrl);
        Task<RepoResponse<List<GetHomePageContentGrResponseDto>>> GetHomePageContentGrAsync(string homePagesTitleImageUrl);
    }
}