SELECT
    [ID],
    [ORDER_ID],
    [PREVIOUS_STATUS],
    [NEW_STATUS],
    [CHANGED_BY_USER_ID],
    [CHANGE_DATE],
    [NOTES]
FROM [dbo].[ORDER_STATUS_MANAGERS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;