UPDATE [dbo].[ORDER_STATUS_MANAGERS]
SET
    [ORDER_ID] = @PRM_ORDER_STATUS_MANAGER_ORDER_ID,
    [PREVIOUS_STATUS] = @PRM_ORDER_STATUS_MANAGER_PREVIOUS_STATUS,
    [NEW_STATUS] = @PRM_ORDER_STATUS_MANAGER_NEW_STATUS,
    [CHANGED_BY_USER_ID] = @PRM_ORDER_STATUS_MANAGER_CHANGED_BY_USER_ID,
    [CHANGE_DATE] = @PRM_ORDER_STATUS_MANAGER_CHANGE_DATE,
    [NOTES] = @PRM_ORDER_STATUS_MANAGER_NOTES
WHERE
    [ID] = @PRM_ORDER_STATUS_MANAGER_ID
    AND [IsDeleted] = 0;