INSERT INTO [dbo].[ORDER_STATUS_MANAGERS] (
    [ORDER_ID],
    [PREVIOUS_STATUS],
    [NEW_STATUS],
    [CHANGED_BY_USER_ID],
    [CHANGE_DATE],
    [NOTES]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_ORDER_STATUS_MANAGER_ORDER_ID,
    @PRM_ORDER_STATUS_MANAGER_PREVIOUS_STATUS,
    @PRM_ORDER_STATUS_MANAGER_NEW_STATUS,
    @PRM_ORDER_STATUS_MANAGER_CHANGED_BY_USER_ID,
    @PRM_ORDER_STATUS_MANAGER_CHANGE_DATE,
    @PRM_ORDER_STATUS_MANAGER_NOTES
    );