SELECT PLI.[ID], PLI.[ORDER_ID], PLI.[ITEM_AMOUNT], PLI.[COMMISSION_AMOUNT], PLI.[NET_AMOUNT] 
FROM [PAYOUT_LINE_ITEMS] PLI 
WHERE PLI.[IsDeleted] = 0 
	AND PLI.[PAYOUT_ID] = @PRM_PAYOUT_LINE_ITEM_PAYOUT_ID 
ORDER BY PLI.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 