SELECT CE.[ID], CE.[ORDER_ITEM_ID], CE.[COMMISSION_AMOUNT] 
FROM [COMMISSION_ENTRIES] CE 
WHERE CE.[IsDeleted] = 0 
	AND CE.[ORDER_ID] = @PRM_COMMISSION_ENTRY_ORDER_ID 
ORDER BY CE.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 