SELECT C.[ID], C.[ORDER_ID], C.[COMMISSION_AMOUNT] 
FROM [COMMISSION_ENTRIES] C 
	LEFT JOIN [PAYOUT_PERIODS] P 
			ON 1=1 
WHERE C.[IsDeleted] = 0 
	AND P.[IsDeleted] = 0 
	AND C.[SELLER_ID] = @PRM_COMMISSION_ENTRIES_SELLER_ID 
ORDER BY C.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 