SELECT [CONTACT_ID], [START_DATE], [END_DATE] 
FROM [FLAT_CONTACTS] 
WHERE [IsDeleted] = 0 
	AND [FLAT_ID] = @PRM_FLAT_CONTACTS_FLAT_ID 
	AND [RELATIONSHIP_TYPE] = @PRM_FLAT_CONTACTS_RELATIONSHIP_TYPE 
	AND [IS_ACTIVE] = @PRM_FLAT_CONTACTS_IS_ACTIVE 
ORDER BY [ID] 