SELECT
    [ID],
    [ORDER_ID],
    [ORDER_ITEM_ID],
    [SELLER_ID],
    [COMMISSION_MODEL_ID],
    [COMMISSION_RULE_ID],
    [ITEM_PRICE],
    [COMMISSION_AMOUNT],
    [CALCULATED_DATE]
FROM [dbo].[COMMISSION_ENTRIES]
WHERE
    [ID] = @PRM_COMMISSION_ENTRY_ID
    AND [IsDeleted] = 0;