SELECT
    [ID],
    [ORDER_ID],
    [ORDER_ITEM_ID],
    [SELLER_ID],
    [COMMISSION_MODEL_ID],
    [COMMISSION_RULE_ID],
    [ITEM_PRICE],
    [COMMISSION_AMOUNT],
    [CALCULATED_DATE]
FROM [dbo].[COMMISSION_ENTRIES]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;