INSERT INTO [dbo].[COMMISSION_ENTRIES] (
    [ORDER_ID],
    [ORDER_ITEM_ID],
    [SELLER_ID],
    [COMMISSION_MODEL_ID],
    [COMMISSION_RULE_ID],
    [ITEM_PRICE],
    [COMMISSION_AMOUNT],
    [CALCULATED_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_COMMISSION_ENTRY_ORDER_ID,
    @PRM_COMMISSION_ENTRY_ORDER_ITEM_ID,
    @PRM_COMMISSION_ENTRY_SELLER_ID,
    @PRM_COMMISSION_ENTRY_COMMISSION_MODEL_ID,
    @PRM_COMMISSION_ENTRY_COMMISSION_RULE_ID,
    @PRM_COMMISSION_ENTRY_ITEM_PRICE,
    @PRM_COMMISSION_ENTRY_COMMISSION_AMOUNT,
    @PRM_COMMISSION_ENTRY_CALCULATED_DATE
    );