UPDATE [dbo].[COMMISSION_ENTRIES]
SET
    [ORDER_ID] = @PRM_COMMISSION_ENTRY_ORDER_ID,
    [ORDER_ITEM_ID] = @PRM_COMMISSION_ENTRY_ORDER_ITEM_ID,
    [SELLER_ID] = @PRM_COMMISSION_ENTRY_SELLER_ID,
    [COMMISSION_MODEL_ID] = @PRM_COMMISSION_ENTRY_COMMISSION_MODEL_ID,
    [COMMISSION_RULE_ID] = @PRM_COMMISSION_ENTRY_COMMISSION_RULE_ID,
    [ITEM_PRICE] = @PRM_COMMISSION_ENTRY_ITEM_PRICE,
    [COMMISSION_AMOUNT] = @PRM_COMMISSION_ENTRY_COMMISSION_AMOUNT,
    [CALCULATED_DATE] = @PRM_COMMISSION_ENTRY_CALCULATED_DATE
WHERE
    [ID] = @PRM_COMMISSION_ENTRY_ID
    AND [IsDeleted] = 0;