SELECT [ID], [PAYMENT_AMOUNT], [FEE_TYPE_ID], [PAID] 
FROM [FLAT_PAYMENTS] 
WHERE [IsDeleted] = 0 
	AND [FLAT_ID] = @PRM_FLAT_PAYMENTS_FLAT_ID 
	AND [YEAR_ID] = @PRM_FLAT_PAYMENTS_YEAR_ID 
	AND [MONTH_ID] = @PRM_FLAT_PAYMENTS_MONTH_ID 
ORDER BY [ID] 