SELECT [ID], [PAYMENT_AMOUNT], [FEE_TYPE_ID], [DESCRIPTION], [FEE_PLAN_ID], [EXPENSE_ID], [PAID], [PAID_AT], [PAYMENT_TYPE_ID] 
FROM [FLAT_PAYMENTS] 
WHERE [IsDeleted] = 0 
	AND [SITE_ID] = @PRM_FLAT_PAYMENTS_SITE_ID 
	AND [FLAT_ID] = @PRM_FLAT_PAYMENTS_FLAT_ID 
	AND [YEAR_ID] = @PRM_FLAT_PAYMENTS_YEAR_ID 
	AND [MONTH_ID] = @PRM_FLAT_PAYMENTS_MONTH_ID 
ORDER BY [ID] 