SELECT [ID], [YEAR_ID], [MONTH_ID], [PAYMENT_AMOUNT], [FEE_TYPE_ID], [DESCRIPTION], [FEE_PLAN_ID], [EXPENSE_ID], [PAYMENT_TYPE_ID] 
FROM [FLAT_PAYMENTS] 
WHERE [IsDeleted] = 0 
	AND [SITE_ID] = @PRM_FLAT_PAYMENTS_SITE_ID 
	AND [FLAT_ID] = @PRM_FLAT_PAYMENTS_FLAT_ID 
	AND [PAID] = @PRM_FLAT_PAYMENTS_PAID 
ORDER BY [ID] 